### ISSUE TITLE
How to scroll dropdown menu back to top when filter/search text changes

### ISSUE THREAD

**Issue by sherryxiao1988** [JedWatson/react-select#1018]
Hi guys,
When user types something in the input, and then they scroll down the dropdown menu to see more filtered options, the dropdown remembers the scrolled position. So when the user types more text in the input, the dropdown remains at the position it was scrolled to before. See the gifs:
![react-select](https://cloud.githubusercontent.com/assets/1202426/15924874/42fd12e0-2de9-11e6-8b61-2dbd9cb030cc.gif)

Is there anyway to make the dropdown scrolls back to top whenever the use type in something?
Thanks!

**Comment by sunilyadav489** [comment]
Any solution on this issue?

**Comment by nemoisfree** [comment]
@sunilyadav489 @sherryxiao1988 I have the same problem :\

**Comment by davidbarratt** [comment]
This has to do with the way the browser works... it's the same div, so the browser remembers the scroll position, even if the contents change.

What we'd have to do is.. if the contents change, set the scroll position within the div using [element.scrollTop()](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollTop).

Another solution would be to force React to rerender the scrolling div (by removing it and adding it back). But since that's expensive and could cause flickering, I would just scroll the element to the top.

**Comment by lttien1** [comment]
@sherryxiao1988 

You can use ref to access DOM like that:

`<Select ref={(ref) = this.selectInst = ref} onInputChange={this.onInputChange} />


onInputChange = () => {
if (this.selectMenu) {
if (this.selectMenu.menu) {
this.selectMenu.menu.scrollTop = 0;
}
}
}
`

**Comment by pascalduez** [comment]
Not necessarily nice but seems to do the job...

```js
function MenuList(props) {
  const { inputValue } = props.selectProps;
  const inputValueRef = React.useRef(inputValue);
  const menuListRef = React.useRef(null);

  React.useEffect(() => {
    if (
      menuListRef.current instanceof HTMLElement &&
      inputValueRef.current !== inputValue
    ) {
      menuListRef.current.scrollTop = 0;
      inputValueRef.current = inputValue;
    }
  }, [inputValue]);

  return (
    <defaultComponents.MenuList
      {...props}
      innerRef={node => {
        props.innerRef(node);
        menuListRef.current = node;
      }}
    />
  );
}



<Select components={{ MenuList }} />
```

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
