### ISSUE TITLE
Can't add property context, object is not extensible

### ISSUE THREAD

**Issue by kaw2k** [JedWatson/react-select#104]
First, thank you for the awesome library! 

I just updated to React v0.13.1 and react-select is causing issues.

Error: 
> Can't add property context, object is not extensible

Warning: 
> Warning: Select(...): No `render` method found on the returned component instance: you may have forgotten to define `render` in your component or you may have accidentally tried to render an element whose type is a function that isn't a React component.

**Comment by kaw2k** [comment]
I faced the same error when using an internal component that was built with v0.12. Building it again with v0.13.1 seemed to fix it. Perhaps it would be the same here.

**Comment by kaw2k** [comment]
I upgraded from `^0.3.4` to `^0.4.2`, the error has changed to:

> Cannot read property '_currentElement' of null

Digging deeper into this.

**Comment by blakeembrey** [comment]
@kaw2k This is because the library uses React as a dependency. @JedWatson, you should be using `peerDependencies` to avoid multiple versions of React on the same page.

**Comment by rsmith72** [comment]
I had a similar error.  [package.json](https://github.com/JedWatson/react-select/blob/master/package.json) now has react.js as a peer dependency, so for me that wasn't the issue.
The issue went away when I explicitly did a require('react') in my react components and use that reference rather than depending on React being loaded from CDN in the page, which was working fine until I used react-select.

**Comment by wangzuo** [comment]
please remove react from dependencies.

**Comment by dcousens** [comment]
Based on @rsmith72's reply,  I think this issue is fixed.  Please re-open otherwise.
