### ISSUE TITLE
Tags with spaces wrap is FireFox

### ISSUE THREAD

**Issue by ryanzec** [JedWatson/react-select#1052]
So with the latest beta, the tags that have spaces will wrap in Firefox:

![screen shot 2016-06-28 at 10 23 06 am](https://cloud.githubusercontent.com/assets/444206/16419505/fa160d4c-3d1b-11e6-89f9-2e5790c0ae2d.png)

From what I can tell, it is because of this element that is at the end of each .Select-value element:

```
<span class="Select-aria-only" is="null">&nbsp;</span>
```

 The way I am fixing this is that I am overwriting the `width: 1px` that the library does with:

```
.Select--multi .Select-value .Select-aria-only {
    width: auto;
}
```

I assume that FireFox uses more than 1 pixel to render a space which is why it wraps.

@JedWatson If this seems like a fix that should be implemented in the library itself, I can write a PR but if you want to fix it is another way, then I will just leave the overwrite in my code.

**Comment by connorTang** [comment]
@JedWatson Has this been fixed? I experienced the same problem with Firefox, and it seems I can give `Select-value-label` class a property `white-space: nowrap` to fix it, as @ryanzec mentioned, I think this should be fixed within the lib itself. 

Furthermore, what's the use of `<span className="Select-aria-only">&nbsp;</span>` in `<ValueComponent>`? Why we have that extra space and span? I ask this because that extra space broke my automation, so I have to set up the automation like checking specifically value + space.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
