### ISSUE TITLE
Render selected item outside of input box for multi select.

### ISSUE THREAD

**Issue by yashkumarsharma** [JedWatson/react-select#1075]
Selected value is displayed inside input box. An option to render the selects values just below it would be nice.

**Comment by trickbz** [comment]
Also need this feature? Any ideas?

**Comment by kovinchuk** [comment]
https://codesandbox.io/s/2kyy4998y

**Comment by bladey** [comment]
Hello -

Thanks for your assistance @kovinchuk! - https://github.com/JedWatson/react-select/issues/1075#issuecomment-515380725

In an effort to sustain the `react-select` project going forward, we're closing issues that appear to have been resolved via community comments or issues that are now redundant based on their age.

However, if you feel this issue is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you, and we'll re-open it if necessary.
