### ISSUE TITLE
react-select inside label is not working

### ISSUE THREAD

**Issue by eyala-stratoscale** [JedWatson/react-select#1110]
When you put react-select inside a label with htmlFor (used for labels in radio groups) it looks fine but the value of react-select is not changing.
It seems like onchange is triggered before react-select setstate and re-renders the component
Example using your provided plunker: 
https://plnkr.co/edit/Ls1wXeRcH8nIUuSn8aCD?p=preview

**Comment by JohannesSanders** [comment]
I'm also wondering how I can focus the react-select field when you click the label.

**Comment by crbrasfield** [comment]
Here is a short preview on how I went about solving the problem:

Component:
```<Select
  name='form-field-name'
  value={this.state.selected}
  options={this.codes}
  onChange={this.changeSelected}
  />```

Method:
```changeSelected = (val) => {
    this.setState({selected: val.value})
  }```

State:
```state={
   selected: 'Select...'
}```

**Comment by ComradV** [comment]
Also have the same problem there:
https://codesandbox.io/s/l299l0ppyq

**Comment by samtsai** [comment]
@ComradV this is a bit outdated but I think you'd need to use `htmlFor` and `inputId`: https://codesandbox.io/s/vibrant-grass-tpuuy

See https://github.com/JedWatson/react-select/issues/2763#issuecomment-401775642

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!

**Comment by jediyozh** [comment]
@bladey I still have this problem
