### ISSUE TITLE
Does React-Select support to mport the 'react-select' less file directly and re-value a variable, then it take effect on the webpage control without any css compiling?

### ISSUE THREAD

**Issue by ZhangScott** [JedWatson/react-select#1121]
I am developing the 3rd party web control, and using the 'react-select'. Currently I would like to customize my control via overwriting the less variables, other than overwriting css directly, it makes more succinct in code. My question is that is it possible to import the 'react-select' less file directly and re-value a variable, then it take effect on the webpage control without any css compiling?

**Comment by nico-schneider** [comment]
Don't know if there's an easy way to do it, but I'd recommend using the override mechanisms CSS provides. Seems to me like less work/code to achieve what you want, and is slightly more update-safe, isn't it?

**Comment by burtyish** [comment]
> using the override mechanisms CSS 

@nico-schneider, did you mean the override mechanism that Sass provides?
Here's my suggestion:
Since the variables in [select.scss](https://github.com/JedWatson/react-select/blob/master/scss/select.scss) all have the [`!default` annotation](http://sass-lang.com/documentation/file.SASS_REFERENCE.html#variable_defaults_), they can be overriden by a previous definition.
So:
my-select-variable-overrides.scss file:
```scss
$select-input-bg: #BADA55;
```

custom-react-select.scss file:
```scss
@import "my-select-variable-overrides";
@import "/node_modules/react-select/scss/default";
```

**Comment by bvaughn** [comment]
Currently, both 'less' and 'scss' directories are included in the dists so you can use them however you want.

I'd recommend overriding styles using CSS though as, in my opinion, the SCSS/LESS files are source code and don't really belong in the NPM bundle. react-select provides a couple of ways to do this- you can specify your own class names or override the default (global) styles.

Closing this issue for now. I believe the question has been answered sufficiently. :smile:
