### ISSUE TITLE
Is there any known way to make the placeholder act more like a material design floating label?

### ISSUE THREAD

**Issue by muxica** [JedWatson/react-select#1126]
I'm using https://github.com/callemall/material-ui for a project and specifically need to use Chips with a multi-select, autocomplete, and search functionality. Since they don't support that yet (if ever) I did research and found react-select. It solves all of the functional issues but I'm having a hard time getting the design functionality I want.

I'm trying to accomplish the floating label text shown in this gif:
![](https://i.gyazo.com/068a26a087f31d73b148ca99ea21f244.gif)

But the only method I see so far of having labels is with `<Select ... placeholder="STRING" />`

The only way I can think to handle this is to somehow pass and subsequently override existing elements that react-select renders. Are there any existing methods built into the codebase for handling something like this?

**Comment by marcelloromanelli** [comment]
@muxica I'm running into a similar issue. What was your approach in the end?

**Comment by muxica** [comment]
There were a lot of css overrides and even then it wasn't entirely material friendly. I'd recommend actually cloning this repo and editing the source to behave how you want it to then plug it into your app.

**Comment by rahuliet** [comment]
+1

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
