### ISSUE TITLE
Bug: Too much text breaks width

### ISSUE THREAD

**Issue by gojohnnygo** [JedWatson/react-select#1127]
Looks like a long string will make this happen. Seems the component width needs to be passed into `react-input-autosize`'s `placeholderIsMinWidth` prop.

I'll be happy to do a PR. What do you think is the best course of action?

![image](https://cloud.githubusercontent.com/assets/197015/17263387/aec34692-5595-11e6-80d6-1cf075b680d6.png)

**Comment by alexlopezit** [comment]
+1

**Comment by gojohnnygo** [comment]
Just created a PR for it here https://github.com/JedWatson/react-input-autosize/pull/71. Hopefully it'll get merged.

**Comment by tsi** [comment]
Just stumbled on this issue and didn't like the option of setting a fixed pixel value as max-width since we're dealing with a fluid layout.
 
[Here's my solution](https://codesandbox.io/s/61pq3zw73), which allows us to set `max-width` in percentages, pixel or my personal favorite - `calc()`, the tricky part was just setting `table-layout: fixed`:
```
.Select-control {
    table-layout: fixed;
}

.Select-input {
    overflow: hidden;
    max-width: calc(100% - 20px);
}
```

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
