### ISSUE TITLE
Using array of values as options

### ISSUE THREAD

**Issue by lvnr** [JedWatson/react-select#1130]
It would be really nice if the options property accepted not just an array of objects, but also an array of strings and numbers, or other values, without specifying labels.

In cases where I want both the 'label' and 'value' to be the same for every option, it becomes somewhat reluctant to specify an array of objects, especially if I want to save and load the options from a database, without unnecessarily transforming/duplicating the data.

**Comment by bvaughn** [comment]
This change would require many forks in the code wherever options are displayed or selected. I understand your not wanting to transform your data before display, but IMO the additional complexity this would add to the Select component is not worth it. The component already does a lot (probably too much) and it's important to limit its functionality in order to keep it maintainable.

Going to close this issue as "won't fix" for now. If Jed or any other maintainers disagree they can reopen it of course. :smile:

Thanks for the request. Hope you understand the reasoning! Cheers.
