### ISSUE TITLE
CSS selectors should be lowercase

### ISSUE THREAD

**Issue by rantler** [JedWatson/react-select#1174]
Using mixed case CSS selectors can lead to confusion, bugs, and often conflicts with existing coding style guides. Please consider renaming the CSS selectors in this project to use lowercase exclusively.

**Comment by Abzoozy** [comment]
I totally agree, and it actually happened in our current project where my colleague forgot to add capital S for select and hence the css rule wasn't applied in our project

**Comment by bvaughn** [comment]
I agree that case-insensitive selectors might be a bit more robust. Unfortunately this kind of change can't really be made due to the fact that it would either break backwards compatibility _or_ require setting redundant classnames to support existing styles/users.

This seems like a good thing to revisit down the road for version 2.x though. I'm going to tag it as such but close it for now. I think time is too limited at the moment and 1.x is already ambitious enough.

Thanks for your understanding!
