### ISSUE TITLE
simpleValue not working 

### ISSUE THREAD

**Issue by munkh-altai** [JedWatson/react-select#1182]
simpleValue not working.

when i use simpleValue not working multi selection & your demo same

**Comment by palnes** [comment]
The latest versions have breaking changes:
https://github.com/JedWatson/react-select/blob/master/CHANGES.md

I would clone this repository and use the examples locally (`npm install && npm start`) , as the website is not up to date with the latest version.

**Comment by munkh-altai** [comment]
thank you for reply

https://plnkr.co/edit/drGR5V5KrjEzjQBZ6KMj?p=preview

this is my Plunker 
can you provide example

**Comment by munkh-altai** [comment]
I am using last version

**Comment by bvaughn** [comment]
> simpleValue not working.
> when i use simpleValue not working multi selection & your demo same

What do you mean by "not working"? Looks like it's working to me. The docs say:

> The `onChange` event provides an array of selected options or a comma-separated string of values (eg "1,2,3") if `simpleValue` is true

Looking at the Plunker you linked, the `onChange` callback is being invoked with a comma-separated string of values (eg "one,two") as would be expected. If you remove `multi` then it receives a single string value. If you remove `simpleValue` then it receives an object(s) instead. This is correct behavior. 😄

Here's an updated version of your Plunker that actually updates the select component when new values are selected: https://plnkr.co/edit/R8pGuwE2mIH8YlH2dWY8?p=preview

Going to close as "working as designed" for now since all seems correct.
