### ISSUE TITLE
Remove hidden input when multi select is empty

### ISSUE THREAD

**Issue by VictorChen** [JedWatson/react-select#1253]
When using a multi select with `joinValues`, the hidden input never gets removed.

eg:

```
<Select
  name="field-name"
  value={value}
  options={options}
  multi
  simpleValue
  delimiter="|"
  joinValues
/>
```

When the select is empty/cleared, the input still exists (with empty string as value):

```
<input type="hidden" name="field-name" value="">
```

**Comment by dave-clover** [comment]
From my understanding, joinValues brings back some "legacy behavior" that existed in earlier versions of react-select.  We are currently using this behavior in our integration tests.  You will probably have to remove joinValues if you do not want this behavior because it would be a breaking change for other developers.

**Comment by VictorChen** [comment]
It's pretty inconsistent right now where the single value Select will not include the hidden input if empty, but the multi value Select does? I feel like this should be addressed.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
