### ISSUE TITLE
Make select box editable

### ISSUE THREAD

**Issue by ImranAhmed** [JedWatson/react-select#1278]
Hi,

I am trying to use the select in (non-multi mode). I want the user to be able to either select a value from the dropdown or specify their own value. I've had a look at the Creatable option, it's a bit buggy (see: https://github.com/JedWatson/react-select/issues/1256) and it still seems like too much work to just make the select box editable.  I also do not want the custom value to appear in the dropdown menu as it does with the Creatable option. Has anyone come across an easy way you can do this? Thanks.

**Comment by ibudisteanu** [comment]
+1

**Comment by philipp-sorin** [comment]
Hey guys, what is the status?

**Comment by ibudisteanu** [comment]
@philipp-sorin no idea: I switched my project to Vue.js because the Vue is superior to react in many different ways and [Vue Select](https://github.com/sagalbot/vue-select) has this option to edit whatever you wrote (select box is editable). You can check the [demo out](http://sagalbot.github.io/vue-select/)

**Comment by philipp-sorin** [comment]
@agirton any ideas?

**Comment by philipp-sorin** [comment]
@ibudisteanu No way for me(and I don't like vue) :)

**Comment by agirton** [comment]
@philipp-sorin  We don't plan on support this feature for 1.0. We will consider this after. @ibudisteanu this comment is not helpful to this issue, removing.

**Comment by ad1992** [comment]
@agirton are we planning to have this feature? I would be happy to create a PR :)

**Comment by shamilium** [comment]
I need this feature too.

**Comment by Rall3n** [comment]
The current implementation of [Creatable](https://react-select.com/creatable) in **v2** does this by default. As long as you do not add the new value to the `options` list, the value should not appear as a selection in the dropdown.

The [example in the documentation](https://react-select.com/creatable) shows that it works that way.

**Comment by mayconmesquita** [comment]
This guy did the solution. See comment:
https://github.com/JedWatson/react-select/issues/1558#issuecomment-471657335

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
