### ISSUE TITLE
AsyncCreatable does not add value to options

### ISSUE THREAD

**Issue by lPadier** [JedWatson/react-select#1279]
In the following code, I mount an AsyncCreatable Select and when I add a value to it, `baz` for instance, it is not added to the dropdown, but I am still prompted to `Create option "baz"`
http://codepen.io/lPadier/pen/kkxQGp?editors=0011

**Comment by Stas-Buzunko** [comment]
Hi, I have the same issue with Creatable Select, have solved the problem somehow?

**Comment by midknightmare** [comment]
I am seeing the same behavior as well.  AsyncCreatable triggers the loadOptions function, but the returned values are never displayed in the dropdown.  Only the "Create option" section is shown.

**Comment by unity** [comment]
I dug into this, and found the issue seems to be the way props `asyncProps` and `creatableProps` are merged in https://github.com/JedWatson/react-select/blob/master/src/AsyncCreatable.js#L14-L15

Having a value set to undefined results in a different merging strategy than having no value set. Javascript finesse it seems.

```js
const asyncProps = {
  options: [{value: 'foo', label:'bar'}, {value: 'baz', label:'bat'}]
}
const creatableProps = {
  options: undefined
}

const merged = {...asyncProps, ...creatableProps}
console.log(merged)
```

I'll start working on a fix.
