### ISSUE TITLE
Clear cache

### ISSUE THREAD

**Issue by ttodorovski** [JedWatson/react-select#130]
When i load data from ajax search results are cached. It would be nice if cache could be cleared.

**Comment by pollen8** [comment]
looks like a bug in the code to me loadAsyncOptions.

Currently it is looping over the search term character by character. If it finds a search result cache for that character then its returning true. I really don't get why its doing that - it would mean searches for "A" and "AB" would both return the cached result for "A"!

To fix this in select.js I commented out the for loop (line 413):

````
for (var i = 0; i <= input.length; i++) {
````
and set the cacheKey to be the input...

````
		//for (var i = 0; i <= input.length; i++) {
			//var cacheKey = input.slice(0, i);
			var cacheKey = input;
			if (this._optionsCache[cacheKey] && (input === cacheKey || this._optionsCache[cacheKey].complete)) {
				var options = this._optionsCache[cacheKey].options;
				var filteredOptions = this.filterOptions(options);

				this.setState(_.extend({
					options: options,
					filteredOptions: filteredOptions,
					focusedOption: _.contains(filteredOptions, this.state.focusedOption) ? this.state.focusedOption : filteredOptions[0]
				}, state));
				return;
			}
		//}
````

Perhaps there is something I don't understand in the implementation, as I've only just started using react-select, but this change seems to be working for me

**Comment by ttodorovski** [comment]
It is not a bug. For every character you type, plugin saves async response to cache. The next time you type the same string, output is returned from cache. 

The problem is that you can't clear cache. I have fix this issue on my branch and i'm waiting for merge.

**Comment by dcousens** [comment]
@ttodorovski this is on the road map.  We intend to break out the caching component as it stands currently and allow for it to be optionally used.  Naturally, this will also provide a way for it be cleared and or reset specifically to your needs.

**Comment by janmyler** [comment]
Could there be a `trim()` function applied to the search string? Sometimes adding a space character to the input ('Barcelona' -> 'Barcelona ') displays 'No results' even though the API endpoint returns the same list of results. I assume the filtering then happens in the select component's cache internally and it produces this false 'no results' state.

**Comment by trkrameshkumar** [comment]
@JedWatson @dcousens 

`catche: false` is not removing  the data loaded through  asyncOptions from ajax search results, am i missing anything?

I am using react-select `1.0.0-rc.2`

**Comment by dtipson** [comment]
Similar problem here: two selects where one needs to limit the other, which means resetting its cache so it will refetch and reconsider what options are valid.  But while cache:false will force the component to use loadOptions again as desired (sort of) it won't actually stop the old options from appearing if the field is empty: the options are unpickable (since I've removed them from the list of options/children) but still appear as choices for the user to try.

The behavior I'd really want is more like to have caching turned on, but then have a way to change or resets the component.  I was thinking that cache could accept a string, thus namespacing the cache so that if the namespace changed, it would be a new cache.  But I haven't been able to find a way in the code to get that to work for a PR.

**Comment by maxlapides** [comment]
@dtipson I would like the same behavior! Taking advantage of the fact that you can pass an object to the `cache` prop:

```javascript
class MySelect extends Component {

    componentWillReceiveProps(nextProps) {
        if (nextProps.selectType !== this.props.selectType) {
            this.purgeCache()
            
            // reset results menu
            this.select.loadOptions('')
        }
    }

    cache = {}
    
    purgeCache = () => {
        Object.keys(this.cache).forEach(entry => {
            delete this.cache[entry]
        })
    }
    
    bindRef = ref => { this.select = ref }
    
    getResults = query => {
        // no query means no results
        if (!query) return Promise.resolve({ options: [] })
        
        // otherwise make API call
        return this.props.callApi(query)
    }

    render() {
        return <Select.Async
            ref={this.bindRef}
            cache={this.cache}
            loadOptions={this.getResults} />
    }
}
```

The idea here is when `this.props.selectType` changes, the cache is cleared. You'll notice the `purgeCache` function iterates through the cache object and deletes each entry instead of simply reassigning `this.cache` to a new empty object. This is because react-select maintains the reference to the original cache object, and continues using that, so `purgeCache = () => { this.cache = {} }` won't work.

Also, because react-select will automatically show the previously-loaded results when you click on the input again, we will want to ensure those are also cleared when the `selectType` changes, so I added some logic to handle that as well.

**Comment by jklotz** [comment]
I came across the same issue with react-select automatically showing the previously-loaded results when you click the input again. In order to both utilize caching but not see previously loaded results when the field is cleared I set the options state on the select ref instead.

`this.select.setState({ options: [] });`

**Comment by JedWatson** [comment]
This is pretty old, I'm closing it as fixed because you can reset the cache in the upcoming v2.

**Comment by mforman1** [comment]
@JedWatson was this resolved in v2? I can't find this option on the documentation.

**Comment by Orteu** [comment]
I need help with it aswell, we need to get rid of the cache on a certain moment. Still have no luck with it.

**Comment by Rall3n** [comment]
[From the docs](https://react-select.com/props#async-props):
>If cacheOptions is truthy, then the loaded data will be cached. The cache will remain until cacheOptions changes value.

So assigning the `changeOptions` prop a value that can change on demand (e.g. a counter) should suffice to reset the cache.

```jsx
state = {
    counter: 1
}

somehowIncrementCounter = () => this.setState({ counter: this.state.counter + 1 })

render() {
    const { counter } = this.state;
    
    return <Async { ... } cacheOptions={counter} />
}
```

**Comment by rangelvarnier** [comment]
I tried to use the counter, but to no avail. I am in version 2.3.0 and could not clear the cache using optionsCache. This worked in version 1.x. Does this really work in version 2.x?

> [Dos docs](https://react-select.com/props#async-props) :
> 
> > Se cacheOptions for verdade, os dados carregados serão armazenados em cache. O cache permanecerá até que cacheOptions altere o valor.
> 
> Portanto, atribuir o `changeOptions`prop um valor que pode mudar sob demanda (por exemplo, um contador) deve ser suficiente para redefinir o cache.
> 
> ```js-jsx
> estado  = {
>      contador :  1
> }
> 
> somehowIncrementCounter  = () =>  isso . setState ({ contador :  este . estado . contador  +  1 })
> 
> render () {
>      const { contador } =  isto . estado ;
>     
>     retornar < Async  {  ...  }  cacheOptions = { counter } />
> }
> ```

**Comment by rangelvarnier** [comment]
> [From the docs](https://react-select.com/props#async-props):
> 
> > If cacheOptions is truthy, then the loaded data will be cached. The cache will remain until cacheOptions changes value.
> 
> So assigning the `changeOptions` prop a value that can change on demand (e.g. a counter) should suffice to reset the cache.
> 
> ```js-jsx
> state = {
>     counter: 1
> }
> 
> somehowIncrementCounter = () => this.setState({ counter: this.state.counter + 1 })
> 
> render() {
>     const { counter } = this.state;
>     
>     return <Async { ... } cacheOptions={counter} />
> }
> ```

I tried to use the counter, but to no avail. I am in version 2.3.0 and could not clear the cache using optionsCache. This worked in version 1.x. Does this really work in version 2.x?
