### ISSUE TITLE
Add a way to customize classes or provide custom renderer for Select

### ISSUE THREAD

**Issue by blackleaden** [JedWatson/react-select#1366]
We decided to replace existing component by React-Select in our project, but there is no way to customize a markup of Select (only values and dropdown options). We're using a UI-framework (Semantic) and we don't want to support special styles for React-Select.
Now React-Selects's classes and markup are hardcoded in `render()` method of `src/Select.js`.

So, it would be great to provide a way to customize classes, or, maybe, use an external renderer.
I think custom renderer for Select is better.

Thanks!

**Comment by rmmjohann** [comment]
I started to implement this feature but stopped as I first need to discuss a few things.

I started to implement a component `selectComponent` that is responsible for select rendering and pass all relevant values via properties. The problem here is that there have to be two refs (`wrapper` and `control`) defined. `wrapper` would be no problem, but control will be as I couldn't find any hints why this ref exists. There is only one test referring to this ref and if it is defined.
`wrapper` exists to be able to determine if click/touch on body is actually an event fired from any element inside the select including its descendants or outside so the menu can be closed.

to overcome the `ref` problem a function `selectRenderer` can be used, but the returned markup has to bin the control ref to `this.control` and the method has to be bound to the `Select` or `Async` class before invocation. In addition, a bunch of arguments have to be passed to the method which leads to the direction of grouping them into objects that will be passed or by simply passing one single object.

In the End the abilities to customize behavior/rendering of Select/Option/Value/etc. could be simplified by refactoring the code to use ES6 classes and therefore enabling inheritance so the relevant methods of the components can be overridden like suggested at #1492 .

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
