### ISSUE TITLE
the `focusedOption` in `Select` 

### ISSUE THREAD

**Issue by geminiyellow** [JedWatson/react-select#1380]
hi @JedWatson, thanks for your great job.

i use this package in my project now, and i have a question.

if i do the following:

1. open dropdown menu
2. i can see the selected option's css class `is-focused: true`
3. move mouse to others option but not select it
4. click outside to close dropdown menu
5. open dropdown menu again 
6. i can see the last focus option is focused

do we really need keep the focused state? 
when i open the dropdown menu, see the `focused` style, is really confuse.

i read the code, https://github.com/JedWatson/react-select/blob/master/src/Select.js#L673-L677

```
	focusOption (option) {
		this.setState({
			focusedOption: option
		});
	},
```

you set the `focusedOption` and keep it in `Select` state, but never unset it.
when open the dropdown menu, you do the 

```
const focusedOptionIndex = this.getFocusableOptionIndex(valueArray[0]);
```

and, the `focusedOption` will be the default value by 

```
let focusedOption = this.state.focusedOption || selectedOption;
``` 

i think when the menu `isOpen`, just

```
let focusedOption = selectedOption;
```

is enough. 

how do you think?

**Comment by topheman** [comment]
Hie @geminiyellow we've got the same issue on one of our project. How did you manage to get around it ? Did you fork the repo ?

**Comment by Skylsmoi** [comment]
I used to have version 1.0.0-rc.10 and had the same issue.
I upgraded to version 1.2.1 and the issue vanished

**Comment by akarabach** [comment]
Any updates on it ?

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're cleaning up and closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
