### ISSUE TITLE
How to render only the dropdown arrow?

### ISSUE THREAD

**Issue by havardge** [JedWatson/react-select#1495]
Hi,

I would like to only render the dropdown arrow, effectively reducing the instance to a button that won't display placeholder or any selected value. Is this possible?

I looked into the various renderers I could provide as input to the component, but was not able to achieve this.

Thanks!

**Comment by rubencodes** [comment]
I would suggest styling:
```
<Select placeholder="" noResultsText="" />
```

If you also don't want anyone to be able to input, use:
```
<Select placeholder="" disabled />
```
Though you'll have to do a little custom styling if you want it to look "normal" (disabled will grey it out).

**Comment by hasufell** [comment]
This looks like a huge limitation. I think ultimately people would want to control the top-level component. E.g. I want it to be a button.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
