### ISSUE TITLE
inputRenderer not passing props on release candidate build

### ISSUE THREAD

**Issue by firebait** [JedWatson/react-select#1501]
https://plnkr.co/edit/gHpdOXGuicxgOp86AkOr?p=preview

I was trying to customize the inputRenderer but found that even though the code shows that it should pass in props:

```
if (this.props.inputRenderer) {
  return this.props.inputRenderer(inputProps);
}
```

The built version does not:

```
if (this.props.inputRenderer) {
  return this.props.inputRenderer();
}
```

There was a commit in November that added this support. I guess it just need to be built and published.

**Comment by gukii** [comment]
I also tried to add a inputProp to switch to the numeric keyboard on mobile phones. The documentation mentions this should be possible, but the   type="number   prop never gets rendered.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
