### ISSUE TITLE
is there an option to open the dropdown to the opposite direction (i.e. up) , if it reaches to the edge of the window?

### ISSUE THREAD

**Issue by ghost** [JedWatson/react-select#1515]
is there an option to open the dropdown to the opposite direction (i.e. up) , if it reaches to the edge of the window?

related to :
https://github.com/JedWatson/react-select/issues/1479

Thanks!

**Comment by alanqthomas** [comment]
+1

**Comment by josh-stevens** [comment]
Please, why hasn't this been implemented? It's been mentioned in issues since 2015, and there is even a PR open for it since September. All of the suggested workarounds in the issues say to change the CSS of the Select-menu-outer class, but I only want this to apply to a specific dropdown in my app, not all of them.

**Comment by DontRelaX** [comment]
+1, this is very important feature.

**Comment by kuppula-pmap** [comment]
I am facing the same issue. Is there any solution for this?

**Comment by adamjking3** [comment]
I also need a solution for this.

**Comment by vkmita** [comment]
+1

**Comment by eldyvoon** [comment]
+1

**Comment by ShepelievD** [comment]
+1

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
