### ISSUE TITLE
Select.Async list disappear when two selected

### ISSUE THREAD

**Issue by antoine35** [JedWatson/react-select#1561]
I have found a problem with the select.async component with multi-selection mode (true value for the multi property). Everything works fine when I select one item, but as soon as I select a second item, the drop down list empties itself.But if I start typing one character, the drop down list appears with the suggested items that match that character.

 Thanks

**Comment by diwakar-s-maurya** [comment]
+1. I am also facing the same problem. using _react-select: 1.0.0-rc.3_

**Comment by antoine35** [comment]
it seems to be better with 1.0.0-rc.2

**Comment by Jimbo80** [comment]
+1. 
With searchable=false it is impossible to select more than two items. When searchable is true you can still type to get more results.
Works fine in 1.0.0-rc.1 (couldn't get it to work in rc.2 either).

**Comment by kornholio83** [comment]
Reverted back to rc.1 and works perfectly

**Comment by traviss-comvex** [comment]
I can confirm (after hours debugging) that _react-select@1.0.0-rc.3_ exhibits the same issue as mentioned by @diwakar-s-maurya.

I downgraded to rc2 and it worked as expected

**Comment by gazpachu** [comment]
The PR is not working for me either. All the selected options disappear when starting a new search with a different letter

**Comment by eddyLazar** [comment]
Is there any progress with this issue? Facing the same problem

**Comment by mehafi** [comment]
There is still problem in 1.0.0-rc.5

**Comment by JedWatson** [comment]
I believe I've fixed this, and will release it soon as rc.9

The menu will always close by default for both single and multi-select when an option is selected, but you can change that with the closeOnSelect={false} prop.

To keep suggestions from the Async component after selecting an option, also set onSelectResetsInput={false}

**Comment by joshuahatcher** [comment]
I seem to be experiencing this same behavior on v. 1.2.0. I see that the issue was fixed on rc.9, which was from an earlier release, so I wonder if something happened to break it? I'd prefer not to revert to an rc version if possible.
I can confirm that I'm getting the exact behavior @antoine35 initially described on v. 1.2.0 of both `Select.Async` and `Select.AsyncCreatable`. I tried overriding the `clearOptions()` method to do nothing (see: https://github.com/JedWatson/react-select/issues/1542 ) to no avail.

@JedWatson - any ideas?
