### ISSUE TITLE
Detect enter key on input search box only

### ISSUE THREAD

**Issue by njbarrett** [JedWatson/react-select#1577]
Hey there,

I tried using the event onInputKeyPressed to detect when the enter key is pressed.
```
    onInputKeyDown(e) {
        if (e.which == 13) {
            console.log(e.target);
        }
    }
```

However this fires when using enter to select an item from the dropdown, whereas I want to trigger something when someone presses enter and they are not using the dropdown.

**Comment by paulokuda** [comment]
Have you tried using `e.preventDefault()`?

@njbarrett

**Comment by gkarwchan** [comment]
It is an old question , but for the people who still are looking for an answer.
There is no built-in way to detect that.
The way I did it is as follows:

on the select props provides three props:

1. first add Ref on the Select, so you can query its props values.
2.  an event handler "onKeyDown" function 
3. optional: disable openMenuOnClick, so the menu open only  when you auto-suggest.

`''js
class myselect extends Component {
  constructor(props) {
  super(props);
this.myRef = React.createRef();
}

onKeyDown(keyVal) {
  if (keyVal.key === 'Enter') {
     const {select: {state: {menuIsOpen}}} = this.myRef.current;
    if (!menuIsOpen) {
         // run what you want to do when you want to press enter
   }
}
}

render() {
   return <Select openMenuOnClick={false]
 onKeyDown = {this.onKeyDown.bind(this)}
ref={this.myRef}
/>
}
}

`''

**Comment by bfintal** [comment]
I used @gkarwchan's answer, but it only worked when I checked this property instead:

```ref.current.select.props.menuIsOpen```

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
