### ISSUE TITLE
Selecting an option doesnot show

### ISSUE THREAD

**Issue by passion4IT** [JedWatson/react-select#1589]
Selecting an option doesnot show the selected option and styles seemed to overflow.

It's possible to retrieve values but doesnot show on UI.
attached image:
![selecting an option style error and options doesnot show up](https://cloud.githubusercontent.com/assets/17505872/23657583/837545a2-0347-11e7-87ff-47af4c34f7fb.png)

**Comment by MrLeebo** [comment]
@passion4IT There is no code here and no evidence of any attempt to debug this yourself. Please consider posting these kinds of problems to your coworkers or http://stackoverflow.com/ instead.

However, I'm nice so I'm going to tell you what I think the problem is even if I don't agree with the way you asked it. Most likely there is a discrepancy between what you're storing as the `value` and what you're storing in `options`.

Consider:

```
const options = [{value: "1", label: "One"}, {value: "2", label: "Two"}]
return <Select options={options} value={2} />
```

Even though it looks like "Two" should be selected, the options value is a string and the value prop is an integer. Please check that you aren't making a mistake like this.

**Comment by passion4IT** [comment]
There was issue with my code structure. I fixed it , anyway thanks
