### ISSUE TITLE
How to clear input as you press backspace?

### ISSUE THREAD

**Issue by anshul2209** [JedWatson/react-select#1591]
-How can we get the cursor to the end of the input after the input has been selected? 
By default the cursor comes to the beginning .

**Comment by Anshul-HL** [comment]
@JedWatson

**Comment by utftufutukgyftryidytftuv** [comment]
inputValue

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
