### ISSUE TITLE
Better positioning system

### ISSUE THREAD

**Issue by FezVrasta** [JedWatson/react-select#1602]
Right now react-select positions the dropdowns right below the originating input element.
This is problematic in situations when there's not enough space on the bottom of the page or of its scrollable container because the page will be enlarged to make the dropdown fit.

If you used a positioning engine like [`react-popper`](https://github.com/souporserious/react-popper) the dropdown could be positioned where there's more available space. The library is very lightweight and supports all your use cases.

**Comment by blakedietz** [comment]
As I'm currently gathering requirements for a project this was one of the features that we were looking for. This seems like a nice feature add.

**Comment by Grsmto** [comment]
FYI in v2 you can now do `menuPlacement="auto"`. Not sure why this isn't default tho.

**Comment by jossmac** [comment]
@gwyneplaine might be time to make the move, perhaps in our next major.

CC @JedWatson

**Comment by ebonow** [comment]
The prop `menuPlacement` has been created since the creation of this issue. While the merits of @jossmac's suggestion doesn't go unnoticed, the move to react-hooks is a much larger undertaking and there are other existing issues to address menu positioning concerns (ie: available space defined from "bottom of window" instead of "bottom of ancestor node with no overflow"). As such, I will be marking this as closed.
