### ISSUE TITLE
option for manually closing dropdown menu when onBlur

### ISSUE THREAD

**Issue by bryan-foong** [JedWatson/react-select#1615]
Hi, thanks so much for this awesome component!

Is it possible to have a function to allow user manually closing the dropdown instead of closing it automatically when blurring? Because what I would like to do is to fire an action before the dropdown closes.

something like additional prop :

```onBlurCloseMenu={false}```

Then we can do:

```
onBlur={() => {
    setTimeout(() => {
        this.setState({
            dropdownVisible: false
        });
    }, 1000);
}}
```

**Comment by green-arrow** [comment]
Bumping this. Being able to manually control when the dropdown menu closes would definitely be useful for many things, such as custom animations. Right now, animating on open is easy with the `onOpen` event, but animating out is not possible.

Fwiw, my specific use case is showing the dropdown menu fixed to the bottom of the screen on mobile devices with a semi-transparent overlay on the rest of the page. Animating in is not an issue, but animating out with a slide down would need something like @bryan-foong suggests.

If you're interested in having this functionality, I can take a look at the code and see if I can get a PR going.

**Comment by vsc-github** [comment]
BUMP! There could be a function that can be called to manually close the dropdown whenever/wherever required.

**Comment by sag1v** [comment]
would be nice for a "always-opened" feature

**Comment by sergiubologa** [comment]
Any news regarding this option?

**Comment by JohnReagan** [comment]
Have another use case for this. I'm using react-select to pick time frames, with a custom Option component to allow custom date selection, see image below: 
![image](https://user-images.githubusercontent.com/6519232/71635324-819ec480-2bf1-11ea-971c-fb26b9cac39a.png)
I'd like to focus the datepicker (using react-datepicker) to allow keyboard input; however, this triggers a blur on the input and auto closes the menu. An optional prop to prevent closing on blur would work great here. Could check that prop to optionally call onMenuClose in the onInputBlur function here: https://github.com/JedWatson/react-select/blob/292bad3298f2cafad6767f2134bd79a9c27e4073/src/Select.js#L1108

**Comment by dluk** [comment]
Is there any workaround for this issue?

**Comment by ebonow** [comment]
Greetings,

This functionality and the PR associated with this was resolved in version 2 with the addition of the prop `isMenuOpen` which can be used to programmatically decide whether the menu should be open or closed.

To address the initial question as to how to accomplish such a thing in v2+, [here is a codesandbox](https://codesandbox.io/s/react-select-delayed-close-onblur-3yp76)


* Please note that setMenuIsOpen gets set to undefined instead of false to allow it to open as it normally would and not stay closed.

```
  const [menuIsOpen, setMenuIsOpen] = useState();

  const options = [
    { label: "One", value: 1 },
    { label: "Two", value: 2 }
  ];

  const delayedCloseMenu = () => setTimeout(setMenuIsOpen, 1000);

  const onChange = () => setMenuIsOpen();
  const onMenuOpen = () => setMenuIsOpen(true);
  const onBlur = () => delayedCloseMenu();

  return (
    <div className="App">
      <Select
        options={options}
        menuIsOpen={menuIsOpen}
        onBlur={onBlur}
        onChange={onChange}
        onMenuOpen={onMenuOpen}
      />
    </div>
  );

```

Given the following: 
- The age of the original post being over 3 and a half years old
- The associated PR https://github.com/JedWatson/react-select/pull/1691 being closed
- The provided working solution above

...we will be closing this issue and continuing to focus on current and future releases of react-select.
