### ISSUE TITLE
Issue with the Readme (Further options)

### ISSUE THREAD

**Issue by OttlikG** [JedWatson/react-select#1619]
Hey guys
Is there anybody who noticed this weird rendering of the Further options part of the README.

https://postimg.org/image/he7eckbgf/

**Comment by ndelbuque** [comment]
since monday its broken

**Comment by radixhound** [comment]
yeah - it's actually a major pain in the butt because I want to read that part... I looked back at old commits and it's broken in all of those places as well, so the readme didn't break. It must be something to do with github changing the way they render the markdown.

![screen shot 2017-03-23 at 9 06 40 am](https://cloud.githubusercontent.com/assets/17362/24257488/45636a38-0fa8-11e7-9f1e-41af2f3f32ae.png)

**Comment by radixhound** [comment]
I managed to fix the markdown and the rendered view can be [seen here](https://github.com/radixhound/react-select/blob/9f82da2a5cb7d098f4fabd67a302e713004ac634/README.md)

**Comment by macbem** [comment]
It looks fine when viewed raw, but yeah, thanks for the fix @radixhound - I was just looking if someone already took care of this, because I wanted to send a PR myself.
