### ISSUE TITLE
disable auto-scroll on selecting an option while in multi select mode

### ISSUE THREAD

**Issue by duanefields** [JedWatson/react-select#1634]
Anyone figure out a way to disable autoscrolling to the selected option while selection options in multi-mode? I don't want to scroll the options to the selected value, as it's is very jarring when multi-selecting. I'm prepared to fork, but can't figure out where and why that's happening.

**Comment by export-mike** [comment]
Hi @duanefields, I'm new to this project but will be looking to help out more, I'd be happy to help you with this issue. If you can help give me a bit more context on what your are seeing first that would be great.

Ideally a jsfiddle with the current behaviour you are seeing and we can go from there and discuss relevant changes.

**Comment by duanefields** [comment]
Currently, if you enable multi-select, as you select options from the dropdown menu, they scroll to the top of the menu. So, if you go half way down, click an option, it scrolls to position 1. If you are multi-selecting, it makes it annoying.

**Comment by damonbauer** [comment]
I believe this is the same issue: https://github.com/JedWatson/react-select/issues/977

**Comment by damonbauer** [comment]
@export-mike - Here's a demo of what's happening: https://codepen.io/damonbauer/pen/pemKgZ?editors=0010

When you scroll down to select an item, the dropdown "jumps" (scrolls) to the next option. Try scrolling down so that "bb" is roughly centered in the dropdown, then select it. You should see "cc" jump to the top of the list.

What I (and @duanefields) would like to happen is for the list _not_ to move at all. Think about editing a spreadsheet; when you delete a row, everything above it stays in place, and the rows below shift up.

I think a simple prop would suffice; something like a boolean of "scrollAfterSelection" would do the trick. It also looks like @serkanozer made a PR for this feature, and it accepts a function instead of a boolean: https://github.com/JedWatson/react-select/pull/1425

**Comment by BossGrand** [comment]
Experiencing this as well

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.

**Comment by Itsdarkhere** [comment]
Still relevant, please reopen !

**Comment by Kerinski** [comment]
Just add this:

new SlimSelect({
    .....
    ......
    events: {
        afterOpen() {
            document.querySelector('.ss-list').scroll({'top': 0})
        }
    }
