### ISSUE TITLE
Hint option needed

### ISSUE THREAD

**Issue by dziamid** [JedWatson/react-select#1682]
Typeaheadjs has this neat option that autocompletes input text with the first option from the list. I think they called it `hint` option. Do we have it in react-select?
![screenshot from 2017-04-24 20-13-00](https://cloud.githubusercontent.com/assets/381076/25350085/a4209116-292c-11e7-80bf-466b533dde19.png)

**Comment by agirton** [comment]
Hi @dziamid this was proposed in #1732. This will allow you to add the highlighting on your side.

**Comment by chronick** [comment]
For when the proposal goes through, here is the component I wrote to highlight the characters at the option level:

https://gist.github.com/chronick/a3c8a421581ac682fb857c95ce7e80f3

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're cleaning up and closing old issues. It appears this issue has been addressed in #1732.

However, if you feel this issue is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
