### ISSUE TITLE
Can I add a mask while I'm writing on Input?

### ISSUE THREAD

**Issue by joaoeffting** [JedWatson/react-select#1683]
Let me know if I can add some kind of mask/type while user is typing. I'm using Creatable and I need to specify a pattern to user create an option.

ex: ____/____  (this should be my "mask")

then user should create a new option like this: 2016/2017. 

And I need to let user only type numbers.

I've read the docs but couldn't find nothing.

tks

**Comment by agirton** [comment]
Hi @joaoeffting We don't support the ability to mask some numbers by default. It seems like a unique situation, so will have to think about if we want this type of feature builtin. Mind opening a PR with a proposal?

**Comment by andrevst** [comment]
Hi all, not so unique case. I got the same issue here. Needs a mask like AA99-999 on my Creatable.

looking for solutions. Ant update I let you know.

**Comment by aliogaili** [comment]
Any update on this? I can look into it as well.

**Comment by somy001** [comment]
I would also need an input mask.

**Comment by helight59** [comment]
need mask too

**Comment by Thuran** [comment]
we need mask too

**Comment by ebonow** [comment]
Greetings,

This is likely something that can be done by replacing the Input component with something like this:
https://github.com/sanniassin/react-input-mask

One consequence of this would be that removing the AutoSizeInput could cause issues when sizing the input when isMulti. Finding a way to wrap a masked input in the AutoSizeInput would be the most ideal situation, but it's not clear how simple it would be to do that.

**Comment by ebonow** [comment]
Greetings all,

I know this has been buried by a lot of time, but decided to try my hand at this. I'm sure there are more elegant solutions out there and while this doesn't directly answer the original question, thought to build something that would be a good start for someone who wanted to expand on this.

Of the different input mask solutions out there, I settled on this one due to the thoughtfulness and clarity of the article to make it easier to understand and build to personal use-cases. 
https://medium.com/outsystems-experts/javascript-events-unmasked-how-to-create-an-input-mask-for-mobile-fc0df165e8b2

Here is my codesandbox example using a credit card mask. Please feel free to use this or expand the hook as needed.
[Credit card input mask example](https://codesandbox.io/s/react-select-input-mask-4fqnf)

This should resolve the use case, but it someone wants to do more to expand the utility of this, please feel free to share with the community.
