### ISSUE TITLE
Create option maintains the last typed value after blur

### ISSUE THREAD

**Issue by OmarMustafa** [JedWatson/react-select#1719]
I'm using Select.AsyncCreatable and when dismissing the compoent and clicking again on it, the item [ Create option "abc" ] doesn't get reset. It can also be shown in the demo page ( http://jedwatson.github.io/react-select/ ).

![image](https://cloud.githubusercontent.com/assets/6657690/25977127/0fdee5e4-366e-11e7-9e97-1985c2530ee6.png)

It might be called a feature but it would be nice to have an optional parameter to override this behavior.

**Comment by agirton** [comment]
Hi @OmarMustafa as you said, we don't support this now, but feel free to open a PR. 😄

**Comment by ericnewcomer** [comment]
I've also noticed this as well but since I'm new thought my incorrect use of the component must have been causing it. Is there a sense of what the preferred change is? To me this seems like a bug and doesn't necessitate another configuration option. Happy to provide a PR, but want to be on the same page first.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're cleaning up and closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

**However, if you feel this issue is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you and re-open if neccesary!**
