### ISSUE TITLE
Ignore lib & dist when there's a viable solution for Bower & GitHub downloads

### ISSUE THREAD

**Issue by dcousens** [JedWatson/react-select#173]
I understand the reason for why there is a `src` and a `lib`, but that doesn't change the fact it is confusing, and there is nothing alluding to what the contribution or build process is.

@JedWatson could you please shed some light on this?

If the `lib/` folder is just a `reactify`'d version of the `src` folder for distribution, then just make it part of your `dist/` folder?

**Comment by dcousens** [comment]
To be honest, there is so little JSX, is there any other reason for this?

**Comment by dcousens** [comment]
The typical pre-publish solution can be found [here](http://stackoverflow.com/questions/13645824/can-i-write-npm-package-in-coffeescript).  But that does suck if you want to use the lib directly from GitHub.

**Comment by xcatliu** [comment]
By the way, what is the build process for `lib`?

**Comment by dcousens** [comment]
@JedWatson is this still meant to be the case?  Or were we going to put `lib/` in `.npmignore`?

**Comment by dcousens** [comment]
This doesn't look like its going to change.
ping @JedWatson close?

**Comment by JedWatson** [comment]
We've gone with an "ignore lib" solution for elemental and Bower builds are lagging behind :disappointed: 

I'm a big fan of _not_ doubling up on code in repos but until there's a workable solution here that doesn't break existing usage, this is where we are.

Planning to port whatever we figure out for Elemental when it lands.

In the meantime to answer an earlier question:

> To be honest, there is so little JSX, is there any other reason for this?

Because babel :sparkles:
