### ISSUE TITLE
Standalone version does not work

### ISSUE THREAD

**Issue by rycastaneda** [JedWatson/react-select#1766]
![image](https://cloud.githubusercontent.com/assets/4694510/26570674/62cf30f8-4544-11e7-9c0c-731b2afc45c7.png)
Right from the plnkr example: https://plnkr.co/edit/HTmtER9AMNcPoWhXV707?p=preview

**Comment by agirton** [comment]
Hi @rycastaneda thank you for letting us know. I'm not available to fix now, but feel free to open a PR with a fix if you would like :)

**Comment by jochenberger** [comment]
related to #270

**Comment by jochenberger** [comment]
This works with the current version:
https://plnkr.co/edit/7Nocs1ewHb7M5jLQtJDs?p=preview
You need to add `prop-types.js` however.

**Comment by CWSites** [comment]
@JedWatson please close, marked as resolved.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
