### ISSUE TITLE
two-step menu -> submenu action to select a composite key:value option

### ISSUE THREAD

**Issue by markveerman** [JedWatson/react-select#1792]
I'm trying to implement a two step selection where a user first selects from a list of `key` options and then selects from a list of `value` options. The key and value would represent a single selected option.These selections would populate a multi-select input as selected `chips`.

e.g. "Favorite Color" => [ red, orange, yellow, green, ...]

I think I'll need to provide a menuRenderer with a custom onClick that looks for the selected option.value and if it maps to one of the keys instead of calling `params.selectValue(option)` I'd call menuRenderer with the new options.

I'd appreciate any suggestions on how I might accomplish this today with the current component as I don't think it's a supported use-case.

**Comment by Taymindis** [comment]
how about this one.

[React-select with Submenu tree](https://codesandbox.io/s/react-select-tree-5sh93?file=/example.js)

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
