### ISSUE TITLE
selected-tag removed on click down not on click release

### ISSUE THREAD

**Issue by afzalah** [JedWatson/react-select#1800]
### Selected Tag removal issue

I wanted to draw your attention to an issue, when we press mouse button it immediately get removed not like normal behaviour, Let's say if a user wants to remove a tag while he press the button tag immediately get removed, meanwhile user can change his mind and can release mouse in another place on page.

### How to reproduce it.

With multi option provide some options, select some values, no try to click and keep pressing mouse button on "X" symbol in the box.

![uoi1dkrwo9](https://user-images.githubusercontent.com/28648946/27330422-9efb3c40-55b9-11e7-987c-0af872bdf175.gif)

**Comment by agirton** [comment]
Hi @afzalah you are right, we use `mousedown/touchend` events to remove the tag. 

@JedWatson it looks like this has been there since the initial rewrite. What was the primary reason for using `mousedown` instead of `click`?

@afzalah In the mean time you can overwrite this behavior by using your own Value component and then use the `click` event.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're cleaning up and closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
