### ISSUE TITLE
Creating a dropdown menu

### ISSUE THREAD

**Issue by JHRms** [JedWatson/react-select#1804]
How would you create a dropdown menu where the original text on the menu remains the same, two options appear when the dropdown menu is clicked, and when one of the options are clicked, it leads to some other functionality without changing the original text. (no typing or searching needed, just a simple dropdown)

**Comment by agirton** [comment]
Hi @JHRms great question. Since this is a select component you will have to work around the fact that typically selecting a value in the option would change what you see in the input. Depending on your design you may want a value passed in so you don't have placeholder text. Also you will need to write your own `menuRenderer` to intercept the onSelect method calls. You can see the `defaultMenuRenderer` [here](https://github.com/JedWatson/react-select/blob/master/src/utils/defaultMenuRenderer.js)
