### ISSUE TITLE
show option select menu under current cursor / add new option for custom function

### ISSUE THREAD

**Issue by TopWebGhost** [JedWatson/react-select#1813]
I've started using this react-select. This is really awesome.
I need help to look for possibilities to show option select menu under current cursor and add new option for custom function at the bottom of the option.
Here is the design you can get more info.
https://s2.postimg.org/l25k0zkwp/design.jpg
Thanks

**Comment by agirton** [comment]
In order to do this you would need to do a lot of custom work that we don't support out of the box. Based on the design the left position of the `Select-menu-outer` would have to be dynamic. This isn't on our road map for 1.0 to provide. Will mark this as a feature request for after 1.0. In the mean time I would recommend to fork the repo and you can build out the functionality.

**Comment by TopWebGhost** [comment]
ok. thanks for your help.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
