### ISSUE TITLE
Doesn't allow search with asterisk(*) in search text

### ISSUE THREAD

**Issue by sampatbadhe** [JedWatson/react-select#1864]
When I am searching data with asterisk(*) character in it, ajax returns the result, but it wont displayed in the select list. 

example: 
I have search engine which search by starts_with, for partial search I need to add asterisk(*) in front of the string.
- Apple
- Pineapple
- Crusted Apple  
- Bilberry
- Blackberry
 
If I search for `App` it return the following result 
- Apple
- Crusted Apple 

To get `Pineapple` to included in the list I need to add asterisk in front of apple like `*apple`

When I add asterisk(*) ajax call returns the result, but the result is not shown in the list.

**Comment by agirton** [comment]
Hi @sampatbadhe you will need to override the `filterOptions` prop to allow this behavior.

**Comment by sampatbadhe** [comment]
Thanks @agirton :+1:

**Comment by bladey** [comment]
Hello -

Thanks for your assistance @sampatbadhe!

In an effort to sustain the `react-select` project going forward, we're closing issues that appear to have been resolved via community comments or issues that are now redundant based on their age.

However, if you feel this issue is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you, and we'll re-open it if necessary.
