### ISSUE TITLE
scrolling broken in demo

### ISSUE THREAD

**Issue by savv** [JedWatson/react-select#1865]
To repro:
1. http://jedwatson.github.io/react-select/

2. press drop-down triangle in react-select component

3. This is what I'm seeing under osx 10.12.5 / chrome 59.0.3071.115 (Official Build) (64-bit)

![broken-cities](https://user-images.githubusercontent.com/747519/27968483-1b49dc42-633f-11e7-975c-4b7c0ca7986d.gif)

**Comment by agirton** [comment]
Looks like due to a CSS issue with how we are loading `react-virtualized` styles. Would you like to submit a PR to fix?

**Comment by davidxll** [comment]
This is an issue of react-virtualized@9.10.x [822](https://github.com/bvaughn/react-virtualized/issues/822). It has been around for a while. I hope this helps 👍

**Comment by bvaughn** [comment]
FYI react-virtualized 9.11 will be going out with this fix shortly.

**Comment by karaggeorge** [comment]
This doesn't happen locally. If I clone and run the code locally, the list is smooth. Maybe the demo needs to be rebuilt?

react-virtualized now has 9.12.0 and has fixed that. Maybe worth updating the dependency?

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're cleaning up and closing old issues that appear to be resolved via community comments.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
