### ISSUE TITLE
Select close button(Select-arrow-zone) does not work on mobile 

### ISSUE THREAD

**Issue by ohsik** [JedWatson/react-select#1875]
Does anybody experience that Close button on multi select(Select-arrow-zone) does not work on mobile or tablet but works good on desktop. 

Arrow up button on the right does not work on mobile.
![image](https://user-images.githubusercontent.com/4256774/28250813-9c288a28-6a26-11e7-9d76-88e899a5eb03.png)

**Comment by agirton** [comment]
Hi @ohsik looks like we are using `onMouseDown` instead of `onClick`. @JedWatson do you remember why this is the case?

**Comment by JulianSuringa** [comment]
does anyone fix this in mobile view on touch arrow not closing?

**Comment by ctkc** [comment]
Here, the same error.

**Comment by mbenjamin618** [comment]
+1

**Comment by suryakun** [comment]
Any update for this bug??

**Comment by sptaszek92** [comment]
the same problem here. Any updates??? @JedWatson

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're cleaning up and closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
