### ISSUE TITLE
Uncaught Error: Cannot find module 'create-react-class'

### ISSUE THREAD

**Issue by QuyetMai** [JedWatson/react-select#1877]
Uncaught Error: Cannot find module 'create-react-class'
    at s (react-select.js:1)
    at react-select.js:1
    at Object.<anonymous> (react-select.js:823)
    at Object.5../Async (react-select.js:2038)
    at s (react-select.js:1)
    at e (react-select.js:1)
    at react-select.js:1
    at react-select.js:1
    at react-select.js:1

**Comment by agirton** [comment]
Hi @QuyetMai this is most likely a dependency issue where you also need to include this. This will be fixed in the next build where we won't rely on create-react-class any longer. If you are unable to solve this on your end until we release, I would recommend to downgrade to a previous version like rc3.

Since this question has been asked before (#1727) going to close this.
