### ISSUE TITLE
Add generic onClick event

### ISSUE THREAD

**Issue by marcselman** [JedWatson/react-select#1912]
I have a select with a couple of disabled options.
What I need is to trigger an action when someone clicks on a disabled option.
For me it would be best if there was a property on the select 'onClick' or 'onOptionClick', or something like that, that gets called everytime an option is clicked whether it's enabled or disabled. The option could be passed as parameter.

Can this be added? Or is there another way for me to implement this?

Thanks

**Comment by joseferrer1090** [comment]
Hello @marcselman  I have the same problem, I would like you to tell me how you solved the problem or did you change the library, because in my case depending on the option I have to call an async method that brings me the data of one of the options found in the select..... 

Please help me !!! 👍

**Comment by Balachandar-K** [comment]
Any solution for this?

**Comment by abury** [comment]
I'm struggling with this as well. Even with a custom option component, it looks like something further up the chain is swallowing the onClick and not passing it further down

**Comment by marcselman** [comment]
In my specific case I've decided to have an active option and handle the click on that with a notification and deselect it. It's not pretty but good enough for our purposes.

**Comment by ebonow** [comment]
Greetings @marcselman ,

**NOTE: onClick will not work.** The options are mapped to the `onMouseDown` and `onTouchEnd` event handlers which fire prior to onClick.

Also note that a future release will include the bug/feature request https://github.com/JedWatson/react-select/issues/4195 which will add the disabled attribute to the Option disabling all mouse events on the dom element.

Therefore, you would not be able to rely on making the Option disabled, but instead would have to contrive your own method of styling and having it behave as disabled. If you would like to add any click handlers, you can do so onto the `innerProps`. Since `onTouchEnd` and `onMouseDown` are already mapped to select the option, you would want to override these if it should appear to be disabled. 

``` JS 
const Option = ({ innerProps, className, ...props }) => {
  const { onMouseDown, onTouchEnd } = innerProps;
  const disabledAction = props.data.shouldAppearDisabled
    ? doSomethingWithDisabledOption : false

  const newInnerProps = {
    onMouseDown: disabledAction || onMouseDown,
    onTouchEnd: disabledAction || onTouchEnd
  }
  
  return <components.Option 
    {...props} 
    className={`react-select__option--is-disabled ${className}`}} 
    innerProps={newInnerProps} 
  />
}
```

In regards to styling, there are a variety of ways that this can be done including the way demonstrated above.

I will be closing this ticket to move onto to review other issues, but please let me know if you come across any problems implementing a solution and I can do my best to assist.
