### ISSUE TITLE
Creating new options with AsyncCreatable and Modal

### ISSUE THREAD

**Issue by justtonytone** [JedWatson/react-select#1935]
I am attempting to use the AsyncCreatable component and would like to open up a modal when a user attempts to create a new option (to gather more information for the option).

I tried passing in `onNewOptionClick` to the component, but I am not seeing a way to add the new option after the user has finished with the modal.

I'm thinking perhaps `onNewOptionClick` can be passed in a callback function that adds the option once the function is ready.

Something like:

```javascript
if (isOptionUnique) {
  const callback = (option) => {
    options.unshift(option);

    this.select.selectValue(option);
  };

  if (onNewOptionClick) {
    onNewOptionClick(option, callback);
  } else {
    callback(option);	
  }
}
```

Is there already a better/existing way to accomplish this?

Thanks

**Comment by EvelyneWang** [comment]
Hi, did you find a way to fix this? I have exactly the same problem.

Thank you.

**Comment by justtonytone** [comment]
Unfortunately no, but I believe my suggested change in the original post would work. I have not gotten around to forking and making the change to test, but hopefully it would be accepted as a simple PR.

**Comment by nafg** [comment]
There's a workaround described here that worked for me: http://www.shahqaan.com/blog/react-select/
Basically, skip `onNewOptionClick` -- use `onChange` and detect whether it's a "regular" option or the new option placeholder by testing what properties it has. For instance the placeholder option is given a className property.
In my case, my options have a `data` property so I test if it's not there instead.

**Comment by AhmedFat7y** [comment]
Have anyone found a workaround for this? It seems the Creatable (even in V2) is expecting simple create scenario where you create new tags. It doesn't account for async creation where you open a modal for user to fill a new form, or submit new data to server.

Is there any plans for including this later on?

**Comment by nafg** [comment]
@AhmedFat7y I've used the workaround I described successfully. Instead of ignoring it except to give it a thumbs down and then asking "has anyone found a workaround for this," perhaps you could be so kind as to share why you don't consider the workaround mentioned to be worth thinking about.

(Yes, it's a workaround, of course it would be nice if the workaround weren't necessary and the API supported it properly.)

**Comment by AhmedFat7y** [comment]
@nafg I'm very sorry if this was inappropriate in anyway.

The case I wanted to solve was to create new options asynchronously.  I'm using react-select v2 for list of users. If a user is not there, create it. To create a user, I open a modal window, submit the result, then somehow I need to pass the response back to react-select.

Although the case might not be exactly the same, it's close to the issue description. However, what you suggested won't solve the issue for me. I thumbed it down because I thought it's not a workaround for this issue.

I might have misunderstood your workaround or suggestion, so I should've asked first I guess.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
