### ISSUE TITLE
SSR mutation issue

### ISSUE THREAD

**Issue by dmytro-lymarenko** [JedWatson/react-select#1970]
These lines
https://github.com/JedWatson/react-select/blob/e65c45bb927926202738b140c07fed5951afba81/src/Select.js#L38
and https://github.com/JedWatson/react-select/blob/e65c45bb927926202738b140c07fed5951afba81/src/Select.js#L78
 cause SSR mutation if `instanceId` wasn't passed by parent component because `instanceId` is global and we can't control it by parent component.

In my project `instanceId` was 3 on the server but on the client it was 2.

So we should either remove that global var or make `instanceId` prop as required.

**Comment by JedWatson** [comment]
It's not a required prop because we shouldn't force everyone to provide it when they're not using SSR. So we need a default for this, for accessibility - which is why we have the global. We could generate a random id but that would have the same or worse effect.

Sounds like what's happening is the Select components are being mounted in a different order on the server and the client; But you should be able to fix this by specifying or deterministically generating the `instanceId` prop in your app.

**Comment by dmytro-lymarenko** [comment]
But please, add it to docs (as optional)! because It took some time for me to find the problem
