### ISSUE TITLE
Custom label

### ISSUE THREAD

**Issue by trungnguyencmu** [JedWatson/react-select#2105]
Can we implement that ?
Currently, label of option always is string
![image](https://user-images.githubusercontent.com/8305733/32098147-f918b3ba-bb35-11e7-8dbe-d42eefbb9af8.png)

**Comment by karaggeorge** [comment]
On the demo (http://jedwatson.github.io/react-select/), see custom Render Methods

**Comment by Jessica7** [comment]
Hi @trungnguyencmu, I did custom label with this format, I hope that it helps you https://codesandbox.io/s/8zv2w5o6k0

**Comment by rakesh25** [comment]
> On the demo (http://jedwatson.github.io/react-select/), see custom Render Methods

That link is broken.

**Comment by rakesh25** [comment]
> Hi @trungnguyencmu, I did custom label with this format, I hope that it helps you https://codesandbox.io/s/8zv2w5o6k0

`optionRenderer` and `valueRenderer` is the key! Thank you @trungnguyencmu

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
