### ISSUE TITLE
Expose open() function as public or as a prop

### ISSUE THREAD

**Issue by leqwasd** [JedWatson/react-select#2106]
Use case - I will show `react-select` in `react-contextmenu` for a table columns. Select options will be all of the hidden columns. So user can right click on the table header and in `react-select` choose or search for a column to add to the table.
At the moment, I didnt see any exposed functions that would open the menu automatically in render.
I think, at the moment, I can achieve this by calling `selectRef.setState({isOpen: true})` the moment I show contextmenu. But this is a dirty and incorrect way.

**Comment by wildeyes** [comment]
how do you get the selectRef?

**Comment by lucasveigaf** [comment]
I was looking for something like this as well. You can achieve this by setting both `autoFocus` and `openMenuOnFocus` props.

**Comment by TylerRick** [comment]
For what it's worth, it looks like you can programmatically trigger it to open with `onMenuOpen`:
```
selectRef.onMenuOpen()
selectRef.onMenuClose()
```
Looks like this also updates the internal `menuIsOpen` state correctly.

Slightly less dirty than setting `selectRef.setState({menuIsOpen: true})` directly, but still feels dirty, because
1. it's an undocumented API
2. `onMenuOpen` wouldn't *necessarily* have a side effect of opening the menu and setting the `menuIsOpen` state; it *could* also be defined as simply what gets called as the side effect *of* setting `menuIsOpen` state to true (called from a `useEffect` callback, for example).

I'd still prefer a public API that we can call to trigger open, like `open()` as OP suggested.

**Comment by TylerRick** [comment]
> I was looking for something like this as well. You can achieve this by setting the `defaultMenuIsOpen` prop to `true`. 

That only works when rendering the Select for the first time. If it already on screen and was initialized with the menu closed (the default), then setting `defaultMenuIsOpen` prop to `true` will not trigger it to open. Which means you can't trigger it to open that way from a button click, for example.

Setting `menuIsOpen` prop to `true` (from, say, a button click) _will_ trigger it to open, but that is problematic because it forces the menu to *stay* open and prevents the Select from managing its own `menuIsOpen` state. You can work around somewhat that by resetting the `menuIsProp` to `undefined` from `onBlur` and `onChange` callbacks. But it prevents the user from closing the menu by pressing Esc (and I didn't see any `onPressEscape` callback).

So the only way to one-time trigger the menu to open without forcing it to stay open — and without having to manage a bunch of state in your container component — appears to be to get a ref and call 
 `selectRef.onMenuOpen()` on it.

Hopefully that will become part of a public API with a better name like `open()` in the future.

**Comment by lukebennett88** [comment]
Hi @leqwasd,

In an effort to sustain the react-select project going forward, we're cleaning up and closing old issues and pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of react-select please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
