### ISSUE TITLE
On click handle on open drop down

### ISSUE THREAD

**Issue by joinsunil** [JedWatson/react-select#2139]
I need on click handle on click on drop down to open it. How can I get that ? I need something like this ...

https://select2.org/getting-started/basic-usage

**Comment by cicco94** [comment]
Hi, use the onMenuOpen and onMenuClose events
![react-select](https://user-images.githubusercontent.com/18578156/73470748-44f4f300-4380-11ea-9774-ffffc14085bb.PNG)

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
