### ISSUE TITLE
onFocus and onOpen are both called on menu close 

### ISSUE THREAD

**Issue by Frezzaldo** [JedWatson/react-select#2151]
I want to run some code when the menu open and not on close. I have tried to use onFocus and onOpen but they are both also called when the menu close.

**Comment by karaggeorge** [comment]
https://plnkr.co/edit/h8u0Q8v0I9sAW5L7Coud?p=preview

This simple example logs when `onOpen` or `onFocus` are called in the console. I try opening and closing the menu and I only get logs when it opens. Can you provide a test case where the behavior breaks?

**Comment by cicco94** [comment]
Hi, use the onMenuOpen and onMenuClose events
![react-select](https://user-images.githubusercontent.com/18578156/73470602-08c19280-4380-11ea-8408-4db9f91ba62e.PNG)

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
