### ISSUE TITLE
Copy changelog to releases tab

### ISSUE THREAD

**Issue by XaveScor** [JedWatson/react-select#2173]

**Comment by JedWatson** [comment]
I'll consider this in the future but at the moment, there's already a large amount of overhead just maintaining the changelog itself and heaps of work to do triaging PRs and issues.

If there's an automated way to populate releases, I'd be happy to get that set up, otherwise I'm not keen to add more overhead - the changlog is easy enough to find.

**Comment by juanpicado** [comment]
We use `standard-version` in our project, to be honest at the beginning I wasn't convinced but now each release is so easy. 

https://github.com/conventional-changelog/standard-version

It' must be painful modify manually the `HISTORY.md` each time.
