### ISSUE TITLE
Warning: `ref` is not a prop

### ISSUE THREAD

**Issue by sabina4** [JedWatson/react-select#2181]
Hello,

I am using ref in <Select.Creatable ref={(node) => this.selector = node} /> and getting this warning:
CreatableSelect: `ref` is not a prop. Trying to access it will result in `undefined` being returned. If you need to access the same value within the child component, you should pass it as a different prop.

**Comment by aaronincincy** [comment]
This appears to be causing warnings for me (react-select@1.1.0, react@15.6.2). I'm using ref={r=>this.selector = r} and getting:

Warning: CreatableSelect: ref is not a prop. Trying to access it will result in undefined being returned. If you need to access the same value within the child component, you should pass it as a different prop. (https://fb.me/react-special-props)

I believe this is because ref is reserved, so you can't really pass it through like you are. If you renamed it to selectRef for Creatable (and updated the documentation for this exception to the Select API) I believe that would solve the issue.

My code seems to still work ok (it was working before upgrading from rc10), but I'd like to get rid of the warning if possible.

**Comment by jonfreedman** [comment]
I am also seeing this warning in the console, it would be great to be able get rid of it.

This is with react 16.2.0 & react-select 1.2.0

**Comment by x2es** [comment]
Also got this warning.
React docs suggest to use `kindOfCustomRef` prop instead `ref`
https://reactjs.org/docs/refs-and-the-dom.html#exposing-dom-refs-to-parent-components

**Comment by lynxtaa** [comment]
As temporary solution, you can wrap Creatable in class-based component like this: 

```jsx
import { Creatable as ReactSelectCreatable } from 'react-select'
class Creatable extends React.Component {
  render() {
    return <ReactSelectCreatable {...this.props} />
  }
}
```

**Comment by jfengel** [comment]
I am also seeing this error, but oddly, only via react-virtualized-select. When I use the component directly, it presents no problems.

The error, as far as I can tell, refers to the `ref: PropTypes.func` on line 293. When I remove it, the problem goes away.

**Comment by Moejoe90** [comment]
Any updates regarding this?

**Comment by diogocorrea** [comment]
+1

**Comment by donperi** [comment]
+1

**Comment by Stardog** [comment]
I get this warning. I am using ref on a Creatable to clear the inputValue after creating a new entry.
```
newOptionClick(value) {
  this.props.newOptionClick(value)
  this.tagSelect.current.select.setState({inputValue: ''})
}

render() {
return <Creatable
          ref={this.tagSelect}
          multi={true}
          options={this.props.tags}
          value={this.props.entryTags}
          onNewOptionClick={this.newOptionClick}/>
}
```
Using "innerRef" does not work. Anyone know of an alternate method?

**Comment by Cattari** [comment]
If someone needs a workaround - here it is. It worked perfectly for me.

`{props => (
            <Select
              {...props} 
              ref={ref => {
                props.ref(ref)
                selectNode = ref
              }} />
          )}`

**Comment by umphy** [comment]
I found that there is an extra level of indirection with a Creatable. So for the following code:
```
return (
	<Creatable
		ref={selectRef}
		...
	/>
)
```

In order to get to the actual select reference to clear a value, you will need (note the 2 select):
```
selectRef.current.select.select.clearValue()
```

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!

**Comment by AleksandrHovhannisyan** [comment]
I think the fact that multiple people reported this issue, without a fix ever being pushed, is an indication that "this issue is still relevant."

**Comment by bladey** [comment]
Thanks for the feedback @AleksandrHovhannisyan.

**Comment by AleksandrHovhannisyan** [comment]
Sorry for that little outburst, lol. I solved my issue using `React.forwardRef` (https://reactjs.org/docs/forwarding-refs.html).

**Comment by ebonow** [comment]
GIven the use of `React.forwardRef` and that these issues seem to reference v1.2 where as current version is v3.1.1, I think it would be fair to close this issue.

If there are any other objections, we can re-open but our intention is to close older issues to create greater transparency on what is left to stabilize and improve react-select and not to leave anyone feeling unsupported for closing out a 3yr old issue on a deprecated version.
