### ISSUE TITLE
Can we display a text when there is no more options available?

### ISSUE THREAD

**Issue by jvenezia** [JedWatson/react-select#2214]
I use `removeSelected={true}`, it would be nice to display a text similar to `noResultsText` when all the options have been selected (no more options available to select) and the input is focused.

Is there an option to do that currently?

**Comment by loopmode** [comment]
In v2 you can override the `NoOptionsMessage` component, see https://react-select.com/components

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
