### ISSUE TITLE
react-select multi overlapping next element in safari

### ISSUE THREAD

**Issue by milencheto** [JedWatson/react-select#2308]
Hello, I have this kind of problem, that  when I click and add more then two options from the list of options, the array of chosen items overlap the next element. And this continue till I clicked somewhere on the page... After that it recalculates the height maybe and it looks good. And that problem comes only in safari. Can you help me in some way, please?
![image](https://user-images.githubusercontent.com/10586251/35095259-7b8ee386-fc50-11e7-9e6c-69695c63833f.png)
after clicking somewhere on the page:
![image](https://user-images.githubusercontent.com/10586251/35095390-ecc4041e-fc50-11e7-8ca4-c8becc40cf35.png)

**Comment by jennysjogren** [comment]
Experience the same issue. 

It is reproducible using Safari (OSX & iOS) for the multi select example:

![screen shot 2018-02-13 at 17 09 30](https://user-images.githubusercontent.com/141627/36160261-012be3be-10e1-11e8-88ab-36fd74853e68.png)

**Comment by Tape** [comment]
I've narrowed this down to the autosize input. Setting the property `autosize` to false looks ugly but it stops the overlapping.

**Comment by tamitutor** [comment]
Setting `autosize` to false is not a solution.  This should not be happening.

**Comment by tirdadc** [comment]
I can confirm that this only happens on Safari, not Chrome or Firefox.

My temporary fix is to at least increase the `z-index` on the focused select so that it looks less messy, but this could still use an actual fix to push elements down properly like on other browsers.

```
.Select.is-focused {
  z-index: 5000;
}
```

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
