### ISSUE TITLE
select as data table cell

### ISSUE THREAD

**Issue by bsr203** [JedWatson/react-select#236]
I am trying to render select on fixed-data-table, and met with some issue. Please see the details here http://stackoverflow.com/questions/30675743/positioning-a-select-component-within-data-table-reactjs-component

Has anyone managed to something similar, or any help on how I could make progress on this?

I will close this issue as soon as I get some feedback on this. thanks a ton.

**Comment by brianreavis** [comment]
In my experiences with fixed-data-table, it's best to wrap your elements in a `<div>` instead of returning them directly from the cell renderer. The styles do some funky things to the cell elements. Give this a try:

```js
function renderSelect(){
  return <div><Select options={ops} /></div>;
}
```

That said, this is an implementation problem – not really a problem with react-select itself. For the sake of keeping the number of issues sane, I'm going to close this. If you find anything out on this, definitely feel free to add it here for anyone else searching :)

**Comment by bsr203** [comment]
thanks brian. that didn't work, but I understand it is not an issue with react-select. Will get back to this if I make any progress.
