### ISSUE TITLE
Passing valueKey and labelKey into valueRenderer and optionRenderer

### ISSUE THREAD

**Issue by jiangweiliu-aa** [JedWatson/react-select#2400]
**Our use case:**
We customize `valueComponent`, `valueRenderer`, `optionComponent`, `optionRenderer`, and make this `customized select` as a base component. 

Because both `valueRenderer` and `optionRenderer` can't visit `valueKey` and `labelKey`, each time we use `customized select component` with different `valueKey and labelKey`, we need to pass a specific `valueRenderer` and `optionRenderer`.  That's is not the best practice. 

To make our life easier, I purpose passing `valueKey` and `labelKey` into `valueRenderer` and `optionRenderer`.  

**Example code:**

modify https://github.com/JedWatson/react-select/blob/master/src/utils/defaultMenuRenderer.js#L52 with:
 `{optionRenderer(option, i, inputValue, valueKey, labelKey)}`

in `renderValue` of `src/Select.js`:
    modify https://github.com/JedWatson/react-select/blob/master/src/Select.js#L831 with :
    `{renderLabel(value, i, labelKey, valueKey)}`
    modify https://github.com/JedWatson/react-select/blob/master/src/Select.js#L847 with:
    `{renderLabel(valueArray[0], labelKey, valueKey)}`

Here is the PR I created https://github.com/JedWatson/react-select/pull/2407/files

Looking forward for your approve!

**Comment by jossmac** [comment]
Oops, looks like the PR is being considered for v1 -- i'll leave this open until that's decided.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
