### ISSUE TITLE
selectOption comparison not working for multi Select

### ISSUE THREAD

**Issue by ivosabev** [JedWatson/react-select#2403]
In Select.js 

```
selectOption = (newValue: OptionType) => {
    const { isMulti } = this.props;
    if (isMulti) {
      const { selectValue } = this.state;
      if (this.isOptionSelected(newValue, selectValue)) {
        this.setValue(
          selectValue.filter(i => i !== newValue),
          'deselect-option'
        );
      } else {
        this.setValue([...selectValue, newValue], 'select-option');
      }
    } else {
      this.setValue(newValue, 'select-option');
    }
  };
```

`i !== newValue` this comparison compares if two JSON objects are the same, not if their contents is the same, which causes the select not to recognize the unselected value as it might be a different JSON in memory, but with the same {label, value} contents.

**Comment by ivosabev** [comment]
Any comments on this?

**Comment by inv8der** [comment]
I just ran into this issue as well. With the combination of redux/reselect/normalizr, comparisons using strict equality will often return false since the objects will reference different locations in memory, although the content may be the same. 

This is especially problematic for the Async component, where the selected value may need to be fetched from an API, as `defaultOptions` may not include it. When `loadOptions` does include this value, it will naturally reference a different object in memory.

It would be nice if you could supply a custom comparator via props.

**Comment by inv8der** [comment]
Actually, I think this can be solved by using `getOptionValue` to get the values to compare. Since you can specify your own `getOptionValue` via props, you customize how the comparison is made. I'll try my hand at a pull request.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
