### ISSUE TITLE
limit the number of select-options built in DOM

### ISSUE THREAD

**Issue by barbalex** [JedWatson/react-select#242]
Hi

I love the looks and functionality of this tool and tried using it in my application.

It is very slow and sluggish.

I guess that is because it builds a DOM-element for every option passed. In my case these are 20'000.

I don't know anything about the internals of react-select. But is it possible to create an option to limit the max number of options displayed in the dropdown (for example 20) while applying the filter to all passed options (in my case 20'000)?

That might speed things up a lot for big datasets.

**Comment by fmovlex** [comment]
The <select> pattern is not really built for 20k+ items... you're probably using it as a autocomplete/typeahead sort of dropdown?

I have a similar case with ~5000 items, but I just use asyncOptions and return ~30 results myself (you can do it in-memory, doesn't really have to be async).

**Comment by barbalex** [comment]
yeah, turns out you are right
I tried react-typeahead and it is BLAZING fast
sorry for bugging!

**Comment by kn0ll** [comment]
so, i know this issue is closed. but there is still a pretty drastic slowness with large lists that i've been able to address (in some way).

virtualized select handles the *rendering* of large lists just fine. but typeahead / search time compounds (linearly?) as the number of options increases. search actually blocks up the UI thread too, making typing feel sluggish for sufficiently large lists. 1k items is slow. 5k items is barely usable (it takes seconds for a key i press to appear in the input).

i've been able to attribute the slowness in typeahead to stripDiacritics. if i set `ignoreAccents` to false, search is instant. so, if you have very large lists and can ignore accents, you will find an simple, immediate, and very significant performance improvement just by setting this option.
