### ISSUE TITLE
Using debounce on loadOptions doesn't always show results

### ISSUE THREAD

**Issue by rynmng** [JedWatson/react-select#2476]
When I use lodash's debounce on my `loadOptions` handler, typing doesn't behave consistently (results are missing, spinner is showing indefinitely) for certain inputs.

When the debounce is removed (and requests are fired for every keystroke), options are consistently shown. I've also tried setting `cache={false}` to no avail.

Sample here:
https://codesandbox.io/s/xplr0lly8w

To see this weird behavior, type a few letters of a github username into the text input. Observe it not really-but-sort-of-working.

To see it working consistently, remove `this.getUsers = _.debounce(this.getUsers, 250);` in the constructor.

This occurs on react-select 1.2.1. Let me know if you need any more info to repro.

Also just wanted to say you guys and gals are doing great work!

**Comment by JAndritsch** [comment]
I think you need to use the callback option instead of returning a promise if you use debounce.

I changed your example in this snippet and it now works: https://codesandbox.io/s/mm16n2x5k9

**Comment by rynmng** [comment]
Sorry for the late reply, and thanks for responding!

I tried your example but it still has weird behavior. For example, my github username is "rynmng". 

If I type "ryn", I'll get a partially matching list of results as expected. Pause for a moment, then type a few more letters, say "mng" - you may get my username. Then try deleting some letters - you won't get a result at all in this case.

I don't see this issue at all when I remove the debounce.

**Comment by pavel-beloborodov** [comment]
@rynmng Didn't work for me too. Same weird behaviour.

**Comment by JonathanWbn** [comment]
I managed to find a way to avoid the weird behaviour, here is a [sandbox](https://codesandbox.io/s/kx5l87yk95).

I don't know if this is the desired result, but I thought I would share it just in case.

**Comment by rynmng** [comment]
@JonathanWbn that seems to work - there's a subtle difference between how you call the debounced method (your method calls a debounced fetch) vs how I'm doing it (I change the onload method to be debounced itself and then pass it to `react-select`).

Do you know why this works? If I can grok this, I'd be happy to update the docs so this is clear (unless this is a bug...?)

**Comment by webmobiles** [comment]
@JonathanWbn I've run again, and it's work when you type without change, the first test i was playing deleting and using backspace, i'll try again to reproduce it

**Comment by webmobiles** [comment]
I did it, it's github api problem , not your code, thanks ! , in console "API rate limit exceeded for 78.216.64.172. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)"

**Comment by quangleminhvn** [comment]
Hi guys, any update on this?
I got the same issue as @rynmng mention

**Comment by dixitk13** [comment]
Hey, @rynmng and @quangleminhvn, I faced the same issues as you, because I call the debounce method with different parameters and the cache wouldn't update. 

I tried a different key prop to the Component based on this parameter and react would re-render the component for me, solving the issue as of now. Try it out, lemme know if that works.

Cheers 🥂

**Comment by jossmac** [comment]
@rynmng @JonathanWbn it sounds like this is resolved -- please comment if this is still a concern, and needs to be re-opened.

**Comment by ADTC** [comment]
@jossmac is it possible to enhance the documentation with a verified official method to do debouncing correctly with `loadOptions`? Because I had found it a struggle to piece everything together using this issue and the sparse documentation.

Here's the modified CodeSandbox, updated to the latest versions of dependencies: https://codesandbox.io/s/laughing-margulis-rb5tsu?file=/src/index.js

Apparently it so happened that in our actual project, we're using [`react-select-async-paginate`](https://github.com/vtaits/react-select-async-paginate) which doesn't support any callbacks. However, it has a much easier fix: simply add a prop called `debounceTimeout` and give it a number in milliseconds.

**I wish `react-select` itself has a similar prop so we don't need to implement debouncing ourselves.**

**Comment by jossmac** [comment]
@ADTC Sorry you had difficulty with this, I understand that the docs are less than ideal. Generally, react-select should own as little of the implementation detail as possible. The debounce solution for one situation may not be appropriate for another; in cases like this it's often good to make the API flexible so the consumer can implement whatever they need e.g. just provide a `loadOptions` callback—the composition of that function is up to the author who has the most context about the application's requirements.

**Comment by AnshAggarwal4015** [comment]
@jossmac  To date, a pertinent solution to the issue at hand remains elusive. It is my understanding that the desire to develop a custom component incorporating AsyncSelect with an integrated debounce function presents a recurring problem: the inconsistency in the display of options—sometimes they appear, and at other times, they do not.

Is there an available resolution to this matter?

**Comment by jossmac** [comment]
@AnshAggarwal4015 Not that I'm aware of, sorry.
