### ISSUE TITLE
[v2] Support for gradient background in control

### ISSUE THREAD

**Issue by kpavankotesh** [JedWatson/react-select#2520]
In v2 latest alpha, I am trying to add gradient like this

```javascript
control: base => ({
    ...base,

    background: 'linear-gradient(90deg, ${color1} 0%, ${color2} 100%)'
})
``` 

It works when I use semicolon at the end like this => `linear-gradient(90deg, ${color1} 0%, ${color2} 100%);` but I get this console error
<img width="655" alt="semicolon error" src="https://user-images.githubusercontent.com/1728799/38870474-92d55104-426b-11e8-95fa-4384ccd29c67.png">

When I don't use semicolon, the gradient doesn't appear. 

Is there any fix for this bug?

**Comment by lesha1201** [comment]
You should use `` instead of '' to use "Template literals".

**Comment by lesha1201** [comment]
It's not react-select issue. React-select@v2-alpha uses glam for styling components but glam have an issue with linear-gradient. It converts `background: linear-gradient(...)` to `background: -webkit-linear-gradient(...),-moz-linear-gradient(...),linear-gradient(...)` instead of 
```
    background: -webkit-gradient(linear, left top, left bottom, from(...), to(...));
    background: -webkit-linear-gradient(...);
    background: -o-linear-gradient(...);
    background: -moz-linear-gradient(...);
    background: linear-gradient(...);
```
![](https://i.imgur.com/IrMLcu0.png)

**Comment by kpavankotesh** [comment]
`v2.0.0-beta.2` resolves this issue as **glam** is removed. Thanks
