### ISSUE TITLE
Support for string options in v2

### ISSUE THREAD

**Issue by ConneXNL** [JedWatson/react-select#2558]
According to the API docs you can only pass an object or an array of objects as the options prop.

However, strings instead of an object seem to work _almost_ just fine. The thing preventing it from working is whenever you have a non-multiple select box and you pass in a string value to `<Select/>`.

At this point the value is removed by:
https://github.com/JedWatson/react-select/blob/v2/src/utils.js#L64

Is it possible to allow string values to be used? This way you are not always forced to make objects like: 
```
[{
  label : 'something',
  value: 'something'
}]
```
but you can just use 
`['something']`

**Comment by robbyemmert** [comment]
Any movement on this? It would be super nice to have.

**Comment by EfstathiadisD** [comment]
Would be nice indeed. I am having problems, when `react-select` is used along with formi, and the Formik HOC, need a string to be passed as a value. Would be great if we had this, but I guess until then I need to find a work-around

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're cleaning up and closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version (v3) and beyond.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
