### ISSUE TITLE
[v2] Placeholder isFocused

### ISSUE THREAD

**Issue by mike1808** [JedWatson/react-select#2655]
Hello, I implemented some custom component for placeholder and will love to receive `isFocused` prop to it to control its styles during the input focus. 

Is there any reason not to pass it to the `Placeholder` component?

**Comment by avremel** [comment]
I had the same issue. I am trying to get the `isFocused` props so that when a user hits the enter key, he will get routed to the focused option, *not* the `inputValue`.

It seems to be just a matter of exposing the value as a prop, as the value `isFocused` already exists on each option.

Here is an example from Nordstrom:
![reactselect](https://user-images.githubusercontent.com/10588097/43651376-2f66a556-9710-11e8-9c9b-4d020ff4f26e.gif)

Here is a workaround that someone gave me:
https://stackoverflow.com/a/51664054/4822174

**Comment by mike1808** [comment]
@avremel I forked the lib and added `isFocused` in props

**Comment by Nelrohd** [comment]
I opened a PR #3096 from @mike1808 suggestion.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
