### ISSUE TITLE
Clicking on arrows or empty scrollbar area of a Select component dropdown closes the dropdown

### ISSUE THREAD

**Issue by hyprbus** [JedWatson/react-select#2698]
Environment:
Microsoft Edge 42.17134.1.0 (Chrome and Firefox work fine)
react-select version: 1.2.1

Current behaviour:
When clicking on a react-select Select component that produces a dropdown list of items with a scrollbar to the right, clicking on the scrollbar arrows or an empty area in the scrollbar, the dropdown closes instead of scrolling. You can see this for yourself with MS Edge on any of the official examples: http://jedwatson.github.io/react-select/

Expected behaviour:
The scrollbar should scroll and not close.

With MS Edge, a dropdown scrollbar works as expected for a select component not implemented with react-select in the current project I'm working on, so it doesn't seem to be a generic Edge issue for HTML select element dropdowns.

**Comment by navhaxs** [comment]
This seems to have been fixed - the scrollbar works fine in Edge browser version 44.17763.1.0 on https://react-select.com/home

However this issue is still a problem on IE 11 :(

**Comment by zaksaid** [comment]
Version 2.2.1 on IE11.1 has this problem as well.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!

**Comment by manan0701** [comment]
Hello,

The issue can still be reproduced in IE 11. I was not able to reproduce it in any other browser. Basically, if the options overflow outside of a parent container (overflow is set to auto), a scrollbar is displayed in the parent container (not within the menu list).

Now when you try to click on the scrollbar in IE, the menu gets closed. I think this might be because IE fires mousedown events when clicked on the scrollbars considering them to be a part of a div. However, is there a workaround to make this work using the utils provided by react-select?

I created a codesandbox for this, but later discovered that codesandbox.io does not render on IE :(

Still here is the link to it: https://codesandbox.io/s/objective-blackwell-nrryu?file=/src/App.js

Thank you and kudos to the team for building react-select 👏🏼
