### ISSUE TITLE
closeMenuOnSelect Not working in Windows 

### ISSUE THREAD

**Issue by nilansht** [JedWatson/react-select#2730]
@JedWatson  Version2  @..For windows, whenever a selection of an option is made either through a click or enter , the menu still gets closed , which should not be the case if closeMenuOnSelect is turned false in the code. This works fine in Mac but is faulty in Windows Chrome . So please give a check soon !!

**Comment by Tecktron** [comment]
I am seeing something like this too (`"react-select": "^2.0.0"`), but not on all machines (browserstack for example works fine, which is annoying especially to my coworker having the issue). I tried incognito mode (with all extensions disabled) and got the same results. 

For me, when I open the dropdown and select something, the dropdown just closes and nothing gets updated (I'm using the multi option). What's more curious is that I added a custom onChange function (it `console.log`'s the  passed in `values` and `action`) and that doesn't get called either. However, I find that when I open the debugger and add a breakpoint in that function, it does get called and the entire thing works as expected. That to me makes it seem like there's some kind of race condition happening, which would make sense if I was using this thing in an asynchronous manner, but I'm not. 

It's quite puzzling.

**Comment by Tecktron** [comment]
I realized that Windows is running on a Surface and I get this same issue with Chrome on Android and Apple devices, so I believe this to be touch screen related, at least it seems to be that way for my issue.

**Comment by manubb** [comment]
Apparently this problem occurs on touch devices. We have tested on:

- Chrome and Firefox W10 with touch screen
- Safari on iPad

Easily testable on https://react-select.com/home#animated-components
(animation example)

**Comment by vpark** [comment]
I can confirm this as well for the devices/browers manubb has listed. 

To further clarify, it doesn't require a touch action to replicate the bug. Using the dropdown with a mouse like a regular non-touchscreen closes the dropdown.

Let me know if you guys need anything else to move the bug under confirmed.

**Comment by jw3s** [comment]
Also encountered the same issue on XPS15 touch.

Its really weird because when I add a breakpoint on `setValue` upon selecting an option, problem goes away, but without the breakpoint, problem always happens. Probably a race condition issue or something, not sure. But what I noticed was in redux devtools, it actually selects the newValue, but resets back to previous value onBlur. Good thing that you can turn this feature off by `blurInputOnSelect`, as the name suggests, it should blur on selecting something. Everything still runs the same on our web app and regression tests. Until this issue is fixed, we'll leave `blurInputOnSelect` off for now.

Saw the same issue logged for mobile chrome btw.
https://github.com/JedWatson/react-select/issues/2771
https://github.com/JedWatson/react-select/issues/2692

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
