### ISSUE TITLE
[v2] Flow type definitions for the flow-typed repo

### ISSUE THREAD

**Issue by mandx** [JedWatson/react-select#2858]
Is there any plan to have a Flow typedef for v2 exported to the [`flow-typed`](https://github.com/flow-typed/flow-typed/) repo? Since Flow is used for development, I'm guessing it could be extracted?

I can't import the library directly with Flow, because I have most warnings enabled, and importing `react-select` makes the Flow checker to just give up because of the many warnings...

**Comment by IanVS** [comment]
Here's a gist I made of flow-types that I extracted manually from v2.  I make no guarantee they're perfect, but they're working pretty well for me so far.  https://gist.github.com/IanVS/faec654751135280b6454ebac7c756b2

**Comment by bladey** [comment]
Hi all,

Thank you @TrySound and @IanVS who had a part in addressing this question.

@mandx in an effort to sustain the `react-select` project going forward, we're closing issues that appear to have been resolved via community comments.

However, if you feel this issue is still relevant and you'd like us to review it or have any suggestions - please leave a comment and we'll do our best to get back to you, and we'll re-open it if necessary!
