### ISSUE TITLE
[V2] Dropdown being blocked?

### ISSUE THREAD

**Issue by chobo2** [JedWatson/react-select#2863]
Hi

I am using react-select inside react-table(https://react-table.js.org/#/story/readme). It seems to have for each cell "overflow:hidden" set and thus react-select dropdown portion is not being shown.

I can see what the react-select is generating as it keeps disappearing when I move away from it. Can I fix this via a z-index?

**Comment by Vynlar** [comment]
Check out the `menuPortalTarget` prop. This should help you with your problem. For more context, you can read about portals in general [here](https://reactjs.org/docs/portals.html).

Good luck!

**Comment by kylebebak** [comment]
@chobo2 

Ran into the same problem. Instead of messing around with portals, you might want to just change the styling for the `td`s in the column that has your `select`s.

~~~js
getTdProps = (state, rowInfo, column) => {
  const { id } = column
  return {
    style: id === 'idForMyColumnWithSelects' ? { overflow: 'visible' } : {},
  }
}
~~~

Here's a screenshot so you can see that it works.

<img width="226" alt="screen shot 2018-09-18 at 11 44 20 am" src="https://user-images.githubusercontent.com/1524088/45709201-4b425080-bb38-11e8-8c74-ade3f1b20ba0.png">


This doesn't seem like an issue with react-select, but maybe it's worth keeping it open to for other folks with the same problem.

**Comment by chobo2** [comment]
@kylebebak 

the code you posted what property does it hookup to in react-select?

**Comment by kylebebak** [comment]
It hooks up to the `getTdProps` prop in **react-table**, not in **react-select**.

Again, I don't think this is an issue with react-select.

**Comment by tommyalvarez** [comment]
@kylebebak for me i have to do that for getTableProps and getTbodyProps also, do you know why? It doesn't work otherwise...

**Comment by DonkovtsevArthur** [comment]
> @kylebebak для меня, я должен сделать это для getTableProps и getTbodyProps, знаете ли вы, почему? Это не работает иначе ... Решение порта было «проще» в этом смысле

getTableProps={() => {
				return {
					style: { overflow: 'visible' }
				};
			}}
			getTbodyProps={() => {
				return {
					style: { overflow: 'visible' }
				};
			}}
			getTdProps={(state, rowInfo, column) => {
				const { id } = column;
				return {
					style: id === 'idForMyColumnWithSelects' ? { overflow: 'visible' } : {}
				};
			}}

**Comment by johnculviner** [comment]
Another way to fix this that doesn't require hardcoding column ids outside of the column is to set the style directly in the column you need. This fixed it for me. EX:
```
<ReactTable
  columns=[{
    style: { overflow: 'visible' }
    ....
  }]
/>
```

**Comment by kalengi** [comment]
> style: { overflow: 'visible' }

This worked for me.

**Comment by kalengi** [comment]
> Another way to fix this that doesn't require hardcoding column ids outside of the column is to set the style directly in the column you need. This fixed it for me. EX:
> 
> ```
> <ReactTable
>   columns=[{
>     style: { overflow: 'visible' }
>     ....restOfTheColumnDef
>   }]
> />
> ```

This worked for me.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
