### ISSUE TITLE
[V2] Options aren't rerendered directly when parent state is changed

### ISSUE THREAD

**Issue by dugernierg** [JedWatson/react-select#2865]
I've been facing what appears to be a bug.

I have two components, Parent & Child, with Child containing a Select component. Parent passes down a list of players that can be updated by the user. the options attribute is set as this.props.players so that when a new player is added, it should be also available in the options.

However, the list will only update if the user try to type something in the search field. It will never update if the Select is not searchable. This issue doesn't occur with v1. Find below an example of my problem.

https://codesandbox.io/s/6v0791zj9r

As you can see, the state is properly updated and the props in Child are also correct yet Select doesn't update its options. I'm not going to call this a bug because I don't know if it's supposed to be the intended comportment of V2 or not.

Anyone can help me out there?

**Comment by WandHerring** [comment]
@lemon-31 The issue doesn't exist on V1, so I use this version instead at the moment since I don't need the new functionalities.

**Comment by lemon-31** [comment]
@WandHerring My thoughts exactly. I'll be using v1 in the meantime

**Comment by thomas88** [comment]
We're running into the same issue as well.

**Comment by steeevio** [comment]
I've got the same issue. My options list is generated from several api calls but only the first option will be displayed. Once that option is selected the list will update to show the rest of the options.

**Comment by lemon-31** [comment]
Hi all,

Good news. I figured this out today. It turns out the problem was nothing to do with the "react-select" project but was actually caused by how we are updating our state in React.

React won't see the change made inside the options array unless a new array object is created. There may be a more elegant way to create the new array object but the way I did it was using the "concat" function with an empty array which returns a new array object with the same data.

For the code sandbox in the OP I fixed the issue there by adding the line with the "concat" function as shown below:

```javascript
addNewPlayerHandler(name) {
  var newPlayer = { value: name, label: name };
  var newPlayersList = this.state.players;
  newPlayersList.push(newPlayer);
  newPlayersList = newPlayersList.concat([]);
  this.setState({ players: newPlayersList });
}
```

If you want to see another example checkout the issue below where I posted a solution to my own issue that I had created.

https://github.com/JedWatson/react-select/issues/2894

Cheers,

Alex

**Comment by rohankk2** [comment]
Hey I just reproduced the same issue and the above solution does not work.

**Comment by lemon-31** [comment]
@rohankk2 

Hi, do you have any code to share? Another way you can guarantee the state to update is using the "cloneDeep" function when you set the state. Eg:

```javascript
npm i --save lodash.clonedeep

import cloneDeep = require('lodash/cloneDeep');

this.setState({ players: cloneDeep(newPlayersList) })
```

**Comment by KamWis** [comment]
@WandHerring @lemon-31  So actually it behaves correctly. Here's what's happening:
 - You are supplying options via props (no matter if that source is dynamic or not),
 - You are passing those options as a `options` prop to the `reactSelect`,
 - You are typing a phrase, then you either perform some sort of API call to get options based on this phrase or do some options manipulation somewhere else,
 - Phrase not always match `option.label` hence `reactSelect` is filtering those out leaving you with the impression that options didn't update.

In this case, you can disable `reactSelect` option filtering, since you are handling options yourself. You can do that via returning always true in `filterOption` callback function:
```
...some class

filterOption = (/* receives option and rawInput params but we don't need it now */) => true;

render() {

    return (
        <MembersSelect
            autoFocus={true}
            placeholder="some placeholder"
            onInputChange={this.handleInputChange}
            onChange={this.handleSelectionChange}
            filterOption={this.filterOption}
            options={this.props.options}
        />
);
}
...end of some class
```

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!

**Comment by JoueBien** [comment]
@bladey bladey
Dynamic results are still busted with out setting filterOption. This should be re-opened and either the behaviour is adjusted or the setting of filterOption to `() => true` is document for the case of setting dynamic options while typing in the input field. 

If the docs need updating there should be a line here https://react-select.com/props under options. 
```
If your options are dynamically driven by the search feature then you will need to specify filterOption={() => true} to prevent options from being hidden.
```

It's probably also worth putting a note under the Async section https://react-select.com/async because that is were people would expect it to be (It's where I ended up while looking for a solution).

**Comment by bebepoussin2** [comment]
[JoueBien](https://github.com/JoueBien) you are simply amazing, you definetly made my day, I have been looking around for a month to fix this.
