### ISSUE TITLE
No simple way to make the arrow of the dropdown rotate when the menu opens.

### ISSUE THREAD

**Issue by ericmackrodt** [JedWatson/react-select#2926]
Background
------------

When trying to make the arrow of the dropdown rotate when the menu is open using CSS by changing the `.dropdown-indicator` class in the `-is-focused` state, the arrow stays upside down when the menu closes as the dropdown is in focus.
That was supported by default on v1

Expected
---------
We should have the option to set the state of the indicator based on the menu itself.

Reproduction
--------------
[https://codesandbox.io/s/6x2x587083](https://codesandbox.io/s/6x2x587083)

As you can see, if you select an item or just click on the dropdown again to close the menu, the arrow won't rotate back.

More Details
-------------
Here's the stack overflow issue with more details and my current solution.
[https://stackoverflow.com/questions/51761008/rotate-arrow-indicator-in-react-select-v2](https://stackoverflow.com/questions/51761008/rotate-arrow-indicator-in-react-select-v2)

**Comment by tomislav-s** [comment]
Instead of using `state.isFocused` you can use `state.selectProps.isMenuOpen` for this

**Comment by vicentelyrio** [comment]
With `2.0.0-beta.6` I had to use `state.selectProps.menuIsOpen`

**Comment by Rahulkr204** [comment]
I solved this by using arrowRenderer props
```
                arrowRenderer() {
                  return <div className={classes.arrowRenderer}><DownChevron/></div>
                }
               <Select
                    arrowRenderer={this.arrowRenderer}
                    optionRenderer={this.props.optionRenderer}
                    isMulti={false}
                    closeMenuOnSelect={false}
                    options={options}
                    onChange={(props)=>this.editDropdown(props,name)}
                    value={value}
                    className={classes.selectOption}
                    placeholder={placeholder}
                    disabled={isDisabled}
                    clearable={false}
                    style={dropdownStyle}
                />
```

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
