### ISSUE TITLE
How is one supposed to style an invalid input

### ISSUE THREAD

**Issue by thomas88** [JedWatson/react-select#2930]
How is one supposed to style an invalid input, i.e. when the select does not pass form validation?

**Comment by elisechant** [comment]
@thomas88 you could probably move this question to a form like Stack Overflow. 

You could compose style props with a helper that spreads error styles when the condition is met, like:

```
<Select styles={{ 
  control: base => ({
    ...base,
    ...controlStylesHasError(hasError),
  }),
}}>

const controlStylesHasError = (hasError) => (
    hasError ? { background: 'red' } : {}
)
```

I prefer to wrap all of my form fields (inputs as well) in a <FormGroup hasError={true} /> and default back to CSS.  This is just because I care about uniformity across my form components.

```
<FormGroup hasError={true} /> 
  <Select components={{ Control: ControlWithErrorState }}>
</FormGroup>

export const ControlWithErrorState = props => (
  <div className={styles.selectControl}>
    <components.Control {...props} />
  </div>
);

.formGroupHasError .selectControl {
  background: red;
}
```

**Comment by mabasic** [comment]
For bootstrap.

Add prop to react select:

```
className="react-select"
```

This enables you to grab all react select components on a page.

then in CSS add:

```
.has-error > .react-select > div:first-child {
    border-color: #a94442;
}
```

When using bootstrap validation class `has-error` on `div class="form-group"` this finds the react select and applies border color.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
