### ISSUE TITLE
isFocused cannot controlled by passed in props

### ISSUE THREAD

**Issue by watert** [JedWatson/react-select#2948]
which is in the document.

**Comment by TylerRick** [comment]
I ran into the same problem. I was trying to focus the select and trigger the menu to open, but noticed that `isFocused` was ignored.

A better way (at least in my case), was to just get a ref and call methods directly on the component as mentioned in #2106:

```
      selectRef.current.focus()
      selectRef.current.onMenuOpen()
```

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
