### ISSUE TITLE
[v2] when prop filterOption changes options are only regenerated after user input

### ISSUE THREAD

**Issue by arty-name** [JedWatson/react-select#2950]
I would like to use filterOption prop to hide some options even before the user has started typing anything in the input. That works. However if the filterOption prop changes on the existing instance the list of options does not change. It only changes after first input. 

Here is the minimal example: https://codesandbox.io/s/q79qjr4
Open dropdown: options 1-4 are visible
Click "Toggle" button and open dropdown again: options 1-4 are still visible
Type anything in the input and delete it: only options 2-4 are visible
Click "Toggle" button again and open dropdown: only options 2-4 are visible
Type anything in the input and delete it: now options 1-4 are visible

**Comment by mitchellwarr** [comment]
+1

**Comment by torbjorn-boost** [comment]
It looks like `filterOption` is only really intended for filtering options when searching, but I tried for the longest time to use it to filter options out of a plain, non-searchable select (instead of filtering myself before providing them as the `options` prop). If `filterOption` _isn't_ supposed to be used for that, maybe the documentation should at least be clearer?

**Comment by vHades0199** [comment]
+1

**Comment by ebonow** [comment]
This issue was logged against a v2 beta version of react-select and no longer appears to be an issue:
https://codesandbox.io/s/react-codesandboxer-example-forked-obe8r?file=/example.js
