### ISSUE TITLE
[V2] Impossible to pass customs styles when an option is clicked, isSelected is always false

### ISSUE THREAD

**Issue by jonidelv** [JedWatson/react-select#3002]
There is a bug when trying to apply custom styles for the option component when an option is clicked. This is happening because `isSelected` is always false even when the option is clicked.

```js
option: (styles, { data, isDisabled, isFocused, isSelected }) => {
    const color = chroma(data.color);
    return {
      ...styles,
      backgroundColor: isDisabled
        ? null
        : isSelected ? data.color : isFocused ? color.alpha(0.1).css() : null,
      color: isDisabled
        ? '#ccc'
        : isSelected
          ? chroma.contrast(color, 'white') > 2 ? 'white' : 'black'
          : data.color,
      cursor: isDisabled ? 'not-allowed' : 'default',
    };
  },
```
This bug is even present on the docs examples https://codesandbox.io/s/3yn3lq01oq?module=/example.js (line 15) file `examples.js`

**Comment by gwyneplaine** [comment]
@jonidelv  I'm not quite sure what the issue is here, if you set isMulti to false in the supplied sandbox, you can see that the logic on line 15 is indeed working. 

In fact if you log out the value of 'isSelected' within the custom styles method, you'll see that isSelected is being set to 'true' for the specified option on click, see the sandbox below (your provided sandbox with the above console log and without the isMulti prop).

https://codesandbox.io/s/l4qzvqyr6m

Happy to help you debug your use case if you provide us with a sandbox of your code :)

**Comment by jonidelv** [comment]
Sorry, you're right, what I meant was, the active state of the option. I took a closer look and made it it work like this:

```js
"&:active": {
 backgroundColor: "red"
},
```
