### ISSUE TITLE
ie don`t work

### ISSUE THREAD

**Issue by lixiaozhangme** [JedWatson/react-select#3007]
hello
In Google, Firefox, it works fine, but all versions in ie can't run, and no error is reported.
![image](https://user-images.githubusercontent.com/19645470/45011978-db1bd100-b047-11e8-8b20-85fe507d46e0.png)
![image](https://user-images.githubusercontent.com/19645470/45012085-3ea5fe80-b048-11e8-8333-ce288d8b78d4.png)

**Comment by gwyneplaine** [comment]
hi @lixiaozhangme  please provide us with a [codesandbox](https://codesandbox.io/s/new) of your reported issue so we can address it efficiently.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're cleaning up and closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
