### ISSUE TITLE
Why do we lose other focus states when select?

### ISSUE THREAD

**Issue by yi-jy** [JedWatson/react-select#3071]
Thank you very much for providing this wonderful library.

But I have a question. Why do we lose other focus states when choosing Options?

I adjusted an online [demo](https://codesandbox.io/s/k9q208o1m5), In this case, you'll find that the focus state of the input box is lost when you enter the input box and select the options, which I think has a bit of an impact on the user experience.

I looked at the relevant code([code1](https://github.com/JedWatson/react-select/blob/18219f5271705ef150ad16177db43f0c44f0413d/src/Select.js#L453), [code2](https://github.com/JedWatson/react-select/blob/18219f5271705ef150ad16177db43f0c44f0413d/src/Select.js#L854))  . I'm curious to know if there are any `props` (options) that you can customize so that you don't lose your current state when choosing an option? Thanks!

**Comment by karlingen** [comment]
This is still an issue.

### Steps to replicate

_In Safari on your iPhone_
1.  Goto https://codesandbox.io/s/66r75?module=/example.js
2. Type anything in the multiselect, select/create a value.

**Expected behavior**
Option is created and appended to the multilabel container.
Input is still focused and you can keep on typing.

**Actual result**
Option is created and appended to the multilabel container.
Input is no longer focused. You must tap on the input field before you can type again.

**Comment by karlingen** [comment]
There is an `blurInputOnSelect` attribute which you can set to `false` that will take care of that!

**Comment by KJoslyn** [comment]
`blurInputOnSelect` doesn't seem to do the trick in the demo above and it doesn't work for my case either. Does anyone have any other ideas?

**Comment by ebonow** [comment]
Greetings @yi-jy and others,

There are the following props which may help you.
`blurInputOnSelect` (as @karlingen mentioned)
`closeMenuOnSelect`

When I tested the demo with these props set to false, the Select input stayed active.

@KJoslyn if this is not working for you, would you mind sharing a code example or even better yet a codesandbox?

**Comment by ebonow** [comment]
In an effort to close out stale and inactive issues, I will be closing this. Please feel free to reply if you still have questions and we can reopen this if necessary.
