### ISSUE TITLE
Non array value to options prop - options.reduce is not a function

### ISSUE THREAD

**Issue by katsos** [JedWatson/react-select#3072]
This is a feature request, not a bug report.

Giving to a `<Select />` component anything else than an array to `options` prop,  
it will cause this error `Uncaught TypeError: options.reduce is not a function`. 
 
An auto generated warning from react development enviroment whould be more clear by using `options: PropTypes.array.isRequired` in prop types definition of Select component.  

If you insist to use prop-types in the project, we could give a more human readable error if `options` prop is missing or it isn't an array, using [`componentDidCatch`](https://reactjs.org/docs/error-boundaries.html`).

This feature can be implemented for v1 and v2.

**Comment by dfoster-cb911** [comment]
Nudge on this one 👍

**Comment by fauzankadri** [comment]
This took a little while to debug. For anyone wondering, options strictly accepts an array. If it's anything else, it will break the app. 

What you can do is use this line if your options changes from array to something else (or vice versa)

```options={myOptions && myOptions.constructor === Array ? myOptions : []}```

**Comment by ColinSandlin** [comment]
I'm a bit confused on this. I'm getting the same error, and I'm feeding it an array. Here's what I'm passing into options:
<code>
[Array(25)]
 > 0: Array(25)
         0: {value: "Thankful--5", label: "Thankful"}
         1: {value: "Joyful--5", label: "Joyful"}
         2: {value: "Peaceful--5", label: "Peaceful"}
         3: {value: "Content--5", label: "Content"}
</code>
etc.

Can anyone help me figure out why its having issues with my array? Thanks!

**Comment by skmaingi** [comment]
are there not better ways of displaying errors than "options.reduce is not a function"?
how is a coder supposed to know this unless he tries to find the issue in github or stack overflow and by the way, I have struggled with this using typescript while returning an array and still the same error.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
