### ISSUE TITLE
Footer in custom MenuList

### ISSUE THREAD

**Issue by archansel** [JedWatson/react-select#3076]
I tried to make MenuList with footer. This is my current implementation
```
const MenuList = ({ children, selectProps, ...rest }) => {
  return (
    <div>
      <components.MenuList {...rest}>
        {children}
      </components.MenuList>
      {selectProps.footer && (
        <Footer {...rest}>
          {selectProps.footer}
        </Footer>
      )}
    </div>
  );
};
```
`Footer` is just simple component with styling. `selectProps.footer` is a clickable component (eg. button)

With this implementation, the footer is clickable but the option is not clickable. If I remove `{...rest}` from `<Footer {...rest}>` so it will become
```
const MenuList = ({ children, selectProps, ...rest }) => {
  return (
    <div>
      <components.MenuList {...rest}>
        {children}
      </components.MenuList>
      {selectProps.footer && (
        <Footer>
          {selectProps.footer}
        </Footer>
      )}
    </div>
  );
};
```
The option is clickable but the footer is not

These issues **ONLY HAPPEN** in touch device, it works perfectly in desktop (both option and footer are clickable). Is there any way to solve this for touch device?

**Comment by iseredov** [comment]
Have same problems. For example https://codesandbox.io/s/z2lj6z804p. If you try to click on the link on the touch device, then we will not go anywhere.

**Comment by ahbagheri** [comment]
A quick workaround is to bind "onTouchStart" event to the the "onClick" event.

> Have same problems. For example https://codesandbox.io/s/z2lj6z804p. If you try to click on the link on the touch device, then we will not go anywhere.

**Comment by ebonow** [comment]
Greetings,

One of the reasons this is happening is because of [how the existing mouse and touch events are bound. 
](https://github.com/JedWatson/react-select/blob/998c979b4ed51ee39b87c9b2f0f03da440017dcf/packages/react-select/src/Select.js#L1065)
``` JS 
  onTouchEnd = (event: TouchEvent) => {
    if (this.userIsDragging) return;

    // close the menu if the user taps outside
    // we're checking on event.target here instead of event.currentTarget, because we want to assert information
    // on events on child elements, not the document (which we've attached this handler to).
    if (
      this.controlRef &&
      !this.controlRef.contains(event.target) &&
      this.menuListRef &&
      !this.menuListRef.contains(event.target)
    ) {
      this.blurInput();
    }
   // ...
  };

```

Since the footer is not in the MenuList in both your examples @archansel and @iseredov , the blur event is immediately triggered. 

The reason why the suggestion by @ahbagheri would likely work is that the onTouchStart event would work is that it fires first, but unfortunately would likely trigger when trying to drag and scroll.

Perhaps a better solution for this would be to check that the event.target is contained in the `menuRef` instead of the `menuListRef` though I don't believe such a thing as a menuRef exists at current time.

**Comment by kushniryb** [comment]
Greetings! 

Stumbled upon the same issue. I've a custom `Menu` component that looks like this:
```jsx
const MenuWithFooter = ({ children, selectProps, ...props }) => (
  <Components.Menu {...props}>
    {children}
    <div css={styles.footer}>{selectProps.renderFooter}</div>
  </Components.Menu>
);

```
`renderFooter` returns a button but the click is not being registered on mobile devices at all.
That said, there are no issues on desktop.

Can someone suggest a workaround? 
I've tried upgrading to v4.3.1 but the issue persists.

Thanks in advance!

**Comment by lukebennett88** [comment]
Hi @archansel,

In an effort to sustain the react-select project going forward, we're cleaning up and closing old issues and pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of react-select please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!

**Comment by Uni2K** [comment]
I think it is still relevant. There seems to be no working solution for now.

**Comment by ben-liveauctioneers** [comment]
This issue is still relevant. Same use case and issue as the original poster.

**Comment by iralitv** [comment]
One of the possible solutions is to use `e.stopPropagation()` for touch events (`onTouchStart`, `onTouchEnd`) of `<button/>` or link inside the `footer` component
```
const CustomFooter = () => {
  const onTouch = (e: TouchEvent) => {
    e.stopPropagation()
  }
  
  return (
    <>
       ...
       <button 
         onTouchEnd={onTouch} 
         onTouchStart={onTouch}
         onClick={() => alert('click')}
       >
         Label
       </button>
    </>
  )
}

const Menu = ({ children, ...props }) => (
  <components.Menu {...props}>
    {children}
    {props.selectProps.footer}
  </components.Menu>
)

<Select
  ...
  components={{
     Menu,
     ...components
  }}
  footer={CustomFooter}
/>
```

**Comment by asif-simform** [comment]
Thanks @iralitv 
it's works

**Comment by jonathannguyenjp** [comment]
@iralitv i don't see footer props in Select component. 
Is this the old version or did you configure something else?
