### ISSUE TITLE
Class "is-open" in version 2.0

### ISSUE THREAD

**Issue by anorudes** [JedWatson/react-select#3103]
Hello :) 
When a select is opened, the "is-open" class isn't added, even with classNamePrefix. There are "is-focused", but this is different.
Because of this, it isn't possible to change the arrow (indicator) styles.

**Comment by s20lee** [comment]
There is a prop called "menuIsOpen" in Select component. Pull request has been submitted to use the prop to add "control--menu-is-open" class to the div when menu is expanded.

**Comment by cutterbl** [comment]
It is possible to do this through the styles prop as well.

```
const dropdownIndicatorStyles = (base, state) => {
  const { menuIsOpen } = state.selectProps;
  const backgroundImage = menuIsOpen ? 'caret-up' : 'caret-down'; // demo purposes only
  return {
    ...base,
    backgroundImage
  };
}

<Select styles={{dropdownIndicator: dropdownIndicatorStyles}} />
```

That's not exact, but I think you get the gist.

**Comment by szczepanbarszczowski** [comment]
I can confirm that in `v2.2.0` class `control--menu-is-open` isn't added when menu is opened. This is kinda issue for people which are overriding global styles. Focus works perfectly fine.

**Comment by AkvelonAccount** [comment]
Just add classNamePrefix='select' to your Select component and you will obtain whole needed classes..

**Comment by alexander-gush** [comment]
Just add classNamePrefix='select' to your Select component and you will obtain whole needed classes..

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
