### ISSUE TITLE
Option to Blur input after clear button click/ removing option in multi-select

### ISSUE THREAD

**Issue by dav-sap** [JedWatson/react-select#3104]
Currently when clicking on the clear button, to clear multiple values selected, or removing a selected option in the multi options, the control is automatically focused, this is very annoying, user might want to just clear/remove and keep doing his work, but it's automatically being focused. 

The blurInputOnSelect works great but it's only when you select a new item not when you clear.

I saw all the hacky ways of using Refs and stuff, but using refs can always be a bit risky and can cause unexpected behavior (there's a reason it's deprecated). Any way to create a simple prop like this? I can help with a PR of my own as well

**Comment by xddz9** [comment]
Any news on this? Is that still not possible? I find that it only happens on mobile, but not on desktop. Is that on purpose?

**Comment by arnelamo** [comment]
Still a problem..

**Comment by Methuselah96** [comment]
I've started [a fork](https://github.com/react-select-oss/react-select) of react-select. Feel free to resubmit this issue on the fork and/or submit a PR to resolve this issue on the fork and we can get it merged and released.

**Comment by ebonow** [comment]
Greetings, 

Much of the logic has been moved to the onChange handler instead of having so many props. Using the action meta api, the clear event can be listened for. 

The hacky part of this unfortunately seems to be that blurring the input immediately has no effect, so a brief setTimeout is required. I'm hoping this is something that a major refactor into hooks will allow us to better control the rendering without timeouts, but time being, this will do the trick.

Working demo: [codesandbox](https://codesandbox.io/s/react-select-blur-on-clear-ghpuo)

```js
  const selectRef = useRef();

  const onChange = (option, { action }) => {
    if (action === "clear") || (action === 'remove-value') {
      setTimeout(() => selectRef.current.select.blur(), 1);
    }
  };

  return <Select isClearable ref={selectRef} onChange={onChange} options={options} />
```

**Comment by ebonow** [comment]
I will close this issue for now. If anyone has any questions or concerns, please feel free to reply and we can re-open this if you feel it is still unresolved and relevant.
