### ISSUE TITLE
[v2] Allow passing your own instance of emotion

### ISSUE THREAD

**Issue by standayweb** [JedWatson/react-select#3120]
When using react-select in an iframe widget, the styling gets added to the head of the parent page rather than to head in the iframe.

Emotion has already solved this issue:
https://github.com/emotion-js/emotion/tree/master/packages/create-emotion

We should expose a way to pass in an emotion instance to the react-select component.

**Comment by thejahweh** [comment]
Or make it usable without emotion. The header looks just horrible with all this style definitions. 

This looks like a bad joke:

![image](https://user-images.githubusercontent.com/10514993/48065896-3abf6580-e1cc-11e8-94af-818d63c67197.png)

**Comment by dan-kez** [comment]
I am running into this issue now because [typeform](https://www.typeform.com/) uses emotion and it conflicts with  react-select's instance of emotion our package.

**Comment by llamerr** [comment]
No updates or solution more than a year later?

**Comment by nishit-mobio** [comment]
Hi, Guys seems this issue is still not resolved. I am facing the same issue

**Comment by pertsenga** [comment]
Any update for this issue?, happens to me as well in Netlify CMS preview

**Comment by mikeyyyzhao** [comment]
same here, we're using react-select in an iframe and the styling is all goofy

**Comment by doougui** [comment]
Any updated to this?

**Comment by sajera** [comment]
In iframe - styles hosted on parent page and absent in frames. 😢

**Comment by paulzacz** [comment]
I have similar issues when trying to use react-select in the shadow DOM. I want to be able to be able to use a custom emotion [CacheProvider](https://emotion.sh/docs/cache-provider), but I can't because emotion is a `dependency` rather than a `peerDependency`. Even if I use the same version in a yarn (v3) monorepo, I get:

> You are loading @emotion/react when it is already loaded. Running multiple instances may cause problems. This can happen if multiple versions are used, or if multiple builds of the same version are used.

[NonceProvider](https://github.com/JedWatson/react-select/blob/master/packages/react-select/src/NonceProvider.tsx) comes close to what I need, but it doesn't have enough props to fully customize `emotionCache`.

Either `react-select` should treat @emotion similar to how `react` and `react-dom` are treated, or a component needs to be exposed to fully customize `emotionCache`.

**Comment by lukebennett88** [comment]
Hi @standayweb,

In an effort to sustain the react-select project going forward, we're cleaning up and closing old issues and pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of react-select please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!

**Comment by paulzacz** [comment]
There is still no component that lets me pass a custom emotion cache, and @emotion/react is still not a peer dependency, so this issue is still relevant.
