### ISSUE TITLE
Delete Not Working on multiTrue of Pre Populated Data.

### ISSUE THREAD

**Issue by mehuljariwala** [JedWatson/react-select#3139]
Hello ,
When i populated data from backend without selecting any value.
that time when i click on delete icon all data lost one time i need to delete particular data.
how to customize delete chip functionality.

Thank you
Mehul Jariwala

**Comment by kahurangitama** [comment]
Looks like the same bug for me.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
