### ISSUE TITLE
Cannot add new value to CreatableSelect onClick via button

### ISSUE THREAD

**Issue by andreathniah** [JedWatson/react-select#3168]
I am in the midst of trying to reproduce something akin to SackOverflow's suggested tags where suggested tags are added to the input panel on click. However, it seems that `CreatableSelect` does not reinitialize updated values in the value props. Is this a bug or am I doing something wrong?

Here's my [codesandbox ](https://codesandbox.io/s/llv4qk71pm) for easier reference.

**Comment by cutterbl** [comment]
I see exactly what you see. Stepping through the code I see the updates being applied to `options` and `value`. The `Creatable`'s `componentWillReceiveProps` method fires, and updates it's internal state. I can dump out the new props at the beginning of `Creatable`'s `render` method, and see your changes. I think the issue comes when `componentWillRecieveProps` fires inside the `Select`. When I step through, I get here:

```
// rebuild the menu options
if (nextProps.value !== value || nextProps.options !== options || nextProps.inputValue !== inputValue) {
```
What I see is it never steps into this conditional, as it sees `nextProps.value` equaling `value` and `nextProps.options` equaling `options`. I know that `componentWillReceiveProps` is a deprecated method, and wonder if that isn't part of the issue.

**Comment by andreathniah** [comment]
@cutterbl thank you for providing me with the clues. My sharp eye colleague managed to find out what was wrong. The mistake was with how I attempted to add a new value to the stack.

Instead of doing the following:
```javascript
 addToStack = name => {
    const { stack } = this.state;
    const length = Object.keys(stack).length;
    stack[length] = { value: name, label: name };
    this.setState({ stack: stack }, () => {
      console.log("addToStack", stack);
    });
  };
```

It should have been done like this:
```javascript
  addToStack = name => {
    const { stack } = this.state;
    const newstack = stack.concat({ value: name, label: name });
    this.setState({ stack: newstack }, () => {
      console.log("addToStack", stack);
    });
  };
```
The code works perfectly as intended now.
