### ISSUE TITLE
onBlur event.target's value is undefined

### ISSUE THREAD

**Issue by Yahkob** [JedWatson/react-select#3175]
if you have an onBlur on your `<Select/>` `event.target.value` is undefined. Inspecting the element the value is not set

Not sure if I'm doing something wrong but seems like it would be the most intuitive to have the value set on the input passed to onBlur. I see the hidden input storing the value but I don't think it would make sense to have to track down that value

**Comment by chimilord** [comment]
+1

**Comment by artgoce** [comment]
+1

**Comment by jsc144** [comment]
+1

**Comment by julesair** [comment]
+1

**Comment by lommez** [comment]
+1

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
