### ISSUE TITLE
Unable to use circumflex accent on Firefox

### ISSUE THREAD

**Issue by Donorhan** [JedWatson/react-select#3183]
Hello,

When I try to use circumflex accent on Chrome everything works fine. On Firefox (version 62.0.2) I can't use it, I can see the "^" character but I'm unable to use then with other characters like  "ê î ô û"

You can replicate the bug from [this page](https://react-select.com/home)

![error](https://user-images.githubusercontent.com/3781087/48122786-a7903980-e278-11e8-8492-83b73bff1781.gif)

**Comment by ViniciusGularte** [comment]
any solution? Same problem here

**Comment by Renatoirp** [comment]
We still have this Issue in Firefox in Mac OS. In other browsers works fine. Firefox in windows has no problem.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
