### ISSUE TITLE
AsyncCreatable onBlur behaves differently when touch events are enabled

### ISSUE THREAD

**Issue by jimbolla** [JedWatson/react-select#3198]
We ran into an issue with AsyncCreatable when touch events are enabled, such as on iPads and laptops with touchscreens. This can be reproduced on a non-touchscreen device simply by manually enabling Touch Events API in Chrome's flags: chrome://flags/#touch-events

Basically:
1. Type some characters into the input box.
2. Wait for results of `loadOptions` to show.
3. Select one with the mouse.
4. Click into another input to trigger blur.

```js
    onBlur = evt => {
      console.log(evt.target.value); 
      // without touch events, this will be an empty string
      // with touch events, this will still contain the search text
    }
```

We're using this value during blur to detect whether the user entered something in the input but didn't explicitly select an item or choose to create a new item. We want to always create a new item in that case. So we're doing this:

```js
    onBlur={evt => {
      const inputValue = evt.target.value;
      if (inputValue && inputValue !== fieldProps.input.value.label) {
        fieldProps.input.onChange({ value: "", label: inputValue });
      }
      return fieldProps.input.onBlur(evt);
    }}
```

But because inputValue still has a value, it's unintentionally changing the value from what they chose from the list of options, because we expected the value to be blank.

**Comment by nickverstocken** [comment]
Not only an issue with AsyncCreatable... I ran into this today. 
When on touch devices the select menu closes (multi select) on selecting one of the options and non touch devices the select stays open.

**Comment by eddOrnelas** [comment]
Any fix for this?

**Comment by DaveNguyenHuy** [comment]
I got same issue :(

**Comment by Rall3n** [comment]
Could anyone provide an example with [CodeSandbox](https://codesandbox.io/s/k5rvn9z3lv)? I could not replicate the issue.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
