### ISSUE TITLE
Empty input[type=hidden] breaks compatibility with FormData when isMulti=true

### ISSUE THREAD

**Issue by anddoutoi** [JedWatson/react-select#3221]
The rendered `<input type="hidden"/>` found [here](https://github.com/JedWatson/react-select/blob/8536000403c81c89c4b28e2c73bfeaaf71723317/src/Select.js#L1729) causes issues when you are using react-select with [FormData](https://developer.mozilla.org/en-US/docs/Web/API/FormData) web API.

v2.1.1, reproducible in all browsers.

Use the minimal code below and do *not* select any option. Just submit the form.

Minimal code:
```jsx
function ExampleComponent() {
  const options = [
    {label: 'Foo', value: 'foo'},
    {label: 'Bar', value: 'bar'},
    {label: 'Baz', value: 'baz'},
  ];

  function onSubmit(event) {
    event.preventDefault();

    const formData = new FormData(event.target);
    const selectedGizmos = formData.getAll('gizmos');

    console.assert(selectedGizmos.length === 0, 'Expected selectedGizmos.length to be 0');
  }

  return (
    <form onSubmit={onSubmit}>
      <ReactSelect
        name="gizmos"
        options={options}
        isMulti />
      <button type="submit">Submit</button>
    </form>
  );
}
```

**Comment by nynka** [comment]
This was causing me an issue as well when upgrading from v2.0.0, because now the form sends an array with exactly one value which is an empty string instead of nothing. My workaround for now is to sanitize the data in the back-end if this kind of array is received.

If nothing is selected in a multi-valued select then nothing should be sent to the server seems to me like the more reasonable approach?

I believe it was introduced with d0d9117 (PR #2903)

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
