### ISSUE TITLE
Rearrange Multi Selected Options Feature

### ISSUE THREAD

**Issue by tletz24** [JedWatson/react-select#3223]
### Summary:
I believe it would be nice to include a feature to the multi-select in which you can have to ability to arrange the selected options to within the select. This should, in turn, run one of the onChange functions with an _updated_ ordered object of selected values.

### Use case.
This would be a neat feature if one is attempting to use the values in a specific order.

**Comment by ebonow** [comment]
I was interested in something similar and without MultiValueRemove. Here is how I am overriding the MultiValue component:

```javascript
const MultiValue = (props) => {
  const { getValue } = props;
  const values = (getValue() || [{}]); 
  const label = values.map(({ value }) => value).sort().join(', ');

  return (
    <components.SingleValue {...props} children={label} />
  );
}
```

**Comment by whayes75** [comment]
+ Interested in this feature as well.  Often times the ordering of children records is important and it becomes very easy to drag and drop the selected options

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

Please see pull request https://github.com/JedWatson/react-select/pull/3645 for a possible solution.

However, if you feel this issue is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
