### ISSUE TITLE
Multi select remove on intro key not working

### ISSUE THREAD

**Issue by victorvalle** [JedWatson/react-select#3227]
Hi I found an interaction error while interacting with the tag using the keyboard

Go to Multi select case.
Focus with the keyboard in one of the tags/labels
The tag "X" button gets the focus.
Press enter key.
Outcome: the tag remains
Expected outcome: the tag gets removed

**Comment by gwyneplaine** [comment]
thanks for this @victorvalle, this interaction is actually intentional, as we do not want to conflate the notion of deleting a multi-select value with the 'Enter' key. While at the moment removing a focused values is the only interaction we support, there is roadmap to support primary actions on focused values in the future.
