### ISSUE TITLE
Select component display hierarchical tree data view via child options?

### ISSUE THREAD

**Issue by voyagertravel** [JedWatson/react-select#3231]
Fantastic Component and enjoy using it - just wondering if the select component can display hierarchical tree data view via child options like the package below
[https://github.com/dowjones/react-dropdown-tree-select](url)
[https://dowjones.github.io/react-dropdown-tree-select/#/story/readme](url)
Many Thanks

**Comment by singleseeker** [comment]
Any update?

**Comment by vimiPonyai** [comment]
Any update?

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
