### ISSUE TITLE
Dropdown doesn't open when wrapping a parent element style as overflow:hidden

### ISSUE THREAD

**Issue by syedabuthahirm** [JedWatson/react-select#3257]
### Thanks for using react-select!

# Are you reporting a bug or runtime error?
Bug

To report bugs against react-select v2 please fork the following code-sandbox:
https://codesandbox.io/s/6488z4kxjr

*   What's your use case? When i use with Modals i can see bottom options

**Comment by Rall3n** [comment]
The prop `menuPortalTarget` should help. It accepts an HTML-element and renders the menu into that element. 

```jsx
<Select
  { ... }
  menuPortalTarget={document.querySelector("body")} // For example
/>
```
[CodeSandbox](https://codesandbox.io/s/m5o25j4k08)

**Comment by datner** [comment]
@syedabuthahirm 
the `overflow: hidden` property makes it so the visual content is clipped, or otherwise _hidden_ when it is bigger or outside the scope of the div, in this case, the wrapper is the size of the input, and the dropdown is beyond that scope, thusly hidden!

@Rall3n is absolutely correct, a portal is what you're looking for, as only binding the menu to another dom element, preferably higher on the dom tree, will allow it to render correctly without obscuring

**Comment by gwyneplaine** [comment]
Thanks @Rall3n for the sandbox reproduction and speedy response, issue closed

**Comment by SPFlores** [comment]
Coming to this 6 years later and wanted to say thank you for this. Saved me from tearing my own hair out when nothing else was working.
