### ISSUE TITLE
Select component launching Invariant Violation error on Text strings not rendered inside <Text>

### ISSUE THREAD

**Issue by AngeloDias** [JedWatson/react-select#3258]
Hi, my code is launching the error coming below. As you can see, the code is similar to the that presented in repository description. The view I'm working on should be placed inside a tabNavigator that is inside a stackNavigator. Since the error is showed on Select tag, I think the problem could be on react-select project. If I'm doing something wrong, let me know.

```
import React, { Component } from "react";
import Select from "react-select";

const _options = [
  { value: "resource1", label: "PDFs" },
  { value: "resource2", label: "HTMLs" },
];

export default class OffersFilter extends Component {
  static navigationOptions = {
    headerTitle: "Filtro",
    headerTintColor: "#fff",
    headerStyle: {
      backgroundColor: "#21bac4",
    },
  };

  state = {
    selectedOption: null,
  };

  _handleChange = selectedOption => {
    this.setState({ selectedOption });
  };

  render() {
    const { selectedOption } = this.state;

    return (
      <Select
        value={selectedOption}
        onChange={this._handleChange}
        options={_options}
      />
    );
  }
}
```

The log error images:

![screenshot1](https://user-images.githubusercontent.com/3493290/49610132-6de84680-f97c-11e8-94b4-3ef184431d36.png)

![screenshot2](https://user-images.githubusercontent.com/3493290/49610144-75a7eb00-f97c-11e8-9f5a-f99f7f7a7fba.png)

![screenshot3](https://user-images.githubusercontent.com/3493290/49610153-793b7200-f97c-11e8-82a2-ae1ad689084f.png)

**Comment by jitinmaher** [comment]
Are you using this inside a react native project? I guess this module is only for reactjs apps.

**Comment by AngeloDias** [comment]
@jitinmaher, yes.

**Comment by datner** [comment]
@AngeloDias 
hey, react-native does not work like regular react does. it doesn't have any html tags (since there is no DOM for it to be rendered to), instead it uses native elements and translates them native code behind the scenes.
react-select is for reactjs, and for the web. the Text component is how react-native parses raw text which otherwise will throw an error! Most web libs are not compatible with mobile development. The logic is this: does it do a thing? It's probably fine. Does it show a thing? It probably wont work.

search for packages with a `react-native-*` name scheme

**Comment by AngeloDias** [comment]
Oooh. @datner. Thank you. My mistake! Closing the issue!
