### ISSUE TITLE
using menuPortal & controlElement should dynamically calculate position of the menu based on scroll

### ISSUE THREAD

**Issue by Rohanhacker** [JedWatson/react-select#3349]
*   What's your use case? (Tell us about your application and what problem you're trying to solve.)
If the react select is inside a scrollable container and we are passing menuPortal as body and a controlElement. The menu does not move with the scroll. 
*   What interface do you have in mind? (What new properties or methods do you think might be helpful?)
It should dynamically calculate the position of the menu when we scroll based on the scroll. We can pass the scroll container as prop eg. scrollContainer={this.refToContainer}
*   Can you point to similar functionality with any existing libraries or components? (Working demos can be helpful.)
NA

**Comment by benkindt** [comment]
+1
See also issue #3313

**Comment by benkindt** [comment]
A workaround for this is to block scrolling with `menuShouldBlockScroll={true}`

**Comment by bladey** [comment]
Hello -

Thanks for reporting this issue.

This bug has been reported multiple times as per issue #4088.

A new master issue #4088 has since been created to keep track this this bug.

This new issue will exist as the source of truth going forward to investigate the issue, report findings, and implement a bug fix.

We'll take into account all the details above while investigating.

If you feel this issue has been wrongly closed as it isn't related to the new master issue #4088, please let us know and we'll take another look.

Thank you!
