### ISSUE TITLE
[Creatable] Custom keyboard keys to create option

### ISSUE THREAD

**Issue by martinvergara26** [JedWatson/react-select#3361]
Please provide an API so that we can pass custom keyboard keys to create an option.

I've seen there used to be something like:
```
<Creatable
    :
    shouldKeyDownEventCreateNewOption={(keyCode) => keyCode === 13}
    :
 />
```

But that's not working anymore for me, with v2.2.0

**Comment by martinvergara26** [comment]
Up

**Comment by lxender** [comment]
That prop has been removed but I cannot find a suitable workaround either.

**Comment by ashanren** [comment]
Has anyone found a suitable workaround for this? I def need this.

**Comment by karlingen** [comment]
Try this: https://codesandbox.io/s/n81o5?module=/example.js

That's taken from the examples on https://react-select.com/creatable under the example called **Multi-select text input**

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
