### ISSUE TITLE
[accessbility] up/down keys does not work when using controlled `menuIsOpen`

### ISSUE THREAD

**Issue by sunglux** [JedWatson/react-select#3381]
## Description

When the menu visibility is controlled by `menuIsOpen` prop, up/down arrow keys do not move the focused option once the menu is expanded.

## Reproduction

The issue is reproducible in the official example. https://react-select.netlify.com/advanced#controlled-props.

## Environment

version: 2.3.0

**Comment by gwyneplaine** [comment]
thanks for this @sunglux, this is not a bug with Selects internal logic. 
By intention, specifying menuIsOpen does not automatically focus the the control.

The reason why up and down arrows don't seem to work, is because the select isn't focused on setting menuIsOpen in our example. I've added a PR to fix this in our example in #3382

**Comment by mikeyyyzhao** [comment]
Is there a way to move the focused option using arrow keys? Once the component is focused, the dropdown automatically drops down for me which is great but the focused option can not be controlled via arrow keys
