### ISSUE TITLE
What is the point of getOptionValue prop ?

### ISSUE THREAD

**Issue by hugomallet** [JedWatson/react-select#3388]
Hi,

The documented getOptionValue prop does not seem to have any effect.
Related to #2920 

Using these options : 
```js
const options = [{ id: 'one', label 'One' }, { id: 'two', label: 'Two' }]

<Select
    options={options}
    getOptionValue={option => option.id}
/>
``` 

`getOptionValue` does not seem to do anything :   
- In the onChange event handler, the value is still the option object
- passing a string id (example: 'one') as value does not select the correct option
- worth, passing an object like `{ id: 'one' }` as value does not select the correct option

**Comment by DanZeuss** [comment]
I agree with you @hugomallet ... even setting that function, looks like that it doesn't work.

**Comment by Rall3n** [comment]
`getOptionValue` is used to find the option and forward it to the appropriate functions (`onChange`, etc.) if an option was clicked in the menu. Also it is used for comparison to highlight the currently selected option in the menu.

The `value` prop in itself can be an option that does not have to be in the menu list. It can be something entirely else as long as it returns at least a label. So using `{ id: 'one' }` as the value does not show anything as well as a simple string. Both fail silently because for both it returns `undefined` when referencing a `label` attribute.
(Example: [CodeSandbox](https://codesandbox.io/s/nlp80q6wl))

**Comment by hugomallet** [comment]
Thank you @Rall3n, it now makes sense !
This should be documented because it's really confusing

**Comment by richard-ejem** [comment]
> `getOptionValue` is used to find the option and forward it to the appropriate functions (`onChange`, etc.) 

This is not true for at least `react-select` v3, `onChange` receives the whole option object as it arrived on `options` prop. The only use of `getOptionValue` I found is that it converts the value to be used for `<input type="hidden">` field internally maintained by `react-select`. Actual use of this field is also a mystery for me, I just needed to define `getOptionValue` to convert `null` to some string, otherwise I was getting React errors when using `{ ..., value: null }` as an option value object.

**Comment by Rall3n** [comment]
Hello @richard-ejem,

> This is not true for at least react-select v3 [...]

you are right, this sentence is wrong. Seems like I wrote it in a hurry.
`getOptionValue` is used to extract a string representation of the value of an option.

>  [...] The only use of `getOptionValue` I found is that it converts the value to be used for `<input type="hidden">` field internally maintained by `react-select`. [...]

It is used in more places than the rendering of `<input>` fields for HTML form submission, including (as of v4.3.0):
* Marking options in the list as selected.
* Checking if a value already exists when using the `Creatable` component.
* Indexing the options for keyboard navigation.
* Handling removal of selected options in the value.

**Comment by richard-ejem** [comment]
@Rall3n thanks for explanation. In this case, shouldn't you consider adding some warning when user provides any option without `{value: string}` ? As I said, the only error I got was from React complaining about null in `input[value]` and it needed some research to find out that I should use `getOptionValue`. And from what you say, it seems that `react-select` would become glitchy also in a bunch of other ways when someone doesn't use `{value: string}`, although it seems to be supported at first sight.

**Comment by ackvf** [comment]
So what exactly needs to be returned from `getOptionValue` to have the option correctly selected?

**Comment by clemwo** [comment]
Maybe some other beginners that got confused by the prior answer will find my example helpful.
Here was my problem, I have data such as:
```
  const exampleData = [
    { id: 0, name: "one" },
    { id: 1, name: "two" },
  ];
``` 
Now I want react-select to show the "name" value in the dropdown. Instead of using `getOptionValue` I had to use `getOptionLabel` to show "one" and "two" in the dropdown.

```
      <Select
        options={exampleData}
        getOptionLabel={(option) => option.name}
      />
```

What the getOptionValue does is not clear to me. I will edit this comment if I find it out. Otherwise I'd be happy to hear what it is used for

**Comment by Eyesore123** [comment]
I always thought that getOptionValue prop works as an identifier for the value that you want to extract from that option. It depends on the context what you would want from the option object, but often it's some kind of value or an id. You can specify how you want to use it in the callback function. In most cases react-select works just fine without getOptionValue but there are some cases where you absolutely need it.
