### ISSUE TITLE
Switch from Flow to TypeScript?

### ISSUE THREAD

**Issue by akx** [JedWatson/react-select#3389]
Since high-profile projects like Jest seem to be switching from Flow to TypeScript, would it maybe be an option for react-select too?

Since [Babel has tooling for TypeScript](https://babeljs.io/docs/en/babel-preset-typescript), it wouldn't require too many tooling changes, and we'd also get up-to-date TS types "for free".

If this is something the project leadership is amenable to, I'd be glad at having a shot at the porting – but if there's no chance such a change would make it through, I'd rather not bother. :)

**Comment by Methuselah96** [comment]
@JedWatson @gwyneplaine I would also be willing to port react-select to TypeScript. I updated the TypeScript definitions in the DefinitelyType repo for v3 and I think that react-select would benefit by switching from Flow to TypeScript. Is this an option you guys are willing to consider?

**Comment by bladey** [comment]
Hey @akx and @Methuselah96,

We are in fact considering switching to TypeScript for the next release of `react-select`, as outlined here - https://github.com/JedWatson/react-select/issues/3910#issuecomment-635499277

I encourage you to leave a comment in the pinned issue to express your interest in helping porting to TypeScript, for now I'll close this issue.

However, if you feel this issue is still relevant and the linked issue isn't specific enough - please leave a comment and we'll do our best to get back to you, and we'll re-open it if necessary.

Thank you!
