### ISSUE TITLE
on version 2.3.0 create-emotion version shows an error on run time. 

### ISSUE THREAD

**Issue by guiyep** [JedWatson/react-select#3408]
I notice that from version `2.2.0` to `2.3.0` the `create-emotion` package version was downgraded. When installing it from scratch it fails in runtime throwing a `file not found`.

Downgrading the version the error not happen anymore.

**Comment by gwyneplaine** [comment]
hi @guiyep, we removed create-emotion in 2.3.x to resolve a server-side rendering issue. 
2.2.x introduced create-emotion to leverage it to support CSP nonces. However this solution made server-side-rendering impossible. 

If you need CSP support please pin to 2.2.x until the 3.0.0 release (emotion 10 resolves this issue). 
Otherwise upgrade to 2.3.x and remove create-emotion from your dependency tree.
