### ISSUE TITLE
Keyboard navigation to the "allowCreate" user input item unavailable

### ISSUE THREAD

**Issue by adinardi** [JedWatson/react-select#343]
It looks like the changes in PR #326 had this side-effect.

Now that the "allowCreate" user input item isn't in `this.state.filteredOptions` it doesn't get hit in `focusAdjacentOption()` during keyboard nav.

The options I can think of here are either having `focusAdjacentOption()` take `allowCreate` in to account as a possibility outside of the `filteredOptions` array -- or --  when `filteredOptions` is built add it in at that point instead of during `buildMenu`.

There might be others. I'm willing to hack on this if there's a good path forward.

**Comment by bruderstein** [comment]
Sorry I didn't see this sooner. I like your idea of adding it into filteredOptions instead of in buildMenu. I'm not sure if that would have side effects, maybe issues with async around caching the "Add" option, then needing to drop the cache after it has been added (and the "Add" option removed), not sure though.  

It'd be good to put some tests around that, and especially a test for the bug itself.

**Comment by bruderstein** [comment]
Hi @adinardi,

I just wanted to ask if you were working on this?  It looks like I'm definitely going to hit this in work next week, so my hand will be forced for some sort of fix, but I'm happy to leave that as a quick hack to make it work until your PR lands.

Many thanks!

**Comment by adinardi** [comment]
I haven't had time to work on it, @bruderstein -- though it's still preventing me from upgrading.

I'll let you know if I get a chance, but odds are you'll get there first. :)

**Comment by bvaughn** [comment]
By the way, I believe PR #1187 should resolve this issue. Please feel free top give the branch a spin and let me know if you have any concerns or other feedback. 😄

**Comment by bvaughn** [comment]
This issue no longer exists in the 1.x code (as of PR #1187) and so I'm going to close it!
