### ISSUE TITLE
Is this repo maintained?

### ISSUE THREAD

**Issue by edravis** [JedWatson/react-select#344]
This question is not tech at all but:
I can see 95 issues and no solutions :\

**Comment by vincenzo-antolini-os** [comment]
Yes, it is.
Last push: https://github.com/JedWatson/react-select/commit/7188b4dc45225872387e05ea39f17c6ea4d16c2f

**Comment by JedWatson** [comment]
Hey @edravis, it certainly is. There are a heap of issues and PRs to work through because it's a complex widget that a _lot_ of people are using in different environments and with different use-cases.

There's been a big push by @bruderstein to get everything under test, which will make issues / PRs much easier to work through with confidence.

This package has been downloaded nearly 25,000 times in the last month, which is a responsibility I take quite seriously. I also maintain several other packages and three major open source projects, mostly in my personal time. Feel free to check out the commit history on my github profile.

And I haven't made a big deal of it but I've been quite sick in the last two weeks which hasn't helped. I appreciate all the issue reports and PRs that have been submitted by the community and am doing my best to get back on top of things.

Point of fact, a new version was released just a few hours before you opened this issue with 5 fixes in it, merged in the last 48 hours. Thanks to everyone who's getting in and helping.

**Comment by edravis** [comment]
@JedWatson really thankful for your complete answer. I understand both the difficult to maintain such a trending project and also de excitement surrounding this success.

I'm one of these guys using this amazing component and we find that it has the potential to overcome the current troubles while developing dropdowns. Because of that, if you need any kind of help maintaining, developing or managing this repo just ask for it. 

I'll be so proud to help if you need so.
Congratulations and good job.

**Comment by JedWatson** [comment]
Thanks @edravis, much appreciated.

Help is always welcome - the easy ways to contribute are:

- Develop a fix for an issue and open a PR.
- Review existing open PRs and comment on them - do they solve the issue? could it cause problems with an alternative use-case? is the change a good long term API solution? (often if I don't merge a PR immediately it's because I'm not confident about it and need more to review / consider it)
- Test open PRs and add a comment indicating whether they work for you or not
- Submit test cases to help us maintain the project more confidently

:grinning:
