### ISSUE TITLE
Drop-down closes although closeOnSelect is set to false (ver 1.3.0)

### ISSUE THREAD

**Issue by NiceGuyNimni** [JedWatson/react-select#3443]
Since version 1.3.0 the drop down closes on each option click even if settings the closeOnSelect to false.

https://codesandbox.io/s/krk84ylo5

Worked fine in version 1.2.1

**Comment by yipivan** [comment]
I experience this issue as well...took me 2 hours to figure out, down downgraded to older version

**Comment by jagadeeshym-dev** [comment]
@NiceGuyNimni 
I am using 1.2.1 version of react-select
Even then it is not working

**Comment by jagadeeshym-dev** [comment]
@yipivan 
Can you tell me, which version this is working fine

**Comment by NiceGuyNimni** [comment]
@jagadeeshym-dev I'm sorry I can't assist further since I'm at a new company and not working with react-select.
You can view my quick fix and implement the same on your version.

**Comment by NiceGuyNimni** [comment]
@jagadeeshym-dev I had a quick look at my sandbox (linked at the top) and changed the version to 1.2.1 and it worked (try to do the same just to be sure).
You might wanna check you node_modules to see that it downgraded as expected.

**Comment by yipivan** [comment]
@jagadeeshym-dev I was using 1.2.1 as well

**Comment by jagadeeshym-dev** [comment]
Awesome it works

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're cleaning up and closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

However, if you feel this issue is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!

**Comment by bottomparm** [comment]
> Since version 1.3.0 the drop down closes on each option click even if settings the closeOnSelect to false.
> 
> https://codesandbox.io/s/krk84ylo5
> 
> Worked fine in version 1.2.1

Thank you!!! This saved me.
