### ISSUE TITLE
[V2] There's no way to change the seudo class with style object?

### ISSUE THREAD

**Issue by zoeyzou** [JedWatson/react-select#3489]
When we try to add custom style with style object as below: 

```
const customStyles = {
  menu: (provided, state) => ({
    width: auto
  })
}
```

This makes sense when you want to change css properties, but we cannot change seudo class this way, for example changing the scrollbar or hover effect.

Is this a bug or a feature? I'm not sure, but it would be really great if someone can help find out.

**Comment by Rall3n** [comment]
react-select uses [emotion](https://github.com/emotion-js/emotion) (version 9) for managing and rendering the styles. Check their documentation for the correct syntax for using pseudo classes.

**Comment by zoeyzou** [comment]
> react-select uses [emotion](https://github.com/emotion-js/emotion) (version 9) for managing and rendering the styles. Check their documentation for the correct syntax for using pseudo classes.

the prop styles is not Emotion specific, it's just an object of cssProperties which includes the properties but no selectors.

**Comment by Rall3n** [comment]
> the prop styles is not Emotion specific, it's just an object of cssProperties which includes the properties but no selectors.

But it is here in this library. The prop `styles` gets an object with functions for each component. These functions return style objects which will be given to the [`css` function from emotion](https://5bb1495273f2cf57a2cf39cc--emotion.netlify.com/docs/css).
For example [here in the source code](https://github.com/JedWatson/react-select/blob/master/src/components/containers.js#L117) of `ValueContainer`.

And here is an [example from the source code with a `:hover` pseudo-class](https://github.com/JedWatson/react-select/blob/master/src/components/Control.js#L50-L52).

**Comment by spedy** [comment]
Example:

```
multiValueRemove: (provided) => ({
    ...provided,
    "&:hover": {
        backgroundColor: "transparent",
        color: "white"
    }
}),
```

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
