### ISSUE TITLE
Certain view properties are not calculated inside render method

### ISSUE THREAD

**Issue by saysmaster** [JedWatson/react-select#3510]
Certain properties that affect the view (like `isDisabled`) are not calculated during the execution of the render method. Instead, they are calculated once at `constructor`, and additionally on subsequent `componentWillReceiveProps` calls.

I suppose this happens for performance reasons.

But this has the consequence that react-select cannot be used (out of the box) with libraries like `mobx` that observe changes only inside the `render` method of an `observer` component.

In my case, the `options` prop is an array of observable objects. I have set `isOptionDisabled` to return true or false depending on some properties of each observable option combined with some external observable data. While the drodpown is open and the user scrolls to find the option to pick, a change on one of the observable options should trigger a rerender of that option (or all options) and that options should switch to disabled state in the dom. But this didn't happen. The options kept their original disabled state even after their properties upon which that state depends, changed. I thought that the reason maybe was that the react-select components are not observers so they could not track the changes.

Before inspecting the source code, I expected `isOptionDisabled` to be called at some point during the execution of the `render` method of a component. I assumed that the MenuList component was responsible of iterating through the options array and calculating those view properties. So I thought that maybe overriding MenuList would solve my issue. So I did something like `const ObserverMenuList = observer(components.MenuList)` and I overriden the `MenuList` with the `ObserverMenuList` in my Select element. My thought was that since now MenuList was an observer, and since during its render method, the `isOptionDisabled` would be called, then all properties of my observable options that partake in the calculation of isDisabled would be tracked, and the view will immediately update after they change value. But this didn't happen, and the view of the menu itmes retained its initial disabled state.

So I inspected the code, and I realized that those values were calculated in the Select component and not during the execution of the render method. Which makes the Select component unusuable (out of the box with just a `const OSelect = observer(Select)`) with mobx.

The workaround was to create a wrapper component around my Select, and declare a mobx computed property that returned a new array based on my initial array, with all the properties i needed for my options. Then, that computed array was passed to the Select component. Whenever any change happened inside the observable options, the computed array was recalculated and passed anew to Select, triggering a componentWillReceiveProps.

Is there any plans to move the calculation of, at least some of, those view-controlling properties like isDisabled to the render method of Select?

**Comment by ShadOoW** [comment]
@saysmaster can you please share how you fixed this? I'm facing same issue, and unable to understand your works around.

**Comment by saysmaster** [comment]
Hello. I don't even remember now, but I read again my comments. So what I essentially did is to treat react-select as a black box. Instead of calculating view values in the array that is already inside the component, I recalculated a new array every time something changed(a computed array) and passed this array as the new options of the select.

**Comment by ShadOoW** [comment]
Hi, thank you for the reply, I was doing something similar but it was still not working.

I'm not sure how I fixed it, but I will share my experience in case somebody has this problem while using formik/mobx/react-select.

My computed prop was being called before I update the observable that it depends on, it was being called immediately after the user select an option, but as I'm using formik I wanted to wait for formik to update and use the prop passed by formik to recompute (at the cost of 1 extra render), but for some reason the compted never get executed again even after the observable changes.

For some reason if you update the observable inside useEffect, the order of execution is:
compute -> useEffect
```
  useEffect(() => {
      myMobxService.update();
  }, [values.myFormikValueThatHasChanged]);
```
But if you update the observale outside the order is:
render-> compute -> render

I guess my initial idea was to do it inside useEffect because I didn't want this code to run unless my formik property updated, but I don't see much difference by running it outside, as mobx is supposed to be smart enough to detect if a rerender is needed.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue  is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!

**Comment by torbjorn-boost** [comment]
I came here after struggling with `isOptionDisabled` not behaving like expected.

It seems counter-intuitive to be able to provide a function like this, and not have it called consistently. I remember having a similar issue earlier, though the details escape me, but it seems that again the fix is to simply map the array of options to a new array to "trigger a refresh" of the disabled state of the options. This is fine, but then I don't feel like offering the `isOptionDisabled`prop makes any sense, since I may as well add if to each option object.

This seems so weird to me, in fact, that I'm still not sure if I'm right.
