### ISSUE TITLE
Input become hidden when used as a controlled component

### ISSUE THREAD

**Issue by pathsny** [JedWatson/react-select#3515]
Here is a code sandbox demonstrating the problem 
https://codesandbox.io/s/z36kk5k0pm
As you can see, when you select an option after typing the box is empty.

**Comment by tpict** [comment]
I'm having a similar issues. Seems like `isHidden` is being set on the `Input` component incorrectly under certain conditions.

Unfortunately I don't have time to investigate a fix, but [see this block](https://github.com/JedWatson/react-select/blob/b8298f4c43a54c19fce48536fbb1cf11a8b01c68/src/Select.js#L604) for workarounds:
- set the `closeMenuOnSelect` prop to false and use `ref` to call `onMenuClose` when desired
- set the `isMulti` prop to true and manage `inputValue`/`value` manually

**Comment by Rall3n** [comment]
@pathsny The box is empty because you set `searchText` to the `name` attribute of the selected option. If the `Select` component has a `inputValue`, the selected option (or the placeholder) won´t be rendered. As reference see [this part of the source code](https://github.com/JedWatson/react-select/blob/master/src/Select.js#L1512-L1514).

I would suggest you replace `searchText: selection ? selection.name : ""` with `searchText: ""` in your `_handleSelection` to keep your selected option visible after selection.

**Comment by pathsny** [comment]
Thank you this worked.

**Comment by hkirat** [comment]
closeMenuOnSelect worked for me
