### ISSUE TITLE
Behaviour of searchable

### ISSUE THREAD

**Issue by ryuken** [JedWatson/react-select#3556]
Currently when you search in the select you are filtering on BOTH value and label.
This is really strange as most of the time values are ID's.
If you have a select with numbers:
```json
[
{ "value": "sjdfn-jkgf-2334-sadf-233445", "label": "1" },
{ "value": "sjdfn-jkgf-2334-sadf-7768", "label": "2" },
{ "value": "sjdfn-jkgf-2334-sadf-894", "label": "3" },
{ "value": "sjdfn-jkgf-2334-sadf-213", "label": "4" },
]
```
if you press 8 you are filtering on 2 & 3
if you press 2 you are filtering on 1 & 4

Its fixed by something like this:
```js
filterOptions = (candidate, input) => {

        if (input)
            return -1 !== candidate.label.indexOf(input)

        return true
}
```

**Comment by Jekillokda** [comment]
Having the same issue

**Comment by bigwheels490** [comment]
Even worse, if you pass an object as your value, the candidate string becomes "<label> [object Object]", so you're searching against something that is not part of the label or value.  For example, I had options whose labels were 'A', 'B', and 'C' and I entered 't' into the input box.  All three options were returned.  

I would suggest that from a the user's perspective they are are not intending to search on anything in the 'value' field, since they aren't even aware of it.  They are thinking they are searching for a string that is being shown to them (the label).  I think the fix is to change the generation of the candidate string to call `getOptionLabel` on the option.

**Comment by ebonow** [comment]
Greetings @ryuken , @Jekillokda , @bigwheels490 

I wanted to follow up on this issue to identify what either expected behavior could/should be and perhaps a way to remedy or customize your experience.

While some of the createFilter options are present in the example, there is another config option called `stringify` which takes the option and transforms it into the string.

By default, it is passed a default function called `defaultStringify` which is defined as:
```js
const defaultStringify = option => `${option.label} ${option.value}`;
```

This is likely why the input text is matching on the value and also why the object values are being converted into `[Object Object]`

You should be able to modify the config as follows:
```js
const stringify = ({ label }) => label;
const filterOption = createFilter({ stringify });

return <Select filterOption={filterOption} {...otherProps} />
```

Again it appears that this is not documented anywhere and instead had to be discovered from the source code so I will have this added to the documentation with hopes that this gives more awareness regarding the functionality. I hope this is helpful and let me know if you believe this to be adequate.

**Comment by ebonow** [comment]
Greetings everyone,

I have added documentation here: https://react-select.com/advanced#custom-filter-logic 

Hopefully this provides a bit more transparency regarding the matching behavior by mentioning the `stringify` function. If there is more clarification or other questions regarding this, please feel free to reply so we can address this and make it easier to understand for everyone.
