### ISSUE TITLE
Add support for debouncing filters

### ISSUE THREAD

**Issue by Quazie** [JedWatson/react-select#3591]
I have an instance of react select with 4k items - searching, even with react-select-fast-filter-options feels real slow at first - it would be nice if searches themselves could be debounced to allow for better functionality with large lists of items.

**Comment by themre** [comment]
perhaps you can replace  MenuList with react-window component? haven't tried it yet.

**Comment by bluefire2121** [comment]
duplicate #3254

**Comment by axross** [comment]
Same here.

The reason why react-select slows down is not displaying results, but seems `filterOptions()` runs for every key inputs.

<img width="708" alt="Screen Shot 2020-04-08 at 5 09 41 PM" src="https://user-images.githubusercontent.com/4289883/78844844-d6559680-79bb-11ea-9d43-9d04b6dec7a2.png">

It would be great if react-select has some way to cancel filtering, e.g. `preventDefault()` or `shouldComponentUpdate()` in `onInputChange()`. Because it enables us to debounce filtering.

**Comment by jayaramkasi** [comment]
https://github.com/JedWatson/react-select/pull/3254 This is a related PR

**Comment by lukebennett88** [comment]
Hi @Quazie,

In an effort to sustain the react-select project going forward, we're cleaning up old issues and pull requests.

As this suggestion would be a breaking change, I've added the 6.0 milestone to this issue, and will move it to the ideas section discussions
