### ISSUE TITLE
Select component placeHolder attribute not taking custom string

### ISSUE THREAD

**Issue by harrychen1** [JedWatson/react-select#3604]
Select component placeHolder attribute not taking custom string.

I've added a string as placeholder as below to display the placeHolder, however, the value always displayed as default "Select...".

        <div className={styles.row}>
          <div className={styles.column}>
          <Select
          id="targetElement" 
          **placeHolder="Select a content type"**
          value={this.props.subContentSelectListItem}
          onChange={this.props.onSubmissionSelectChange}
          isMulti={false}
          isSearchable={true}
          options={this.props.subContentSelectList}
          />
          </div>
        </div>

Could this be a bug?

Thanks in advance for you help.

**Comment by Rall3n** [comment]
Could not reproduce using the latest version. Using the prop `placeholder` the text changed as expected.

If your example code is the code you used, than it might be that you used a camel-case `placeHolder` instead of a simple lower-case `placeholder`. React is treating props as case-sensitive, meaning just changing one letter to upper-case will treat it as a different prop.

**Comment by harrychen1** [comment]
You are correct. I was using camel-case placeHolder instead of a simple lower-case placeholder.

This is my type.

Thanks for the quick response and close the case.
