### ISSUE TITLE
makeAnimated not available in unpkg

### ISSUE THREAD

**Issue by malay-15** [JedWatson/react-select#3615]
I am using ReactJS using script tag and including react-select by sourcing unpkg packages (https://unpkg.com/react-select@2.0.0/dist/react-select.js and others). "Select" component is woking perfectly fine. However, makeAnimated is not available.

I tried adding https://unpkg.com/react-select@2.0.0/lib/animated/index.js but it is throwing "ReferenceError: exports is not defined". 

Could you please add makeAnimated to unpkg dist file? Thanks.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
