### ISSUE TITLE
shouldBlockScroll not working on Firefox

### ISSUE THREAD

**Issue by focux** [JedWatson/react-select#3642]
The scroll is not being blocked on Firefox when `shouldBlockScroll` is true. You can test using the current cypress tests: https://react-select.com/cypress-tests

**Comment by richardvuu** [comment]
@focux what version of Firefox and React Select are you using? I am actually facing this problem myself but I can't replicate it on the cypress tests page

**Comment by focux** [comment]
@richardvuu I'm using version `67.0.1`

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
