### ISSUE TITLE
Multi select, display only selected items count

### ISSUE THREAD

**Issue by tynarbekov** [JedWatson/react-select#3664]
Hi all. I tried many of ways to do this. I render as component multiValueContainer.
But I didn't find right way to render only selected items count. 
Can anyone help me?

**Comment by buixuanhai** [comment]
Did you created a custom MultiValueContainer?

**Comment by tynarbekov** [comment]
Yes. like this.

`  // Selected Items
  // tslint:disable no-any
  multiValueContainer = (selectProps: any) => {
    const label = selectProps.data.label
    const allSelected = selectProps.selectProps.value
    const index = allSelected.findIndex((selected: OptionValues) => selected.label === label)
    const isLastSelected = index === allSelected.length - 1
    const labelSuffix = isLastSelected ? `` : ', '
    return (
      <components.MultiValueContainer>
        <Typography className={styles['selected-items']} type='Body1'>{`${label}${labelSuffix} `}</Typography>
      </components.MultiValueContainer>
    )
  }
`

**Comment by timbset** [comment]
Did you find the solution? I'm trying to do the same - just render the "N items are selected" label instead of tags. Already spent much time and didn't find something working.

**Comment by Rall3n** [comment]
This question has [already been asked](https://github.com/JedWatson/react-select/issues/2790) and the [solution I posted there](https://github.com/JedWatson/react-select/issues/2790#issuecomment-460636017) is still applicable to the latest version of `react-select`.

[Here is also an example](https://github.com/JedWatson/react-select/issues/3463#issuecomment-469875204) if you want to display an `All Items selected` text instead of values or count.

-----

Furthermore please restrain from posting coding questions on the GitHub page of `react-select`. The maintainers recommend that these sort of inquiries should be posted over at [Stack Overflow](http://stackoverflow.com/questions/tagged/react-select).

**Comment by trnitin** [comment]
Trying to get count instead of displaying all option was working before,but isn't now.
i suspect a problem in node modules,anyway have asked.
please help me
Cannot read property 'selectProps' of undefined

const ValueContainer = ({ children, getValue, props }) => {
        var length = getValue().length;
       
        return (
             <components.ValueContainer {...props}>
                    {console.log(length)}
                    {!props.selectProps.inputValue && length > 2 &&
                        `${length} People${length > 2 ? "" : "s"} selected`}
    
                    {React.Children.map(children,child => {
                        if (length < 3) {
                            return child;
                        }
    
                    })}
                     {console.log(...props)}
                    {console.log('hello')}
                </components.ValueContainer>
                
           
                
            );
        };

 Select Component

<MySelect
                                    value={selectedOption}
                                    onChange={this.handleChange}
                                    options={options}
                                    isMulti={true}
                                    // isSearchable={true}
                                    allowSelectAll={true}
                                    className="inputOnly react-select-container"
                                    classNamePrefix="react-select"
                                    placeholder="Makers"
                                    components={{ ValueContainer }}
                                    /* eslint no-use-before-define: 2 */  // --> ON
                                />

**Comment by prashanthsandela** [comment]
@trnitin I observed that, if  I return  custom value  in ValueContainer, it losses  onBlur  for Select with `closeMenuOnSelect={false}`. 

```
<Select
value={selectedOption}
onChange={this.handleChange}
options={options}
isMulti={true}
closeMenuOnSelect={false}
allowSelectAll={true}
className="inputOnly react-select-container"
classNamePrefix="react-select"
placeholder="Makers"
components={{ ValueContainer }}
/>


const ValueContainer = ({ children, getValue, ...props }) => {
  const length = getValue().length;
  return (
    <components.ValueContainer {...props}>
      {console.log(length)}
      {!props.selectProps.inputValue &&
        length > 2 &&
        `${length} People${length > 2 ? "" : "s"} selected`}

      {React.Children.map(children, child => {
        if (length < 3) {
          return child;
        }
      })}
      {console.log(...props)}
    </components.ValueContainer>
  );
};
/>
```

Now,  after  custom value display, like  `3 People  selected`,  onBlur doesn't work. How do I fix this issue?

**Comment by diegoaraujolima** [comment]
components not exist in Async Select... : (

**Comment by devdreamsolution** [comment]
Thank you, @trnitin , your solution works well.
