### ISSUE TITLE
React select each option as a React component

### ISSUE THREAD

**Issue by Vivek-Nehra** [JedWatson/react-select#3670]
Hey thanks for providing such an awesome library.. I just had a question would be really helpful if anyone answers it..
I need to provide an 'i' icon for each option of Select component which has an independent onClick handler so that it gives more info about that current option selected.. Is there any way I can achieve that.. Any help is appreciated

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
