### ISSUE TITLE
Options dropdown not showing in child component

### ISSUE THREAD

**Issue by nikhil-seban** [JedWatson/react-select#3674]
Rendering child component and passing all options. The parent component works with the same options
```
<Client
        key={client._id}
        client={client} options={this.props.options}
      />
```

in child component 

```
<Select
                        onChange={this.handleClientChange}
                        value={this.state.options}
                        options={this.props.options}
                        isMulti
                      />
```

here the values are showing correctly but the options dropdown never popups

**Comment by kkkrist** [comment]
How exactly do state and props of the child end up looking like? Maybe post a dump?

**Comment by nikhil-seban** [comment]
@kkkrist this.state.options have the values from db which user has already selected and the function handleClientChange will update the values on change in select. The props.options have all the option values that are passed from parent component.

Both the state and props are in the following format

`const options = [ { value: 'chocolate', label: 'Chocolate' }, { value: 'strawberry', label: 'Strawberry' }, { value: 'vanilla', label: 'Vanilla' }, ];`

**Comment by kkkrist** [comment]
So you're making an async call to fetch the values from db? Have you made sure the result is correctly passed down all the way to <Select /> so that a re-render is being triggered? 

I'd observe the option prop of the child component with the React devtools extension or by throwing in a `console.log(this.props.options)` / `debugger` statement into the `render()` method. I guess for some reason, `this.props.options` doesn't end up being what you expect it to.

**Comment by nikhil-seban** [comment]
@kkkrist I have console logged props.options before the select and the values are showing as same as in the parent component

**Comment by bladey** [comment]
Hello @nikhil-seban,

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
