### ISSUE TITLE
`tabIndex` should be a number or string/number

### ISSUE THREAD

**Issue by ematipico** [JedWatson/react-select#3687]
`tabIndex` is now a string inside the `propTypes` but it should be also a number (built in types in JSX mark `tabIndex` as number)

I noticed that there was a PR fix this: https://github.com/JedWatson/react-select/pull/1595/files

But somehow the code is now reverted: https://github.com/JedWatson/react-select/blob/master/packages/react-select/src/Select.js#L241

This is causing problems with the types (using TypeScript) where they have marked `tabIndex` as a string, forcing me to do some funky conversion inside my code base. Is there a reason for this choice of is it just an error?

**Comment by bladey** [comment]
As far as I can see this was re-implemented from scratch at one point and the string/number improvement was not brought forward.

**Comment by ebonow** [comment]
Greetings @ematipico and sorry for the late reply to this...

I see no reason why this shouldn't also be type number especially since the one defined value for it in Select.js is a number
https://github.com/JedWatson/react-select/blob/2962385e67e213c61bc62f087426b44895ffa5b8/packages/react-select/src/Select.js#L1764

I have created PR to resolve this.
