### ISSUE TITLE
onChange is not called when menuPortalTarget is set

### ISSUE THREAD

**Issue by dana2208** [JedWatson/react-select#3721]
when I set menuPortalTarget  to the body ot other containing element, the select is broken and the onChange is not triggered, I have noticed that when I am clicking on a menu item a "focus" event is fired on the select input element, probably causing the onChange not to fire, 

Do you have any idea on what may cause this behaviour?

Thanks!

**Comment by ebonow** [comment]
Greetings @dana2208 ,

I have tested this and it appears to no longer be an issue as demonstrated [here:](https://codesandbox.io/s/react-select-v3-sandbox-menu-portal-right-812b9?file=/example.js)

If you are still experiencing an issue, would you kindly provide a codesandbox example of your implementation so that we can better assist with whatever challenges you are running into? At that point we can continue to assist or re-open this if there is some bug discovered.

Thank you.

**Comment by aarandale** [comment]
I am facing same issue here. I have explicit onchange function on Select with multi enabled
