### ISSUE TITLE
HI, Does support tree select? I am not found it.

### ISSUE THREAD

**Issue by vimiPonyai** [JedWatson/react-select#3750]
Thanks in advance.

**Comment by vimiPonyai** [comment]
@alexeygolev good to know your advice.
I am finding a component it can render a `tree select`. 
useage:
    * father node represent day (monday, tuesday ....)
            * son node represent time(morning, evening ...)
so it`s very useful for user can select monday-morning or tuesday-evening.
(will like as:)[https://ant.design/components/tree-select-cn/#header]
![image](https://user-images.githubusercontent.com/44854469/65651146-208ab200-e040-11e9-8a85-5b5819b77b19.png)

**Comment by bladey** [comment]
Hi @vimiPonyai,

I wanted to check in and see if you still required this feature. We're triaging issues at the moment to sustain the project going forward.

**Comment by vimiPonyai** [comment]
@bladey sure, it`s pretty useful if support tree-select component. actually I can`t find any good tree-select component while using react + material-UI.

**Comment by ebonow** [comment]
Greetings, 

I have used `rc-tree` via antD react components and found it both easy to use and very flexible.
https://github.com/react-component/tree

Truth is there is a fair bit of complexity and flexibility involved with creating a Tree (see the list of props in rc-tree or view their storybook), so it's likely this could become an ask as large as the rest of all other react-select features.

As of now, it is not something immediately in the roadmap, but there are others requesting this feature here in https://github.com/JedWatson/react-select/issues/4229 and seems like there is being development made by the community. I am hoping that it is successful and we can add it to the "Show and Tell" area in discussions. I would love to compile a list of useful react-select "recipes", but I digress...

Since this request is a duplicate and there is more recent activity taking place, I will close this issue, but please feel free to contribute and continue to the conversation there.

**Comment by alextaymx** [comment]
> 

@ebonow Hi there, I noticed the rc-tree is just a plain component without any styles. May I know how do you style it nicely?
