### ISSUE TITLE
Mutliselect menu doesn't get closed after clicking outside of the menu

### ISSUE THREAD

**Issue by jbojcic1** [JedWatson/react-select#3756]
I have a multiselect with closeMenuOnSelect false, and control component passed like:
`Control: (props) => MyControl(props, somethingElse)`
when select is controlled by the parent, menu doesn't get closed on the outside click. however if I define control component without additional params and just use:
`Control: MyControl`
menu is closed fine

Example: https://codesandbox.io/s/react-codesandboxer-example-mbnrb

To reproduce the issue just select few values and try to click below the menu and it will stay open. Then pass just a component to the Control instead of `props => component(props)` function and it will be closed normally, or instead just make select uncontrolled by deleting values and onChange and it will also close normally.

**Comment by pauloandreget** [comment]
Hey @jbojcic1 almost 9 months later, did you find a solution for this? I have the exact same issue on version 3.1.0 while using custom `components.Control` with extra props.

**Comment by jbojcic1** [comment]
@pauloandreget I worked around it by creating "full" component for the Control, passing somethingElse param to selected and then accessing it in Control component via selectProps. 

Control component:
`export const Control = <T extends any>(props: ControlProps<T>) => {
  ...
  const selectProps = props.selectProps as SelectProps<T>;
  const somethingElse = selectProps.somethingElse;
  return (...);
};`

then use it like:
`
   const components = { Control };
<ReactSelect<TOption> 
  components={ Control }
  somethingElse={...}
  ...
/>`

**Comment by pauloandreget** [comment]
Thanks @jbojcic1 seems to works fine using `selectProps` this way until the official fix for this issue.

**Comment by ebonow** [comment]
Greetings @jbojcic1 and @pauloandreget ,

I am writing to add some clarification to the issue stated here. 

Indeed, the implementation in the codesandbox is not the recommended way of replacing components. There has been a lot of confusion and rightfully frustration that these types of component replacements don't work. I wanted to confirm that declaring components inline will cause issues. The root of which can be best summarized by the [React docs
](https://reactjs.org/docs/higher-order-components.html#dont-use-hocs-inside-the-render-method)

>The problem here isn’t just about performance — remounting a component causes the state of that component and all of its children to be lost.
Instead, apply HOCs outside the component definition so that the resulting component is created only once. Then, its identity will be consistent across renders. This is usually what you want, anyway.

This applies to the internal state and references within the react-select components as the ref relationships are impacted by the unnecessary remounting. Instead, as was the solution, declare the components outside the Select scope.

I will be closing this issue, but please feel free to reply if there are any additional questions or concerns and we can reopen this if applicable.
