### ISSUE TITLE
ScrollLock dist missing window undefined check

### ISSUE THREAD

**Issue by swensorm** [JedWatson/react-select#3802]
While attempting to upgrade react-select from version 2.4.4 to the latest 3.0.8 I'm running into issues with server side rendering and the following error:
```
ErrorDetails : ReferenceError: window is not defined
    at ./node_modules/react-select/dist/base/dist/react-select-cac0a5ae.browser.esm.js (server.min.js:117809:17) -> var canUseDOM = !!(window.document && window.document.createElement);
```

We use this within a .Net CMS by way of ReactJS.Net so the `window` object is not available while it is being rendered on the server.  The strange thing is that looking at the dist output from the npm package, the check for window being undefined isn't there:
![image](https://user-images.githubusercontent.com/1808452/66236311-c8932180-e6b7-11e9-947b-2bc3cff6e8bf.png)
However, looking at the src it is:
![image](https://user-images.githubusercontent.com/1808452/66236359-e9f40d80-e6b7-11e9-8d7a-456fa0b73a9e.png)

The check did exist in the dist output of the 2.4.4 version so something with the build process may have been changed with version 3.0.0 that could have caused this?  Thank you for looking at the issue!

**Comment by krzysztof4M** [comment]
@swensorm  Have you found any solution?

**Comment by mgrzyb** [comment]
The bundle you use on the server should be built with webpacks target: 'node' to resolve modules from 'main' or 'module' fields and not using client-side specific aliases.

Since you're not running it under nodejs (ReactJS.NET does not provide full nodejs environment) you will get "require is not defined" when trying to use bundle built like this but there is away.

In the server build, keep target: 'web' (default when unspecified) but change resolve.aliasFields to an empty array, like this:
```
module.export = {
 ...
 resolve: {
    aliasFields: []
  }
}
```
This way webpack will not use browser specific aliases when resolving react-select module... Ufff... :)

**Comment by alverdal** [comment]
I was able to solve a similar issue with "window is not defined" when using SSR with reactjs.net by using your fix @mgrzyb . 
Issue was described in ticket https://github.com/marcelltoth/react-select-reborn/issues/8.

**Comment by swensorm** [comment]
While I can confirm that adding `aliasFields: []` to the webpack config did indeed fix the drop-down rendering server side, it had the unfortunate side effect of causing over 1 MB of locale data from the `Intl` package to be included as well.

**Comment by rafalschmidt97** [comment]
> While I can confirm that adding `aliasFields: []` to the webpack config did indeed fix the drop-down rendering server side, it had the unfortunate side effect of causing over 1 MB of locale data from the `Intl` package to be included as well.

Same :)

**Comment by devstarman** [comment]
Why can't you check if windows is defined on canUseDOM() function?
I'd like to use some of hacks mentioned above but:
1) I can't conditionally render this component because my SSR config is still going through all the code and encounters this canUseDOM method even in case when it's not rendered.
2) I can't modify my webpack config due to project configuration (it's create-react-app based template and ejecting would cause much damage).

**Comment by ianks** [comment]
In the code, it looks like there is a check for `typeof window !== 'undefined'`, however in the compiled version I see:

```
// node_modules/react-select/dist/Select-9fdb8cd0.browser.esm.js:430s

var canUseDOM = !!(window.document && window.document.createElement);
```

Manually updating that code fixes the issue. For time time being, I guess we are stuck on the older version.

**Comment by AdnanTheExcellent** [comment]
Any headway on this? the alias and aliasFields method did not work for me when trying to upgrade to react-select 3.1.1

**Comment by ebonow** [comment]
Good news everyone! Looks like this behavior in `preconstruct` was fixed in version 2.0.2 which was released within the last 24 hours. 
https://github.com/preconstruct/preconstruct/releases/tag/%40preconstruct%2Fcli%402.0.2

I will inquire about getting its dependency updated from 1.0 to 2.0.2 to resolve this as well as any other changes that might be required.

**Comment by Methuselah96** [comment]
[@mgrzyb's comment](https://github.com/JedWatson/react-select/issues/3802#issuecomment-589819173) hits at the root issue and provides the best solution at the moment. See https://github.com/reactjs/React.NET/issues/1017 for more context.

I don't believe that the fix to Preconstruct affects this issue because that fix is specific for UMD builds, and this issue is specific to non-UMD builds.

I'm going to close this for now. I don't believe that there's anything else that `react-select` can do to improve the situation. This is more of a ReactJS.NET problem than a react-select problem since we are correctly assuming that `window` is defined in a `web`/`browser` context. Feel free to comment if you think there's something that we can do to improve the situation.

**Comment by Methuselah96** [comment]
I'll leave this open until a permanent solution is found.

**Comment by swensorm** [comment]
I do not agree with the assessment that the runtime environment not supporting a `window` facade is the root cause of the issue.  I do, however, agree that the root cause is not _directly_ react-select, but would say is in fact the `preconstruct` build tool.  If preconstruct is "correctly stripping `typeof window` checks" then shouldn't it be stripping `window.document` checks as well since that will also always exist in a browser context?  It is unfortunate when tools try to be too 'smart' for their own good.  I would accept this issue being closed on this basis though.

It has been some time since I was in these codebases, and we're on a pretty old version, so perhaps just need to take another look at the build and split ssr from client or, as @ianks suggested, see if the non-browser cjs version works.

**Comment by Methuselah96** [comment]
@swensorm I am in general agreement with what you're saying although I would have to do some further investigation into the issue to form a stronger opinion. I don't think that the root issue is Precontruct, I think it has more to do with not having a way to express which file can/should be used for SSR. I've made [a PR](https://github.com/JedWatson/react-select/pull/4423) to remove the browser alias fields since they provide no real benefit.

**Comment by Methuselah96** [comment]
I've done some more research. Even if we remove the browser alias fields for `react-select` it still breaks with Emotion 11. See https://github.com/emotion-js/emotion/issues/1246, https://github.com/emotion-js/emotion/issues/1407, and https://github.com/emotion-js/emotion/issues/1728 for more details. This is a fundamental issue with ReactJS.NET and other SSR libraries that configure their Webpack config to target `web`.

If we are able to do anything on our end that would fix the problem, we would do it, but at this point Emotion would need to change first (which doesn't seem likely given the above issues).

**Comment by Methuselah96** [comment]
I've done some more research. Even if we remove the browser alias fields for `react-select` it still breaks with Emotion 11. See https://github.com/emotion-js/emotion/issues/1246, https://github.com/emotion-js/emotion/issues/1407, and https://github.com/emotion-js/emotion/issues/1728 for more details. This is a fundamental issue with ReactJS.NET and other SSR libraries that configure their Webpack config to target `web`.

If we are able to do anything on our end that would fix the problem, we would do it, but at this point Emotion would need to change first (which doesn't seem likely given the above issues).
