### ISSUE TITLE
Custom Menu component is breaking menuPlacement="top"

### ISSUE THREAD

**Issue by DeyLak** [JedWatson/react-select#3812]
I tried to create my custom `Menu` component, but it didn't work.

https://codesandbox.io/s/react-codesandboxer-example-pk48u?fontsize=14

In the sandbox, I copied original `Menu` component implementation from [here](https://github.com/JedWatson/react-select/blob/master/packages/react-select/src/components/Menu.js#L332) but my prop `menuPlacement="top"` is still not working.

Sorry, If, I got it wrong, but I didn't find a lot about this option in the docs.

**Comment by DonkeyAfterDark** [comment]
That sandbox uses an iFrame to display the content. Try on a real website and make sure to set the menuPortalTarget to document.body.

**Comment by DeyLak** [comment]
@DonkeyAfterDark I didn't get you, how does iframe influence portalling of the select? Setting `menuPortalTarget` doesn't seem to have some difference.
You also can open the sandbox as a standalone site by copying the url from the sandbox browser address bar: https://pk48u.csb.app/

**Comment by Rall3n** [comment]
@DeyLak The compiler does not recognize the `css` prop. You have to add following configuration to your file:
```jsx
/** @jsx jsx */
import { jsx } from '@emotion/core';

/* Rest of the code */
```

The `@jsx` pragma tells the babel compiler to use another variable for jsx-element parsing instead of the standard `React` variable (basically the reason we have to `import React from 'react';` in every component file). The `jsx` variable from `@emotion/core` is a replacement for the standard `React` variable which handles the `css` prop.

**Comment by DeyLak** [comment]
@Rall3n Thanks, it worked.
