### ISSUE TITLE
Feature Request: Make a custom Option component receive isCreatable as prop to render custom "Create ..." option

### ISSUE THREAD

**Issue by wachunei** [JedWatson/react-select#3833]
# Feature Request
I'm using async react-select with custom components, I want to improve this selector by using async creatable. As far as I've read the only way to customize the "create .." row is by using `formatCreateLabel`, this is only going to customize the `label` object passed down to my custom `Option` component.

My custom `Option` component displays extra information that the default "Create ..." row does not have at the moment, thus I need to conditionally render another component. Having a `isCreatable` prop would come in handy for such task.

Right now as a workaround I'm customizing the `label` prop passing down a specific object and depending on that to display a custom `Option` component.

**Comment by ebonow** [comment]
Greetings @wachunei ,

I agree that it is obscure, but it is possible to render the "Createable Option" through the existing methods using the `formatOptionLabel`. 

https://codesandbox.io/s/react-select-createable-option-lm6ro

``` JS
const formatOptionLabel = (option, { context }) => {
  return context === "menu" && option.__isNew__ ? (
    <Fragment>
      {option.label}
      <br />
      <small>This is a created item</small>
    </Fragment>
  ) : (
    option.label
  );
};

return <Createable formatOptionLabel={formatOptionLabel} ... />
``` 

I'll be closing this issue so that we can continue to work through existing bugs and issues, but can reopen it if necessary. Let me know if you have any troubles working with this implementation.
