### ISSUE TITLE
Right click in react-select creatable multi-select text input only shows correct options when user clicks on the curser

### ISSUE THREAD

**Issue by scrayWC** [JedWatson/react-select#3836]
Right click in react-select creatable multi-select text input only shows correct options when the user clicks where the curser appears at the very beginning of the input.

![Screen Shot 2019-11-01 at 6 15 21 PM](https://user-images.githubusercontent.com/30298592/68123608-7bcf8000-fedb-11e9-91b6-ca1c58f91ffd.png)

If a user clicks anywhere else within the input, these options appear instead. 

![Screen Shot 2019-11-01 at 6 21 39 PM](https://user-images.githubusercontent.com/30298592/68123606-7bcf8000-fedb-11e9-814f-b6a9f935f90b.png)

Shouldn't there be a way to increase the default width of the input to allow users to click anywhere within it and have the correct options show up?

**Comment by ebonow** [comment]
Greetings @scrayWC ,

I recently responded to another ticket about this https://github.com/JedWatson/react-select/issues/4106 and happen to have a working code example.

Working demo: [codesandbox](https://codesandbox.io/s/react-select-paste-on-mobile-q51wl?file=/src/App.js)

The input by default is meant to shrink to the smallest width specifically for multiSelect. This might cause some conflicts for you as it seems you want to fit to the width of the available space as the mutlValues populate.

Therefore, the jist is that you override the input to be 100% though it is fairly nested so it will require setting the width of its parents also to 100% with Input Container having no width, but instead `flex: "1 1 auto"` so that it will fill out the horizontal space.

You would also need to disable mouse events on the placeholder to ensure it doesn't receive the click target instead of the input.

This is what I was able to put together:
```js
return <Select 
          styles={{
          placeholder: (provided) => ({
            ...provided,
            // disable placeholder mouse events
            pointerEvents: "none",
            userSelect: "none",
            MozUserSelect: "none",
            WebkitUserSelect: "none",
            msUserSelect: "none"
          }),
          input: (css) => ({
            ...css,
            /* expand the Input Component div */
            flex: "1 1 auto",
            /* expand the Input Component child div */
            "> div": {
              width: "100%"
            },
            /* expand the Input Component input */
            input: {
              width: "100% !important",
              textAlign: "left"
            }
          })
        }}
/>
```

Hope this works for you and I can re-open this for you if you have any other questions or concerns.
