### ISSUE TITLE
Feature Request : Exclude logic

### ISSUE THREAD

**Issue by souuu** [JedWatson/react-select#3837]
**Feature Request :**
*   **What's your use case? (Tell us about your application and what problem you're trying to solve.)**
I have a multi select list and resulting rows depending on what is selected.
There is no way to exclude some elements from the list, this can be achieved only by selecting all the elements except the one that I want to exclude which is not a correct UX.
*   **What interface do you have in mind? (What new properties or methods do you think might be helpful?)**
Well I can suggest 2 ways :
1- after selecting the element, if you click on it and not the 'X' icon it switch to red color which means that the element is excluded. Of corse this option can be disabled from the props.
2- if excluding mode is activated, an exclude icon is added in the end of the element line, when the user clicks on the icon, the element is selected but in a disabled state or colored with red.
*   **Can you point to similar functionality with any existing libraries or components? (Working demos can be helpful.)**
Well, we can see the filtering way of google spreadsheets, you can select all except one, but they have their own logic when filtering.

**Comment by ebonow** [comment]
Greetings, 

> There is no way to exclude some elements from the list, this can be achieved only by selecting all the elements except the one that I want to exclude which is not a correct UX.

I don't know if you found a working solution, (our team has debated the merits of a select all vs split dropdown to select include or exclude mode), but it certainly seems possible to create this with custom components. 

Discussing proper UX is difficult because it is subjective and this is a use case that I feel many woudl have different opinions on how to achieve this.

Personally, having it on the multiValue might cause confusion especially if there are multiple selected items. Turning one red, turns all red, might not be an expected outcome for a user, but you could implement it with this as a starting point:

```
const [ values, setValues ] = useState([]);
const [ excludeSelected, setExcludeSelected ] = useState(false);

const styles = {
  MultiValue = css => ({ 
    ...css,
   cursor: 'pointer',
    ...(excludeSelected && { 
      background: 'red',
      textDecoration: 'line-through'
    })
  })
}

const MultiValue = props => {
  const onClick = () => setExcludeSelected(!excludeSelected);
  return <MultiValue onClick={onClick} {...props} />
} 

<Select components={{ MultiValue }} styles={styles} ... />

``` 

I like the idea of perhaps adding an indicator to the Indicator Container to toggle include/exclude mode but there are other options.

- Putting a button in your dropdown menu options that show up on focus to say "Exclude"
- Adding a select all toggle to your Menu
- Using a split dropdown to choose the mode (Include or exclude)

Personally I think flights.google.com does a fairly good job at this when filtering airlines after choosing a flight destination and date.

That all said, the UI would have to be dynamic to fit the UI and thematic needs of many so I think exclude would be impossible to get correct for everyone, let alone most. I would welcome more examples for devs and designers alike to choose from, but for now the implementation should be the same.

Also, the selection mode could be made to toggle values as well should you want to toggle the selection type.
```
const onChange = opt => {
  const selected = [ ...values, opt ];
  const selectedVals = selected.map(x => x.value);

  setValues(excludeSelected ? options.filter(x => !selected.includes(x.opt)) : selected);
}
```

Again, just more food for thought, but hoping you have an example of how you implemented this so others can be inspired.

Cheers

**Comment by ebonow** [comment]
It would appear that react-select currently allows enough flexibility to implement such a UX design as you are proposing and would likely be welcomed if you were to develop a proof of concept in a sandbox to share with the community.
