### ISSUE TITLE
Unable to paste values in the search field

### ISSUE THREAD

**Issue by ArtyomShalagin** [JedWatson/react-select#3857]
I noticed that the browser does not identify the text input for the select field as a text field which means I cannot paste values in it. Actually `Ctrl + V` works fine but the right-click menu doesn't have a "Paste" option and, more importantly, I cannot long-press paste from the touch version. Is it a bug or is it expected behavior for some reason?

**Comment by yaeltu** [comment]
you mean you can't type inside the select bar? because I can

**Comment by ArtyomShalagin** [comment]
Ok, I kind of figured it out. The problem is that the placeholder is actually not a `placeholder` prop for the underlying `input` but just a `div` with text. The actual input initially has zero width and is growing wider as you type. My temporary fix was to manually set width for `react-select-2-input` element and set higher z-index for the div containing the `input` element so that it will be in front of the div with the placeholder.

Now I'm just wondering why was this made that way? Looks like setting `placeholder` prop for the `input` instead of making a separate div doesn't break anything and then pasting works fine but maybe there was a reason for it? I could probably fix it and create a PR if this is a bug 
@JedWatson

**Comment by Iulia-Soimaru** [comment]
+1 to ^ I am facing exactly the same issue

It would be great to have api to actually change `input` styles through the style object, because when you are adding styles to `input` object,  it's actually for the `div` that wraps the input

<img width="1165" alt="react-select" src="https://user-images.githubusercontent.com/8752554/77203437-a185ac00-6aad-11ea-89bb-2335e6e9712d.png">

We are using styled components in the code base, for now I just overwrote styling for `Creatable` with
 `input { width: 100% !important }`

```
const StyledSelect = styled(Creatable)`
    width: 100%;

    input {
        width: 100% !important;
    }
`;
```
