### ISSUE TITLE
Mix text and tags both in MultiSelect Input [v2]

### ISSUE THREAD

**Issue by CaptainT33mo** [JedWatson/react-select#3872]
Is there a way to add both normal text and tags in the multiselect option as demoed here: https://yaireo.github.io/tagify/#section-mix

In one of my use case, I am trying to add a search field which will have a normal text and tags in the search field and for that, I want to use react-select but couldn't figure out how to do it with multiselect input. Any help would be much appreciated.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!

**Comment by npearson72** [comment]
I'm curious why this issue was closed? Is there a way to handle mixed input like the OP is asking about?
