### ISSUE TITLE
can we use classNamePrefix for custom styling?

### ISSUE THREAD

**Issue by KSK3107** [JedWatson/react-select#3894]
Hi, can we use classNamePrefix for custom styling or do we have to follow only the way which is suggested in docs, like creating a styles object. 

I have a scenario where I am overriding the MenuList, Option, MultiValueContainer components for multi-select-dropdown. I this case I am using something like,
`<div className="select-input-container">
        <components.Input {...inputProps} />
    </div>`

How can I acheive css like 'The input which is inside the select-input-container should have different styling'
Eg: 
.select-input-container {
 input {
// overriding styles
}
}

**Comment by bladey** [comment]
Hello @KSK3107,

In an effort to sustain the `react-select` project going forward, we're cleaning up and closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

However, if this issue is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
