### ISSUE TITLE
After selection, dropdown doesn't display options unless focus is lost

### ISSUE THREAD

**Issue by ibarczewski** [JedWatson/react-select#3895]
We're using 3.0.8, and have a select option that opens a calendar to select a custom date. When the custom date is selected, they cannot click the dropdown to show values again unless they click outside of it. This is working as intended when clicking any other value.

GIF demostrating the issue (weird size due to having to cover sensitive client information): https://giphy.com/gifs/YoKhMefK3pHhvTxoD1/

I believe this was possibly handled in #1887, but it is still an issue here.

**Comment by VinceVachon** [comment]
I also experience this bug. Someone has a temporary fixes for this?

**Comment by ebonow** [comment]
Greetings @ibarczewski , 

Sorry for the long delay in getting a reply. Can you confirm if this is still an issue for you or can this now be clossed?

**Comment by ebonow** [comment]
In an effort to maintain the list of reported issues, I will be closing this. If either you @ibarczewski or @VinceVachon are still experiencing issues, please feel free to reply and provide a reproducible example codesandbox so we can better help diagnose any issues you might be experiencing in your custom implementations of react-select. We would happily re-open this issue so that we can investigate further so long as we have a starting place to better understand what is happening and if it is a library or implementation issue.
