### ISSUE TITLE
"Cancel selection" buttons, whole dropdown, and dropdown arrow not usable by vimium

### ISSUE THREAD

**Issue by Trial-In-Error** [JedWatson/react-select#3908]
Vimium is an assistive / convenience tool that (among other functionality) enables navigating links / clickable items strictly through keyboard shortcuts. It uses [the heuristics in this source](https://github.com/philc/vimium/blob/master/content_scripts/link_hints.coffee#L627) to determine if something is "clickable". Currently, react-select is completely invisible to vimium. I would expect it to present a handful of clickable items: the entire component, each selected items' "cancel" x, and the dropdown arrow. This could be accomplished by adding, for instance, the attribute "role=button" to each of these elements.

This is mildly inconvenient for me as a Vimium user, but I'm also concerned that this may be a more common problem with other assistive tech. Is this an intentional choice by react-select? How does this fit into the larger story of a11y as you see it?

**Comment by plondon** [comment]
Here's how I handled it

https://github.com/blockchain/blockchain-wallet-v4-frontend/commit/49d97e945c7941fc0f65913bd893af995360a7d6

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
