### ISSUE TITLE
Fix the UNSAFE Methods

### ISSUE THREAD

**Issue by davidcostadev** [JedWatson/react-select#3931]
First, thanks this amazing package! :-) But I really can't update to the 3.X version.

I made a fork to fix the problem of UNSAFE methods v1.3.0.

https://github.com/JedWatson/react-select/compare/v1.3.0...davidcostadev:v1.3.1

I tried to create a pull request this to this tag but this not worked, it's because that is not a branch. I suggest create a branch called v1 upon the v1.3.0 tag, to help who are still using this version.

**Comment by JedWatson** [comment]
Thanks @davidcostadev!

Unfortunately we can't publish an official 1.x release with the fixed lifecycle methods because they're not available in the version of react (15) that 1.x is using and I know some people haven't upgraded to react 16 version yet who still use react-select v1.

So anyone who has this problem will need to fork it themselves, as you have.
