### ISSUE TITLE
Accessing custom MenuList buttons with keyboard

### ISSUE THREAD

**Issue by fridagoransson** [JedWatson/react-select#3940]
I have built a react-select with a custom MenuList. In this custom MenuList i have two buttons. They work fine when i'm using a mouse but I can't get to them if i'm using a keyboard.

Is it possible to do this? Either by using arrow down/up and getting to the buttons after reaching the end/start of the list or by tabbing/"pseudo-tabbing" to the buttons.

Here's a simplified example where I have tried to use the onKeyUp function to capture when a user is at the first or last option. This works but i'm unsure of what to do next..

https://codesandbox.io/s/ecstatic-tree-5349w

I've also tried to find out if it's possible to add it to the list of focusable items in any way but so far I haven't found anything. Anything that can help med reach the buttons by keyboard would be really helpful :)

**Comment by flexdinesh** [comment]
@fridagoransson this is not a solution but may I recommend an alternate approach?

select is semantically expected to hold the input and options. It makes more sense to have behaviorioral buttons either outside the select or in the control component rather than in the menulist.

More here — https://codesandbox.io/s/react-select-custom-control-zxkmf

**Comment by fridagoransson** [comment]
@flexdinesh Yes, i understand what you mean and I agree that it makes sense. 
But the design i have received don't really support this at the moment so it's kind of a last resort to change it

**Comment by fridagoransson** [comment]
This is how I ended up solving it https://codesandbox.io/s/exciting-faraday-to6gi
