### ISSUE TITLE
Custom input component won't inherit the styles

### ISSUE THREAD

**Issue by Simpleqode** [JedWatson/react-select#3947]
I am following the React Select docs to alter the Input component of the Select (to add more properties I need to the default input):

```
const Input = ({ getStyles, onChange, innerProps }) => {
  return <input style={getStyles('input', props)} onChange={onChange} {...innerProps} {...somethingElseINeed} />;
};

const CustomSelect = props => {
  return (
    <Select components={{ Input }}></Select>
  );
};
```

However, it won't apply the styles applied to the default React Select component. What am I missing?

**Comment by alexristich** [comment]
You're referring to this, correct? https://react-select.com/components

```
const Input = props => {
  if (props.isHidden) {
    return <components.Input {...props} />;
  }
  return (
    <div style={{ border: `1px dotted ${colourOptions[2].color}` }}>
      <Tooltip content={'Custom Input'}>
        <components.Input {...props} />
      </Tooltip>
    </div>
  );
};
```

What I see here is that `Input` is returning a wrapped `<components.Input>`. What I see in your code is that you're just returning `<input>`.

From the API (https://react-select.com/props), it also doesn't look like `onChange` is a supported property for `components.Input`.

**Comment by bladey** [comment]
Hello -

Thanks for your assistance @alexristich!

In an effort to sustain the `react-select` project going forward, we're closing issues that appear to have been resolved via community comments or issues that are now redundant based on their age.

However @Simpleqode, if you feel this issue is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you, and we'll re-open it if necessary.
