### ISSUE TITLE
[Bug] Can't test autofocus prop

### ISSUE THREAD

**Issue by amit-davidson** [JedWatson/react-select#3965]
Hey,
I'm using the autoFocus prop in the dropdown and it works in the browser, but I'm having trouble testing it. I'm using the autoFocus prop and it doesn't seem to open the menu when I search for the options (No results for searching `react-select-dropdown-multiple__option` by className)

I investigated more into the code and found this:https://github.com/JedWatson/react-select/blob/d78730377e25658a5df2930faee54574e757d463/packages/react-select/src/__tests__/Select.test.js#L1756.

Seems that this test is intentionally not tested. I wanted to know if it's planned to be solved anytime soon and if there's a workaround for testing this prop?

**Comment by amitdavidson234** [comment]
@bladey Any update?

**Comment by bladey** [comment]
No update yet @amitdavidson234.

**Comment by ebonow** [comment]
The code itself has a documented example of this as a codesandbox link:
https://codesandbox.io/s/71xrkj0qj

I forked it, updated the versions of all the packages and confirmed that this is still an issue.

**Comment by ebonow** [comment]
@amit-davidson

I decided to revisit this and it appears that the sandbox that is referenced in the testing suite is using `autofocus` instead of `autoFocus` as it is documented. After updating the version and using the correct prop name, I was able to get a codesandbox that works for both isMulti and singleSelect.
[codesandbox](https://codesandbox.io/s/react-select-autofocus-kzymo)

I revisited the testing harness and was able to run the unit tests as expected and without issue. Additionally, I was able to confirm another that had been commented out. 

I have created a PR that will update the test suite to avoid confusion, but seems that I can safely close this issue. Please, let me know if you are still experiencing issues, and we can re-open this.

**Comment by amit-davidson** [comment]
@ebonow I'll test this and re-open if needed. Thanks!
