### ISSUE TITLE
Is there a way to conditionally close the dropdown based upon a value?

### ISSUE THREAD

**Issue by KleonTsimperis** [JedWatson/react-select#3978]
I'm not sure if I can classify this is a bug, but I'm trying to close the dropdown based on a selected value and it seems that 2 clicks need to be pressed in order for this to work. So I'm using the `closeMenuOnSelect` prop and passing a boolean state value that is alternating based if one of the selected values has been chosen. So say I have 3 values (1,2,3) and would like the dropdown to close only if value 1 is selected. However, I have to select the value 1 twice in order for the dropdown to fold away. Here is a quick snippet: https://codesandbox.io/s/sharp-panini-h3vii

**Comment by ebonow** [comment]
Unfortunately, the menu will close onChange prior to the setting taking effect.

What you can do is toggle the `menuIsOpen` prop instead. 

I forked your sandbox hoping that this accomplishes what you are looking to do as I had to implement something similar.

https://codesandbox.io/s/admiring-jennings-6c56n?file=/src/App.js

**Comment by bladey** [comment]
Hello -

Thanks for your assistance @ebonow!

In an effort to sustain the `react-select` project going forward, we're closing issues that appear to have been resolved via community comments or issues that are now redundant based on their age.

However @KleonTsimperis, if you feel this issue is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you, and we'll re-open it if necessary.
