### ISSUE TITLE
Migration Issue: ref prop now returns StateManager

### ISSUE THREAD

**Issue by Mhbuur** [JedWatson/react-select#3984]
I just upgraded from v2 to v3 - almost painless, except one issue.

With v2 I retrieve a component reference this way (overall context is that I need to blur the control on close):

`<Select ref={ref => this._select = ref} ...`

With v3 the ref type changed to StateManager and I get the following error:

Type 'StateManager<any, Select<any>>' is not assignable to type 'HTMLInputElement'

I've looked in the migration notes and I can't find anything about this issue. I found a related discussion about ref not being a prop, but none of the suggestions there seem to work (and the issue is still open): https://github.com/JedWatson/react-select/issues/2181

Am I missing the obvious here - how do I get the input element reference in v3?

**Comment by shankarregmi** [comment]
+1

**Comment by chrisdraws** [comment]
I'm also seeing this issue.

**Comment by Rall3n** [comment]
`ref` on the default `Select` import should always be the `StateManager`, even in v2. You might have imported the base component directly instead of using the default.

The input responsible for handling blur and focus is available under `managerRef.select.inputRef`.

-----
But by default you should not have to manage focus or have to trigger blur by default. The `StateManager` handles this all by its own.

**Comment by chrisdraws** [comment]
Thank you.  I know this is a little bit off of this topic, but might you
aliso know who select the dropDown menu itself?  We are putting it into a
portal and I'm having trouble then getting a reference to the menu, from
which I want to grab it's dimensions because in some cases it's going off
the screen to the left or pushing down into the bottom.  We already have
menuPlacement="auto" which helps in most cases, but there are some cases in
which i need to measure where the menu is actually positioned in reference
to the window or modal, and I"m having trouble grabbing a reference when
the menu is open in order to measure it.

**Comment by ebonow** [comment]
@chrisdraws it's currently a known issue that `onMenuOpen`, the menuListRef is null. The easiest way to get around this is with a timeout to allow the ref to catch up with the state changes.

``` JS
  const selectRef = useRef();

  const onMenuOpen = () => {
    setTimeout(() => {
      const { menuListRef } = selectRef.current.select;
      // Do stuff with menuListRef
     }, 1);
  };

  return <Select ref={selectRef} onMenuOption={onMenuOption} />
```

I hope this answers your question. For time being, I will consider this resolved by @Rall3n (Thank you!) and if there are any other questions or concerns, we can re-open this issue. Thanks!
