### ISSUE TITLE
Is it possible to include group names into the search?

### ISSUE THREAD

**Issue by Lord-Mendoza** [JedWatson/react-select#3996]
I have my options for my ```<Select>``` to receive the following format:
```javascript
[{label: "Animals",
  options: [
        { label: "Dog", value: "Dog" },
        { label: "Cat", value: "Cat" }
  ]
}];
```
With the existing setup, when you type to search it's only searching by value, but I was wondering if you can also search by group names?

**Comment by ebonow** [comment]
I implemented something like this. The assumption is that if the inputText matches a group label, then display the entire group. Otherwise, only display options from that group that matches the input. 

- **foundNeedle**: Basic string matching function
- **filterGroupAndOptionLabels**: Filter function for groups - If text matches group label, return entire group, else return new group with only matching filtered options included and omit groups not matching either group or option labels.

NOTE: I am using a Component instead of a string for group label, so I have to compare on one of the Component's custom props (`textLabel` for this example), but if your group label is a string, then using `group.label` instead of `group.label.props.textLabel` would work


```
  const getOptions = () => [{
    label: "Animals",
    options: [
        { label: "Dog", value: "Dog" },
        { label: "Cat", value: "Cat" }
    ]
  }];

  const loadOptions(inputValue='', callback) {
    const needle = inputValue ? inputValue.toLowerCase() : '';

    const foundNeedle = (stack, fromBegin = false) => (
      fromBegin ? stack.toLowerCase().startsWith(needle) : stack.toLowerCase().includes(needle)
    );

    const filterGroupAndOptionLabels = (groups) => (
      groups.map(group => {
        if (foundNeedle(group.label.props.textLabel, true)) {
          return group;
        }

        // If it doesn't match group label, filter options within group
        const groupOptions = group.options.filter(groupOption => foundNeedle(groupOption.label));

        // If there are no matches, exclude group, else return new group with filtered options
        return !groupOptions.length ? null : { label: group.label, options: groupOptions };
      }).filter(x=>!!x) // filter out null groups
    );

    const options = getOptions();
    const filteredOptions = options.length ? filterOptions(options) : [];
    callback(filteredOptions);
  }
```

And then you should simply be able to call the following
```
return <Select loadOptions={loadOptions} />
```

Please let me know if this helps or if I skipped any steps.

**Comment by bladey** [comment]
Thanks for your assistance @ebonow.

@Lord-Mendoza - 

In an effort to sustain the `react-select` project going forward, we're closing  issues that appear to have been resolved via community comments or issues that are now redundant based on their age.

However, if you feel this issue is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you, and we'll re-open it if necessary.

**Comment by SylvainGibert** [comment]
I found out actual solution for now with mixing previous solution provided by @ebonow and actual version of 
`react-select@5.7.0`

Putting `<Select loadOptions={loadOptions} />` doesn't works for me

So I just imported `import AsyncSelect from 'react-select/async';`

and used it like this 

```javascript
import AsyncSelect from 'react-select/async';

const loadOptions = (inputValue = '', callback) => {
  const needle = inputValue ? inputValue.toLowerCase() : '';

  const foundNeedle = (stack, fromBegin = false) =>
    fromBegin ? stack.toLowerCase().startsWith(needle) : stack.toLowerCase().includes(needle);

  const filterGroupAndOptionLabels = (groups) =>
    groups
      .map((group) => {
        if (foundNeedle(group.label, true)) {
          return group;
        }

        // If it doesn't match group label, filter options within group
        const groupOptions = group.options.filter((groupOption) =>
          foundNeedle(groupOption.label),
        );

        // If there are no matches, exclude group, else return new group with filtered options
        return !groupOptions.length ? null : { label: group.label, options: groupOptions };
      })
      .filter((x) => !!x); // filter out null groups

  const filteredOptions = options.length ? filterGroupAndOptionLabels(options) : [];

  callback(filteredOptions);
};


<AsyncSelect
  loadOptions={loadOptions}
  defaultOptions
  cacheOptions
/>
``` 

I also found that `group.label.props.textLabel` will be now `group.label` and implemented it above

Thanks again @ebonow and make this piece of code works forever 😎
