### ISSUE TITLE
Multi select dropdown items removed

### ISSUE THREAD

**Issue by RahulShahUI** [JedWatson/react-select#4005]
In MultiSelect, on selecting the dropdown menu items removing from menu and showing in selected lists

https://codesandbox.io/s/8qw3p?module=/example.js&file=/example.js

can we keep the selected items in dropdown menu itself and show selected.

can we keep Ocean in dropdown menu even it's selected.

![image](https://user-images.githubusercontent.com/38944466/79102525-88101100-7d88-11ea-8e73-13325dc05790.png)

**Comment by Esskimo** [comment]
Try adding the `hideSelectedOptions={false}` prop - that way the selected item remains in the dropdown menu.

Edited code taken from the CodeSandbox example:

```javascript
import React from 'react';

import Select from 'react-select';
import { colourOptions } from './docs/data';

export default () => (
  <Select
    defaultValue={[colourOptions[2], colourOptions[3]]}
    isMulti
    name="colors"
    options={colourOptions}
    className="basic-multi-select"
    classNamePrefix="select"
    hideSelectedOptions={false}
  />
);
```

![image](https://user-images.githubusercontent.com/31285011/79803525-6b647200-8362-11ea-9eee-4bd40e6b18bd.png)

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing  issues that appear to have been resolved via community comments or issues that are now redundant based on their age.

However, if you feel this issue is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you, and re-open if necessary.
