### ISSUE TITLE
Typescript runtime error with 3.1.0 "TypeError: newProps is undefined"

### ISSUE THREAD

**Issue by varzaman** [JedWatson/react-select#4011]
I have minimal information right now, but I wanted to bring this to attention while I was gathering more information.

I haven't been able to reproduce this in codesandbox yet.

I'm running a React-Native-Web project on React-Native 0.57.30, React 16.6, and TypeScript 3.5.3.

I have been running React-Select 3.0.8 with no issues. After upgrading to React 3.1.0 I not receive an error every time I open up the dropdown in the app that is simply

```TypeError: newProps is undefined```

It looks like this is the location the error is happening from my bundle.js

In Select.js
```      (newArgs: any, lastArgs: any) => {
        const [newProps, newSelectValue] = (newArgs: [Props, OptionsType]);
        const [lastProps, lastSelectValue] = (lastArgs: [Props, OptionsType]);

        return isEqual(newSelectValue, lastSelectValue)
          && isEqual(newProps.inputValue, lastProps.inputValue)
          && isEqual(newProps.options, lastProps.options);
```

This causes a runtime error that makes our app unusable. 

It looks like to me that somehow newProps is undefined and so when tit goes to get the inputValue, that is when it errors out.

I'm not sure why I haven't been able to get a codesandbox of this with similar parameters as in our app, so that part would require some investigation on my part, but it seems like it should be able to be solved from erroring out with an undefined checker at the very least.

**Comment by ebonow** [comment]
Greetings @varzaman and apologies for the extremely late reply. Thank you for reporting this.

Upon closer review, the behavior you are describing seems to be consistent with another open issue: https://github.com/JedWatson/react-select/issues/3452

Please refer to the above issue and see if there is anything present there that could help you resolve your build issues. I will be closing this as a duplicate so please feel free to reply or add any extra questions or concerns there so that we can consolidate our support efforts.
