### ISSUE TITLE
[Discussion]- menuPosition `fixed` keep the its position while scrolling

### ISSUE THREAD

**Issue by huylocit14054** [JedWatson/react-select#4020]
What I needed in my app was when the screen height is not enough the menu list will pop up at the top of the controller. By researching, I figured out menuPosition=" fixed" is the answer.

As you may all know, when setting the`menuPosition` prop to fixed, the menu will always be fixed on the screen. By scrolling the menu list will follow your screen.

However, in my app, I need it to fix with the control container not the screen. So I use some library call [react-use](https://github.com/streamich/react-use) to trigger some hook on scrolling. And I figure out somethings really weird and interesting. By adding `useWindowScroll` hook to my component, and doing nothing, I can scroll while the menu list stays still. 

Here is my [code](https://codesandbox.io/s/compassionate-cookies-85j2n?file=/src/SelectWithScroll.js:71-86). 
The first select component is used without useWindowScroll hook.
The second select component is used with useWindowScroll hook.
You can try can scroll it.

So I really not know what really happened here. So I create this issue to ask about this. And may someone need anything same with me can have a solution

Sorry for my bad English and thank you for a great library.

**Comment by bladey** [comment]
Hello -

Thanks for reporting this issue.

This bug has been reported multiple times as per issue #4088.

A new master issue #4088 has since been created to keep track this this bug.

This new issue will exist as the source of truth going forward to investigate the issue, report findings, and implement a bug fix.

We'll take into account all the details above while investigating.

If you feel this issue has been wrongly closed as it isn't related to the new master issue #4088, please let us know and we'll take another look.

Thank you!
