### ISSUE TITLE
Other than hideSelectedOptions any other option to hide selected option from being displayed

### ISSUE THREAD

**Issue by askshinde** [JedWatson/react-select#4031]
I am using 2 multi select with menuIsOpen{true} , where the first select contains option value from DB and the second one is a blank select. What evere a user selects in first select menu option the selected value becomes option for the second select menu. Every thing works fine, I just want what ever option the user is selecting in first select menu it should not be visible to user because its already being showen in second select menu

**Comment by ebonow** [comment]
Greetings @askshinde , 

Let me make sure I understand what you are asking.

1. Select1 has several options... lets just say option1, option2, option3 
2. Select2 has no options and no value set

**Expected behavior**: When a user selects option1 from Select1 then,

1. Select2 has Option1 added as an option and is set as the value
2. Select1 has Option1 removed as an option and value

To achieve this, you need to remove the value and option from Select1 at the onChange handler.
Here is an example [codesandbox](https://codesandbox.io/s/react-select-include-exclude-selects-fo5uz) that appears to demonstrate the behavior you're looking for.

I'll close htis for now, but happy to review if you have other questions or concerns.
