### ISSUE TITLE
upgrading react-select version1.0.0-rc.10 to 3.1.0

### ISSUE THREAD

**Issue by ramankharche** [JedWatson/react-select#4059]
I am trying to upgrade react-select version from 1.0.0-rc.10 to 3.1.0. I'm getting following error

jquery.js?eedf:3869 Uncaught TypeError: Object(...) is not a function

My current react version is - 15.6.2

I want to upgrade react-select for the following reason:
 When user type in react-select(<Select> Component) there is a little delay i see in box(where i've used <Select> Component). The text in the box appears in little late (300ms ~ 500ms)

**Comment by JedWatson** [comment]
React-Select now requires React version `^16.8.0` which is why you're getting errors.

For better or worse, you'll either need to update your version of React, or stay with the version of react-select you're using (or at least, you could move off rc.10 to the latest version on the 1.x branch which is `1.3.0` but I'm not sure if that will solve the performance problem you're seeing.
