### ISSUE TITLE
Deprecate warning findDOMNode in StrictMode

### ISSUE THREAD

**Issue by dougg0k** [JedWatson/react-select#4068]
Hi,

The title.

```
Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of NodeResolver which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://fb.me/react-strict-mode-find-node
    in div (created by Context.Consumer)
    in EmotionCssPropInternal (created by MenuList)
    in MenuList (created by MenuPlacer)
    in ScrollBlock (created by MenuPlacer)
    in NodeResolver (created by ScrollCaptor)
    in ScrollCaptor (created by ScrollCaptorSwitch)
    in ScrollCaptorSwitch (created by MenuPlacer)
    in div (created by Context.Consumer)
    in EmotionCssPropInternal (created by Menu)
    in Menu (created by MenuPlacer)
    in MenuPlacer (created by Select)
    in div (created by Context.Consumer)
    in EmotionCssPropInternal (created by SelectContainer)
    in SelectContainer (created by Select)
    in Select (created by StateManager)
    in StateManager (created by Styled(StateManager))
    in Styled(StateManager) (at SelectStyled.tsx:83)
```

**Comment by dgwyer** [comment]
I'm seeing the same warning. There are several different types of these warnings popping up. It would be great if an update could be released to fix them.

**Comment by dougg0k** [comment]
Yes, that was only one case.

**Comment by bladey** [comment]
Hi both,

Thank you for the provided information above.

As you may be aware, this bug has been reported multiple times as per issue #4094. On behalf of the maintainers I apologise it's taken awhile to get to this.

A new master issue #4094 has since been created to help keep track of this bug going forward.

This new issue will exist as the source of truth going forward to investigate the issue, report findings, and implement a bug fix.

We'll take into account all the details above while investigating.

If you feel this issue has been wrongly closed as it isn't related to the new master issue #4094, please let us know and we'll take another look.

Again, thank you.

**Comment by diegoulloao** [comment]
Any solution for this? still happening in 2021

**Comment by Methuselah96** [comment]
@diegoulloao See https://github.com/JedWatson/react-select/issues/4456. It's still an issue, but only for animated components and we hope to fix it, but it's not the highest priority at the moment. Upvote that issue so we can know how many people are running into it.

**Comment by famenesesc** [comment]
Hi, It stills happening, thanks!!

**Comment by tgaeta** [comment]
Removing `animatedComponents` worked for me.

**Comment by timsun28** [comment]
Hi, I'm currently having the same issue when trying out the animated example from the docs. 
It seems that this issue has been fixed in [this pr](https://github.com/JedWatson/react-select/pull/4704), however the latest release was back in May 2021. 

When can we expect a new release so this issue is fixed?

**Comment by Methuselah96** [comment]
You can try out the beta version of v5 (`5.0.0-beta.1`). We hope to have a stable release of v5 within the next couple weeks.

**Comment by timsun28** [comment]
After updating to the beta version for now, I don't get the error message any more! 
Thank you, I will be looking forward to the stable release
