### ISSUE TITLE
clearIndicator is not showing

### ISSUE THREAD

**Issue by ImSolitude** [JedWatson/react-select#4076]
I am not sure if I am missing something but when using `isClearable={true}` the clear indicator is still not showing,

![error](https://user-images.githubusercontent.com/20565199/83945605-7bea8200-a814-11ea-8b7a-d19f1a83e92c.png)

**Comment by sumanta-ghosh** [comment]
I am also facing the same issue.

![image](https://user-images.githubusercontent.com/2699051/89147309-e0576280-d573-11ea-950e-e72f4e1633e1.png)

![image](https://user-images.githubusercontent.com/2699051/89147253-bbfb8600-d573-11ea-9c66-e9d365bf130b.png)

**Comment by Rall3n** [comment]
@sumanta-ghosh The `ClearIndicator` is for the purpose of clearing the selected value, not the search input.

**Comment by sumanta-ghosh** [comment]
@Rall3n but in the example it showing the clear icon when I type in the input box. 

![image](https://user-images.githubusercontent.com/2699051/89149918-2bc13f00-d57b-11ea-8f96-8550968bf325.png)

**Comment by sumanta-ghosh** [comment]
If I select any value from the list then it shows the clear button. When I focus and start typing then that clear button remains there and when I click on a clear button then search string removed and the clear button disappears.
Maybe that is a bug.

**Comment by Rall3n** [comment]
> @Rall3n but in the example it showing the clear icon when I type in the input box.

@sumanta-ghosh Because the `Select` component has an option selected. **If** it has a selected option, it will render the `ClearIndicator` component.

> If I select any value from the list then it shows the clear button. When I focus and start typing then that clear button remains there and when I click on a clear button then search string removed and the clear button disappears.
> Maybe that is a bug.

What you described is the **default** and **expected** behavior. It is not a bug.

I believe you misunderstand the `ClearIndicator` components purpose. It's for clearing the value of the `Select` component i.e. the selected options. The search input has nothing to do with it.
