### ISSUE TITLE
Bundling with BundleConfig fails because of syntax error in react-select

### ISSUE THREAD

**Issue by nickornotto** [JedWatson/react-select#4087]
Add a path to the `react-select` component in your js file:

`import Select from 'react-select';`

and it is enough to just add the above line.

Add bundle to `BundleConfig.cs` that contains the path to the js where `react-select` is imported eg.:

```
bundles.Add(new ScriptBundle("~/js/app.select")
                .Include("~/dist/js/app.select.js"));
```

Include the bundled file in your `razor`:

`@Scripts.Render("~/js/app.select")`

Take a look at the page source, click the url to the bundled file. It will display the error:

```
/* Minification failed. Returning unminified contents.
(1705,41-42): run-time error JS1013: Syntax error in regular expression: ,
 */
```

`react-select` v. 2.4.4

**Comment by ebonow** [comment]
Greetings @nickornotto , and sorry for the late follow up on this.

Can you please provide some more details regarding your setup? It sounds like you are attempting to include react-select in a ReactJS.NET environment. Is that correct? If so, what versions are you using for
- ReactJS.NET
- .Net framework 

There are several things that can cause this such as files ending in comments, files containing certain vendor prefixes (eg: `-webkit`), or even [instances of string interpolation](https://stackoverflow.com/questions/60431094/minification-failed-returning-unminified-contents-when-contain-template-literal). 

It's been awhile since I have compiled v2, but those imports don't seem accurate to me either, though I could be wrong.

**Comment by ebonow** [comment]
Greetings @nickornotto 

I wanted to verify that this was not an issue before closing this even without additional details. After some investigation, I assume this was being done with the vanilla configuration instead of with webpack/babel bundling.

To verify that react-select works with reactjs.net, I did the following:
- installed .net core 3.1
- created project folder 
- `dotnet new -i React.Template`
- `dotnet new reactnet-webpack`
- `npm install`
- `dotnet run`

It would seem that the reactjs.net template project includes an example to react-select already (v3.1) which can be downgraded to v2.4.4 in the package.json

<img width="739" alt="Screen Shot 2021-02-22 at 7 19 05 AM" src="https://user-images.githubusercontent.com/1007579/108729697-a59d2380-74df-11eb-8d19-faa910edb717.png">

If you have further questions feel free to reply to help you troubleshoot further, but this would appear to be a configuration issue rather than a react-select issue.
