### ISSUE TITLE
Fit contents in flex layout

### ISSUE THREAD

**Issue by artooras** [JedWatson/react-select#4089]
I have a very simple setup - a `display: flex` header with a logo on the left and a `react-select `on the right.

![image](https://user-images.githubusercontent.com/4358143/84619677-74933a80-aede-11ea-8794-ee25467c171d.png)

But, as you can see, `react-select` doesn't stretch to fit the value. I've tried a lot of options, but nothing seems to work. Does anyone have a solution?

[Here's the sandbox](https://codesandbox.io/s/funny-brattain-k9fmj?file=/src/App.js).

I have asked this question on [SO](https://stackoverflow.com/questions/62324546/react-select-to-stretch-to-fit-value) as well, with little traction...

**Comment by bladey** [comment]
Hi @artooras,

Have you tried to wrap the Select component with another styled div?

I've created an example here which expands the select width - https://codesandbox.io/s/dreamy-water-vbnht

**Comment by ebonow** [comment]
@artooras Hello again,

The styling I think you are looking for is based on the SingleValue. Since the default styling is set to `position: absolute`, it will not flex without some styling overrides.

I responded to a thread recently discussing [how to create an inline React-Select](https://github.com/JedWatson/react-select/issues/4008#issuecomment-635748900) (with a working sandbox [example](https://codesandbox.io/s/react-codesandboxer-example-dx04k)). While you would likely want to keep the Indicators and borders, it should fit as a proof of concept of flexing the width of the Select to fit the value.

Most notably, here is the styling used to enable this
```
/* Position value relative (instead of absolute) and remove transform and max-width */
.react-select .react-select__single-value {
  position: relative;
  transform: none;
  max-width: none;
}
```

**Comment by artooras** [comment]
Thanks @ebonow , I ended up using a version of your solution. I used `position: relative` on `singleValue`.

**Comment by ebonow** [comment]
I spent the weekend looking at different styling methods trying to break the old habits of using classNames everywhere. That said, this would likely be more the recommended way for anyone else in the future looking to solve a similar problem.

```
const styles = {
  singleValue: inlineCss => ({ ...inlineCss, position: 'relative' })
};

<Select styles={styles} ...>
```

In either case, glad it worked out.

**Comment by bladey** [comment]
Thanks @ebonow for your assistance!
