### ISSUE TITLE
Custom Options created multiple times?

### ISSUE THREAD

**Issue by JoeZman** [JedWatson/react-select#4100]
I display multiple cards on a page.  Each card has a Select that loads data from the network.  When the user clicks the Select (to open the menu), I load the data and create custom options.  I do this in the onMenuOpen callback.  This works fine as long as I make no additional state calls.  If I set state while the menu is open, my custom options are **recreated** again.  Can anyone suggest a better way to lazy load without having the user to type (filter)?

**Comment by ebonow** [comment]
@JoeZman 

It sounds like you have the following use-cases:
1. You have multiple Selects
2. Each requires some api data fetch that you don't want to call until the user has clicked/focused on a specific card/Select
3. You want to then apply some logic to that fetched data to create custom options

That said, you need to manage your state so it's only doing one data lookup. I recommend using onFocus as the trigger (instead of onMenuOpen) to fetch data as soon as the user indicated intent to use the control. You also need to be responsible for knowing whether you fetched data already or not which should be evident by checking that 1) you don't already have options and that 2) you are not already fetching them.

As a bonus, Select takes a isLoading prop which displays a loading indicator.

You could easily wrap this into your own component so you can pass in a data fetch and callback mapper that you pass into each. Untested so use at your own risk...

```
const DataFetchSelect = props => {
  const { fetcher, mapper } = props;

  const [ options, setOptions ] = useState([]);
  const [ isLoading, setIsLoading ] = useState(false);

  const fetchData = () => {
    setIsLoading(true);
    fetcher().then(data => {
      const mapped = mapper(data);
      setOptions(mapped);
      setIsLoading(false);
  }, [])

  const onFocus = () => !options.length && !isLoading && fetchData();

  return <Select options={options} isLoading={isLoading} onFocus={onFocus} />
}
``` 

Let me know if this satisfies your needs and if so, please consider closing this ticket to keep our issue log nice and tidy.
