### ISSUE TITLE
The problem of deleting the custom option

### ISSUE THREAD

**Issue by emin-karadag** [JedWatson/react-select#4104]
Hello there,
We use react-select in one of our projects.
However, we have a problem. When we write something that is not among the react-select options, we do not want it to be deleted and we want to save it. Currently, something that is not included in the react-select element is deleted automatically. We want the opposite. The value we write manually is not deleted and we can save it. We need this, how can we do it?
Thank you.

**Comment by ebonow** [comment]
Hello @emin-karadag ,

I am not sure I understand the problem you are trying to solve.

"Not among the react-select options"

Does this mean that you are trying to create a new option that is not in the list? If so, then I would recommend taking a look at the documentation for [CreatableSelect](https://react-select.com/creatable)

If this means that you want a new option to show up in the list, then you would need to ensure that you are adding it to the list of options you are providing the Select.

If I misunderstood, then please let me know what I am missing so I can help you resolve your issues.

**Comment by emin-karadag** [comment]
Hello @ebonow 
You are right I told a little complicated. Let me put it like this: We want the Combobox feature, not Dropdown.
Maybe it was a little more understandable.

**Comment by ebonow** [comment]
Combobox feature is essentially what the CreateableSelect is. It allows you to create a new option that doesn't exist in the list. However, since you are providing the options to the Select, so you need to add the new option to the list once it's been created (presumably with the `onCreateOption` prop.

Here is an example taken from the link I shared above. 

https://codesandbox.io/s/29ovm?module=/example.js

Does this solve what you are trying to accomplish?

**Comment by emin-karadag** [comment]
Hello @ebonow 
Sorry, the sample you submitted doesn't solve my problem.
"CreatetableSelect" was rejected for user experience.
We want the expression we wrote to remain in the Combobox without hitting the "Select" expression.
Also, when we click on an outside area, we do not want the expression we wrote to be deleted.

we want something exactly like the one below.
https://jquense.github.io/react-widgets/api/Combobox/

Is your support possible in this regard?
Thanks :)

**Comment by ebonow** [comment]
Combobox is a general UI concept, so just trying to understand your context.

It sounds like you want to retain the text input when the user leaves focus of the input. There are several different ways of achieving this but here's just one example I've written which also demonstrates selecting the text and keeps the [input visible and editable](https://codesandbox.io/s/react-select-editable-and-selectable-6nfdv).

This example will not retain the input onBlur if it is not a selected value because it can be confusing from a UX perspective that the input is not a valid entry. However, in the case that you would like to retain it, you can simply edit the `onInputChange` function by removing the conditional for the `input-blur` action.

Let me know if this fits your use case or is at least closer to what you are looking for.

**Comment by emin-karadag** [comment]
@ebonow 
I tried to apply what you said a bit, but unfortunately I was not very successful.
I don't want to use a new library.
Could you please share a sample code block about the transactions you mentioned in your previous message?

**Comment by ebonow** [comment]
@emin-karadag This is copied from the [code example I provided](https://codesandbox.io/s/react-select-editable-and-selectable-6nfdv?file=/src/App.js:508-704) and I will add comments to know which lines you can remove to keep the users input when they leave the input without selecting the value (as default behavior for the one I included will reset to last selected value).

There are two things you will need to do:
1) Make it a controlled input by maintaining the user's input and passing it through to the Select
2) Add some CSS to enforce opacity rules so the input text is not hidden when the user leaves the input


Step 1 - Create state for the inputValue and update it as the user types
```
  const [inputValue, setInputValue] = useState("");

  const onInputChange = (inputValue, { action }) => {
    // onBlur => setInputValue to last selected value
    // UNCOMMENT THE CONDITIONAL BELOW IF YOU WANT TO RESET THE INPUT TO LAST SELECTED VALUE
   /*
    if (action === "input-blur") {
      setInputValue(value ? value.label : "");
    }
   */

    // onInputChange => update inputValue
    else if (action === "input-change") {
      setInputValue(inputValue);
    }
  };

  const onChange = option => {
    setInputValue(option ? option.label : "");
  };

   return (
      <Select
        className="react-select--editable"
        classNamePrefix="react-select"
        inputValue={inputValue}
        onInputChange={onInputChange}
        onChange={onChange}
        controlShouldRenderValue={false} // Will set this to false since we want to only display the input
        ...
      />
)
```

Step 2 - Styling using the css classes added in the above props for className and classNamePrefix
```
.react-select--editable .react-select__input input {
  opacity: 1 !important;
}
```

If you have any troubles with this, please create a fork and paste the link so I can better understand what part isn't working for you.

**Comment by emin-karadag** [comment]
thank you for example :)

**Comment by ebonow** [comment]
@emin-karadag Glad I could help. Does this resolve your issue?

**Comment by bladey** [comment]
Thanks for your help @ebonow!

@emin-karadag if this doesn't solve it, please reopen the issue!
