### ISSUE TITLE
Paste from buffer on mobile devices

### ISSUE THREAD

**Issue by Komalov** [JedWatson/react-select#4106]
It's a bug or at least a very unexpected behavior when pasting values on mobile devices

I can make component to paste value only after 2 or more attempts
 
![paste react select](https://user-images.githubusercontent.com/26224268/86383273-208aa300-bc9f-11ea-8f75-e74ef1592b6b.gif)

Before it was suggesting to copy placeholder instead, so I made some tricks with styles
```
placeholder: provided => ({
    ...provided
    pointerEvents: 'none',
    userSelect: 'none',
    MozUserSelect: 'none',
    WebkitUserSelect: 'none',
    msUserSelect: 'none',
  })
```
But anyway there is a 2px wide input in select component now and it seems that something strange is going on with it.

It's reproducible on latest 3.1.0, but I have it since 2.4.4. I tried many different android/ios devices with different browsers, always the same.

Also, I haven't found no workaround on it so looking forward to fix it somehow

**Comment by Komalov** [comment]
Here is the small reproducible demo of what I said https://codesandbox.io/s/paste-on-mobile-rbncb?file=/src/App.js

If a long tap happened over the placeholder area we no longer have paste option. You can play with it to see this behavior is not stable

**Comment by Komalov** [comment]
Ok, I got that making input tag be as wide as the whole component does fix the problem. But I am unable to do that manually, because "input" key in custom styles object won't applied for input, it goes for div wrapper above it. Even taking such an input by id from css side gives no results

@bladey is there any possibility to change width for input tag from users side?

**Comment by ebonow** [comment]
Greetings @Komalov ,

I took a look at your use case, and you are correct. The context menu will not prompt you to paste unless the touch point is over the input element, which is difficult because as you stated earlier, the default input width is 2px. 

You can use the api styling on the Input to style it as you need to. However, the input within the Input component is wrapped in 2 divs, so you will need to target the selectors a bit more explicitly. 

Try this in your styles prop...
[Working Forked Codesandbox](https://codesandbox.io/s/react-select-paste-on-mobile-q51wl)

```js
input: (css) => ({
  ...css,
  /* expand the Input Component div */
  width: "100%",
  
  /* expand the Input Component child div */
  "> div": {
    width: "100%"
   },

  /* expand the Input Component input */
  input: {
    width: "100% !important",
    textAlign: "left"
  }
})
```

I'll mark this closed for now, but I can reopen this if you have any questions or issues with the implementation. Hope this is helpful and thanks for you patience.

**Comment by ShiiRochi** [comment]
> Greetings @Komalov ,
> 
> I took a look at your use case, and you are correct. The context menu will not prompt you to paste unless the touch point is over the input element, which is difficult because as you stated earlier, the default input width is 2px.
> 
> Ideally, you would want the width of the input to stretch the width of the container and you can use the api styling on the Input. However, the input within the Input component is wrapped in 2 divs, so you will need to target the selectors a bit more explicitly.
> 
> Try this in your styles prop... [Working Forked Codesandbox](https://codesandbox.io/s/react-select-paste-on-mobile-q51wl)
> 
> ```js
> input: (css) => ({
>   ...css,
>   /* expand the Input Component div */
>   width: "100%",
>   
>   /* expand the Input Component child div */
>   "> div": {
>     width: "100%"
>    },
> 
>   /* expand the Input Component input */
>   input: {
>     width: "100% !important",
>     textAlign: "left"
>   }
> })
> ```
> 
> I'll mark this closed for now, but I can reopen this if you have any questions or issues with the implementation. Hope this is helpful and thanks for you patience.

For `react-select@^5.7.2` the following snippet can be used:

```javascript
export const styles = {
    // I decided to leave it here
    placeholder: base => {
      return {
        ...base,
        pointerEvents: 'none',
        userSelect: 'none',
        MozUserSelect: 'none',
        WebkitUserSelect: 'none',
        msUserSelect: 'none'
      };
    },
    input: base => ({
      ...base,
      // expand input area to fill all the available area
      gridTemplateColumns: '0 minmax(min-content, 1fr)'
    })
};
```

**Comment by the-night-wing** [comment]
@ShiiRochi, thanks, your suggestion was really helpful. 

But in my case the input was jumping to a new line while there was still enough space:

![1](https://github.com/JedWatson/react-select/assets/45423106/73d31c49-7b2d-455d-b913-4e977104bc5c)
![2](https://github.com/JedWatson/react-select/assets/45423106/b99ef450-0fd6-4398-a7a7-259740faf8e5)

Such behavior is caused by `flex: wrap` on the parent and `flex: '1 1 auto'` on the `input` wrapper.
Adding `flex: '1 1'` alongside with `gridTemplateColumns: '0 minmax(min-content, 1fr)'` fixed this:

![3](https://github.com/JedWatson/react-select/assets/45423106/460acdef-b53f-4376-b4fa-74dfb90d6785)

If you want to control when the input gets wrapped - change `auto` to some value, f.e.: `flex: '1 1 30px'`:

Snippet:
```
export const styles = {
    input: base => ({
      ...base,
      // removes default 'flex-basis: auto' property
      flex: '1 1',
      // expand input area to fill all the available area
      gridTemplateColumns: '0 minmax(min-content, 1fr)'
    })
};
```
 
P.S. Really don't get why they don't make it default, because such behavior on mobile is clearly a bug
