### ISSUE TITLE
dropdown doesnt open when clicking a custom ValueContainer that was loaded with selected values

### ISSUE THREAD

**Issue by yarinsn** [JedWatson/react-select#4115]
issue is reproduced here:
https://codesandbox.io/s/react-select-custom-valuecontainer-with-values-issue-9bllj?file=/src/index.js

**Comment by ebonow** [comment]
[Value Container](https://react-select.com/components)
`Container responsible for loading the placeholder value and the input.`

Your example replaces the children of the Value Container with a string value but by removing the children, you have also removed the Input and Placeholder components which are used to handle focus and click events to open the menu.

If you click the IndicatorsContainer, you can see that the dropdown still operates.

What it appears you are trying to do is perhaps display a label within a multi select with a summary of the selected options.

If that is the case, you may want to instead try to use the MultiValue component and use the index prop to ensure you only render one value (otherwise it will render a MultiValue for each selected value). Here, I borrow the SingleValue component to get consistent styling with my other selects, but a div would be the same.

```

const MultiValue = (props) => {
  const { getValue, index, selectProps } = props;
  const { formatOptionLabel } = selectProps;

  const children =  {`${getValue().length} items selected`}
  // Only show one value, so use the 1st value (ie: index = 0)
  return (
    !index && <components.SingleValue {...props} children={children} />
  );
}
```

**Comment by yarinsn** [comment]
i guess what i found weird about the situation is that as long as i dont load the control with values, everything works fine.
but yeah, i understand that there is a correct way of achieving what i need. ill look into it. thanks!

**Comment by yarinsn** [comment]
okay so after fiddling with it, I ended up with this:

```
const MultiValue = (props) => {
  const { getValue, data, selectProps } = props;
  const { formatOptionLabel } = selectProps;

  const children = `${getValue().length} item(s) selected`;
  const index = getValue().indexOf(data);

  // Only show one value, so use the 1st value (index === 0 or !index)
  return (
    !index && <components.SingleValue {...props} children={children} />
  );
}
```

```index``` is not part of props, but ```data``` is. The function above runs every time an option is selected (but not only), and for every selected option separately, and ```data``` will always hold single selected value. 
The ```!index``` makes sure that the component will be rendered once.

**Comment by ebonow** [comment]
I guess I should ask what version of react-select you are using as the index prop is [a fairly recent addition.](https://github.com/JedWatson/react-select/releases/tag/react-select%403.0.8).  Your sandbox appears to be using version 2.12 so it's likely it wouldn't be accessible unless you upgraded. 
 
Admittedly, prior to version 3.08 I was using CSS to hide all the other multiValues. 
```
.react-select__multi-value + .react-select__multi-value {
  display: none;
}
```

In any case, glad it's all working for you.

**Comment by athammer** [comment]
Can confirm this is an issue on 2.4.3 as well. Did some quick testing and looks like this is still an issue even in the newest version. The problem I was trying to solve was not having any selected values show up in the value container but it seems when I set the value container it also makes it unclickable. Does anyone know if there another way to do this to avoid this issue? Thank you!
https://codesandbox.io/s/react-select-custom-valuecontainer-with-values-issue-7fozb?file=/src/index.js
