### ISSUE TITLE
Add button in row

### ISSUE THREAD

**Issue by MohsenEs** [JedWatson/react-select#4126]
for example 
![2020-07-15_11-27-42](https://user-images.githubusercontent.com/46873097/87513888-a559c180-c68e-11ea-8906-35d6ae8ab672.jpg)

**Comment by ebonow** [comment]
This is possible, but not without a bit of time. 

First, there are many ways a Tree can behave.  Are the "branches" also selectable? Your screenshot seems to imply that they are not and are simply collapsible. How does input in the search field impact your results? Does it filter the branches, the children of the branches or both?

Based on some assumptions from your screenshot, what I would do is create 3 custom components:
1. Write a custom `Group` component that has a toggle state and passes a method to toggle that state to the `GroupHeading` component. 

Some props to know for Group component:
- children is the array of options
- label is the group heading label
- Heading is the GroupHeading component itself

```
const Group = ({ children, label, Heading, ...props }) => {
  const [ collapsed, setCollapsed ] = useState(false);
  const toggle = setCollapsed(!collapsed);

  return (
    <div>
       <div className="group-heading" onClick={toggle}>{label}</div>
       {!collapsed && (
         <div>
            children.map((Option, index) => <Option key=`label_${index}` />
          </div>
       )}
    </div>
 )
}
```

You would need to add the styling for the arrow and group heading. You could also animate the collapsing toggle instead of hide/show.


The last thing for the buttons is that you need to create a custom Option component. Make sure you follow the guide and [pass in the innerRef](https://react-select.com/components#inner-ref) but again something I imagine like 
```
const Option = <div>{label}<span className="option-actions><button children="add" /><button children="edit" /><button children="delete" /></span></div>;
```

The above is pseudo code and likely wouldn't work out of the gate, so I recommend following the example for a custom Option component to get you the last part.

Hope this is a good start and let me know if there are any questions.

**Comment by MohsenEs** [comment]
I do not mean tree at the moment, for now I just want to show the edit and delete buttons when the mouse moves on options. Is there a code for the sample?

**Comment by ebonow** [comment]
Here is the [example code sandbox](https://codesandbox.io/s/gx78i?module=/example.js) for creating a custom Option component. You could always fork/edit it and console.log the props sent to the Option component that you have access to. I'll try to walk through the basics here for what you're trying to do, but feel free to reference the above to help your development.

In your case, you want to display an Option that has buttons that display when the option is focused. To do this, we need to override the normal Option component that gets rendered. So we create a new Option to replace the one react-select uses. Since we only want the buttons to show when the option is focused, we need to also look at the other props passed to the Option component, specifically one called `isFocused `.

To address the styling easily, we can use custom styles and in this case, display: 'flex' and justifyContent: 'space-between' is likely what we're looking for.

Now for the actions. You would need to apply onClick events to each button, but you also need to make sure the onClick of these doesn't trigger the select. To avoid this, we can pass in an empty onClick to the option component so that it overrides the default behavior (at least in theory, haven't tested it but appears to check out ok looking at source code). We can then apply the selectOption method only when they click the label and apply the option data (provided by the data prop).

Here should be enough to get you started.

```
import Select, { components } from 'react-select';

const optionAdd = option => {};
const optionEdit = option => {};
const optionDelete = option => {};

const Option = ({ children, ...props }) => {
  const { selectOption, selectProps, data } = props;
  const { optionAdd, optionEdit, optionDelete } = selectProps;

  const onClick ={
    option: () => {},
    label: () => selectOption(data),
    add: () => optionAdd(data),
    edit: ()=> optionEdit(data),
    delete: () => optionDelete(data)
  };

  return (
    <components.Option ...props onClick={onClick.option}>
      <span onClick={onClick.label}>{children}</span>
      {!!props.isFocused && (
      <span>
        <button onClick={onClick.add}>add</button>
        <button onClick={onClick.edit}>edit</button>
        <button onClick={onClick.delete}>delete</button>
      </span>
    )}
    </components.Option>
  )
}
const styles = {
  option: css => ({ ...css, display: 'flex', justifyContent: 'space-between' })
};


return <Select styles={styles} components={{ Option }}  />;
```

Note: if you want to make this more composable, you could define your methods for your buttons by passing them in as props directly into the `Select`. You would then be able to access them via the `selectProps` prop sent to your custom Option component. Please note that this could conflict with future functionality naming conflicts so apply your best judgement.

If you have further implementation questions, please ask but also it might be easier to help if you create a code sandbox so we can walk through it together to verify it works as intended.

**Comment by MohsenEs** [comment]
https://codesandbox.io/s/gracious-robinson-8llzq?file=/src/App.js

Error

**Comment by ebonow** [comment]
> https://codesandbox.io/s/gracious-robinson-8llzq?file=/src/App.js
> 
> Error

This link unfortunately takes me to an empty Sandbox. There's references to react-select but no code corresponding to it.

<img width="1344" alt="Screen Shot 2020-07-15 at 8 46 11 PM" src="https://user-images.githubusercontent.com/1007579/87617166-723e1f00-c6dc-11ea-9e4c-5b9a58042f4c.png">

**Comment by ebonow** [comment]
Here is a quick example using most of the code from above.
https://codesandbox.io/s/react-select-custom-option-gltc7?file=/example.js

It still doesn't handle clicks appropriately but it should be a good start.

**Comment by MohsenEs** [comment]
Thanks for exactly what I wanted

**Comment by bladey** [comment]
Thanks again for your help @ebonow, @MohsenEs if you still need assistance, please let me know and we'll reopen the issue.

**Comment by abhi-2020** [comment]
> You would need to apply onClick events to each button, but you also need to make sure the onClick of these doesn't trigger the select. To avoid this, we can pass in an empty onClick to the option component so that it overrides the default behavior (at least in theory, haven't tested it but appears to check out ok looking at source code)

@ebonow this is not working.
Here is the code https://codesandbox.io/s/vigorous-snyder-0207e?file=/src/index.js

**Comment by ebonow** [comment]
Greetings @abhi-2020 ,

You are correct. I dove a little deeper and later discovered that what causes the selection is not the onClick, but rather the innerProps which attaches event listeners instead for `onMouseDown` and `onTouchEnd` so the empty onClick handlers can be removed.

This can be circumvented entirely by removing the innerProps from the Option props.
```
const Option = ({ innerProps, ...props }) => {
```

Here is a fork of your sandbox demonstrating this:
https://codesandbox.io/s/react-select-option-remove-innerprops-8x34d

Let me know if this is what you were looking for and if not, then let me know how else I can help.,
