### ISSUE TITLE
how to keep create new option always selected by default in dropdown

### ISSUE THREAD

**Issue by kishan-tocca** [JedWatson/react-select#4135]
<CreatableSelect
            ref={r => (selectRef = r)}
            value={state.selectedOption}
            components={{ Option }}
            onChange={handleChange}
            options={state.options}
            isMulti
            getOptionLabel={option => option.label}
            getOptionValue={option => option.value}
            placeholder="Filter by location , name, company name, job title..."
            createOptionPosition="first"
            allowCreateWhileLoading={true}
            onKeyDown={onKeyDown}
            onCreateOption={handleCreate}
            isClearable
            menuIsOpen={state.dropDownOpen}
            onInputChange={handleInputChange}
            onFocus={focused}
            
        />

**Comment by ebonow** [comment]
Greetings @kishan-tocca ,

Were you able to resolve this? 

I am looking at your props, and if you want the created Option to appear in the dropdown as selected, you would need to ensure that the new option added to your `state.options` on your `handleCreate` method and you would also need to add the prop `hideSelectedOptions={false}` so that the selected option is visible in the menu.

Please let me know if it's not clear, not what you were asking, or if you have any other questions and if necessary I can reopen this and assist you. Thank you!
