### ISSUE TITLE
FR: Allow trigger options reload

### ISSUE THREAD

**Issue by simPod** [JedWatson/react-select#4160]
Hello I'm using Async select:

```ts
<AsyncSelect defaultOptions loadOptions={promiseOptions} />
```

Is there a way to trigger options reload? `promiseOptions` result is based on state value so when that value changes, I'd like to reload options. I have not found anything I could call to achieve it.

https://codesandbox.io/s/festive-lalande-li5nz?file=/example.js

**Comment by ebonow** [comment]
Greetings @simPod 

Thank you for reporting this and I agree it is a good FR. We currently have issue #1879 open which does provide a workaround, but likely will be reviewed so that we can provide a better mechanism through some kind of existing or new feature. Feel free to follow the above issue if you would like to receive updates on its progress. 

In the meanwhile, I will close this as a duplicate to help us continue to identify unique issues to work through.
