### ISSUE TITLE
React-Select should automatically supply aria-label default same as id

### ISSUE THREAD

**Issue by amandapouget** [JedWatson/react-select#4166]
As described here, with simple examples:
https://github.com/testing-library/dom-testing-library/issues/714

Per the referenced spec, label does not associate with "div" by id, unless "aria-label" or "aria-labelled-by" are supplied.

I propose that when aria-label is _not_ supplied by the caller, that it default to the same as `id`, so that the label and "pseudo input" div from react-select are associated as required by the spec.

**Comment by ebonow** [comment]
Greetings @amandapouget and apologies for the long delay in getting a response.

I responded to the thread included in the link above, but for context, it would appear that a label was being created with the intention of being applied to the Select. 

However, react-select does not generate any labels so this is a specific user implementation. 

When creating a label to be used for the Select, it's imperative to use the correct id for the `for` attribute and in this case, the `inputId` of the Select should be used instead of the `id`.

Hopefully this clears up the confusion and resolves any issues regarding HTML validation. I will close this issue now, but feel free to reply if this doesn't resolve your use case and we can continue the discussion or re-open this if necessary.
