### ISSUE TITLE
Show selected value in react-select on form edit

### ISSUE THREAD

**Issue by user09876090** [JedWatson/react-select#4188]
I am using react-select in a form. It's working fine on form submission but when I edit a record then I am trying to show the selected value as default value (ON EDIT). But I am getting nothing. below is the code
```
import Select from 'react-select'
```

```
    editDetails = (e) => {
         const editProduct = this.props.editDetails
         const detailsFromApi = this.props.detailsFromApi
         this.setState({ defaultVariant: detailsFromApi.defaultVariant})
    }
```
And in render  I have the following 

```
<Select
   isMulti
   options={this.state.options}
   defaultValue={this.state.defaultVariant}
   onChange = {(e) => this.onSelectVariantChange(e)}
   className="basic-multi-select col-md-7 p-0"
   classNamePrefix="select"
   required
 />
```
What am I missing?

**Comment by ebonow** [comment]
Greetings,

If I understand correctly, it sounds like you are trying to pre-populate the default selected value of the select based on some saved data. 

Is your `defaultVariant` populating as the fully formed option or just the value? 

Example:
```
const options = [
  { label: 'A', value: 1 },
  { label: 'B', value: 2 },
  { label: 'C', value: 3 },
];

// wrong
const defaultValue = 1

// better
const defaultValue =  { label: 'A', value: 1 };

// best
const defaultValue = options[0];
```

So my best guess would be that you need to find the desired option
``` 
const defaultValue = this.state.options.find(opt => opt.value ===  this.props.detailsFromApi.defaultVariant);
<Select defaultValue={defaultValue} ... />
```

Also note: If your options or default values are loading on the page async, then it's also possible Select is rendering before there is a set defaultValue, in which case you might need to change it to a controlled component and instead use `value` instead of `defaultValue`

**Comment by user09876090** [comment]
@ebonow The label was not set properly. Now it's working. Thank you!!
