### ISSUE TITLE
How to change order of components inside control

### ISSUE THREAD

**Issue by cseas** [JedWatson/react-select#4220]
Asking here because the [StackOverflow question on this](https://stackoverflow.com/questions/60281317/react-select-clear-and-dropdown-indicators-order) has been lying unanswered for months now.

The current order of components inside control is (left to right):
Input > Clear button > Indicator Separator > Dropdown Indicator

The order I'd like to achieve is (left to right):
Dropdown Indicator > Indicator Separator > Input > Clear button

I know the hacky way of doing it would be to just `display: none` the Indicator Separator and Dropdown Indicator and add my own custom components inside of control. But is there a way to shuffle the order of components in-built in the Control component?

**Comment by ebonow** [comment]
Greetings @cseas , 

The hierarchy of the components you mention are 
```
- Control 
-- ValueContainer
--- Input
-- IndicatorsContainer
--- Clear Indicator
--- Loading Indicator
--- IndicatorSeparator
--- Dropdown Indicator 
```

Since the Clear Indicator and Dropdown Indicator are in the same container, you would need to decide how to best separate and position them within the Select. Since the logic to render the `LoadingIndicator` and `ClearIndicator` are both tied to the internal state within the StateManager (which is not easily accessible from the custom component)*, it would likely be a good idea to leave those Indicators in the `IndicatorsContainer` instead of trying to recreate them as custom components. The better approach would be instead to filter out the `IndicatorSeparator` and `DropdownIndicator` (as they are mostly aesthetic), to remove these from the `IndicatorsContainer` and instead render them inside the `Control` next to the `ValueContainer`.


The new hierarchy would look something look this:
```
- Control 
-- DropDownIndicator
-- IndicatorSeparator
-- ValueContainer
--- Input
-- IndicatorsContainer
--- Clear Indicator
--- Loading Indicator
```

[Here is a working demo I was able to put together](https://codesandbox.io/s/react-select-indicator-containers-ir7u5?file=/example.js) that hopefully resolves your use case.

**Comment by cseas** [comment]
That worked perfectly. Thanks a lot!

**Comment by NageshKapate07** [comment]
Is there any way to fix position of ClearIndicator inside scrollable multi-select dropdown??
