### ISSUE TITLE
Multi-select text input Cut off on IE browser

### ISSUE THREAD

**Issue by smurfs2549** [JedWatson/react-select#4224]
![image](https://user-images.githubusercontent.com/8286468/94400549-e9436980-019b-11eb-8060-1df3a7caef4e.png)

Reproduce steps:
Type multiple uppercase letter
Browser: IE 11.

**Comment by marianayap** [comment]
@smurfs2549 hello! I'm wondering if someone is workin on the issue already? I'm interest on it

**Comment by Rall3n** [comment]
This is not an issue with `react-select`.

Instead the issue lies in the `react-input-autosize` package used as the `Input` component for the `Select` components.

**Comment by bladey** [comment]
Thanks for the assistance @Rall3n. @smurfs2549 or @marianayap if you think this is in fact related to `react-select` please let us know and we'll re-open the issue.

**Comment by smurfs2549** [comment]
@marianayap Sorry, I am also waiting someone work on the issue.

**Comment by ebonow** [comment]
Greetings and sorry this is still an issue for you @smurfs2549  and @marianayap,

Since `react-input-autosize` is a mono repo to support multi input for react-select, I think it's fair to re-open especially if we would like to tie up loose ends with IE11 support.

We are looking to replace the react-input-autosize component with a css only solution, but unfortunately support for IE11 will be dropped with version 5 with the introduction of this, so it's not likely to help.

Out of curiosity, have you had an opportunity to look into this and know why the styling isn't being calculated/set properly?

**Comment by dcousens** [comment]
Hi @smurfs2549,
I am marking this issue as stale as we have dropped support for IE11 in the newest major release of React Select
