### ISSUE TITLE
ClearIndicator's onClick overrides public blur() method

### ISSUE THREAD

**Issue by cseas** [JedWatson/react-select#4228]
I'm trying to blur the control field when the clear button is clicked but for some reason the clear button keeps overriding the blur method and brings control back into focus.

```tsx
export default () => {
  const selectRef = useRef(null);
  
  return (
    <Select
      ref={selectRef}
      onChange={selectRef.current.blur();}
      isClearable
      ...
    />
  );
};
```

As expected, the above code blur's the control field soon as we select an option from the list. But when we click on the Clear icon, the control field still remains focused even though the blur method gets called.

Is this a potential bug or is there some way to override what the onClick of the Clear button is doing?

[[Related StackOverflow discussion](https://stackoverflow.com/questions/64115992/how-to-override-clearindicators-onclick-to-blur-control-on-clear-in-react-selec)]

**Comment by ebonow** [comment]
Greetings @cseas 

It seems like this functionality is built into the clearIndicator as you can see [here](https://github.com/JedWatson/react-select/blob/5bee3f40e74c165117a6765588ae906f07ad76f9/packages/react-select/src/Select.js#L969)

```
  onClearIndicatorMouseDown = (event: MouseOrTouchEvent) => {
    // ignore mouse events that weren't triggered by the primary button
    if (event && event.type === 'mousedown' && event.button !== 0) {
      return;
    }
    this.clearValue();
    event.stopPropagation();
    this.openAfterFocus = false;
    if (event.type === 'touchend') {
      this.focusInput();
    } else {
      setTimeout(() => this.focusInput());
    }
  };
```

By replacing the `innerProps` passed to the ClearIndicator, you can circumvent this default behavior from being called with the focusInput and fortunately, `clearValue` is a common prop passed to the component so it is easy enough to replace this functionality.

Here is a working example with an `onClear` prop passed to the Select so that it can be accessed from the ClearIndicator component via the `selectProps` prop to blur when cleared.

https://codesandbox.io/s/react-select-custom-clearindicator-c8fxv?file=/example.js

**Comment by cseas** [comment]
@ebonow That seems to work well. Thanks! I'll close the issue.
