### ISSUE TITLE
How to create tree in select

### ISSUE THREAD

**Issue by MohsenEs** [JedWatson/react-select#4229]
How can I create a selection list like the image below?
Thank you for giving me a ready example
![2020-09-30_10-53-27](https://user-images.githubusercontent.com/46873097/94655609-ba4c0580-030b-11eb-9990-bbc931355da3.jpg)

**Comment by ebonow** [comment]
Greetings @MohsenEs ,

1. What would you expect the data shown above to be modeled or rather what would the array for your `options` prop look like?

2. Do you expect the parent nodes to be selectable, collapsible or both?
- What is the expected behavior of clicking on a parent node (for example, what would happen if the user clicks the option for `choice 6`?)

**Comment by MohsenEs** [comment]
Each of them has its own value, which we get by clicking on each of them. In fact, it is a selection list that shows us the tree using the json file that we can select any of them.

**Comment by ebonow** [comment]
> Each has its own value, which we get by clicking on each value. In fact, a selection list that shows us the tree using the json file that we can select each, we can select all items Even the parent

Yes, this is the nature of a select such that each option has its own value. The complexity with a tree is that there can be a relationship between the parent or sibling, or they can be distinct. 

I imagine you are looking for something similar to [this](https://ant.design/components/tree-select/) but the model has a few different options so I am trying to better understand exactly what you want to build.

From what I hear these are things you would likely need to allow the ability to select multiple options and potentially click collapsible areas...
```
closeMenuOnSelect={false}
isMulti={true}
```

To proceed further, can you please provide:
1) An example of JSON data 
2) Your transformation of it as a flat array of options

**Comment by MohsenEs** [comment]
exactly like this
https://ant.design/components/tree-select/

**Comment by ebonow** [comment]
@MohsenEs 

I don't mind working through issues with people and finding ways to help them solve their issues, but it is in good faith that they have put in some level of thought and work. I put in a fair amount of time diving into code and looking for workarounds with a library that the creator is not even around to ask questions regarding implementation details and feature roadmaps.

This is not your first post and not even your first time requesting this feature (https://github.com/JedWatson/react-select/issues/4168) which already borders on spamming. I also recall, the last time I helped you and asked you to create a code sandbox, you created one that didn't even have a react-select in the code (https://github.com/JedWatson/react-select/issues/4126)

I bring this up because it seems like you are ignoring my instructions and that you want someone else to do the hours of work for you. I am more interested in trying to encourage the community to develop and contribute. If you want help, please respond to what I am asking you, otherwise, I will move on.

I asked in my previous post (and will ask one more time) to share what the raw JSON data looks like and then what that should look like as an array of options for the Select.  Once the data is there, we can build the custom Options component to render as a Tree node (with whatever color theme you like).

So again, to proceed further, can you please provide:
1. Example JSON data for the Tree
2. Transformation of that data into an array that can be used by the `options` prop

**Comment by MohsenEs** [comment]
در ابتدا باید از شما بابت این رپوسیتوری  تشکر کنم.
در نوع خودش بهترین هست.
من خیلی دوست دارم بتونم در توسعه  react -select   به شما کمک کنم
ولی با توجه به این که من تازه شروع به کار کردم در حال حاضر نمیتوانم
اما بزودی به پیشرفت خودم در react  حتما این کار را انجام خواهم داد.

در واقع من ۳ امکان کاربردی نیاز داشتم 
۱- بتوانم عملیات crud  بر روی آیتم ها انجام بدم 
که خوشبختانه با کمک شما این مورد در کد (#4126) انجام شد  

۲- بتونم یه ایکون اضافه کنم که مودال باز بشه و عملایات اینسرت انجام بدم
میتونه این ایکون بجای آیکون clearable   باشه
اینو توی پست (#4169) مطرح کردم که هنوز موفق نشدم من او مشکل رو باز میکنم که این مورد اونجا حل بشه

۳- اما در رابطه با ساختار انتخاب درختی 
انتظار من از این ساختار این است که 
۱- با توجه به ساختار مثال برای شما ارسال کردم در صورتی که selectable آن فعال باشد قابلیت انتخاب داشته باشد
۲ - برای انتخاب هر گره ۲ حالت داشته باشد هم با انتخاب گره فقط نام ان گره نمایش داده شود و یا جمع بسته شود برای مثال : Authors => tittle1 => title2
در  نهایت id  گره انتخابی را ما استفاده میکنیم

۳ - امکان انتخاب چند گانه isMulti={true}

(Your transformation of it as a flat array of options to be passed into the options prop of the select)
متوجه این مورد نمیشم 
اگه نیاز هست بیشتر توضیح بدید لطفا


1222/5000
First of all, I have to thank you for this repository.
It is the best of its kind.
I would love to be able to help you develop react-select
But since I have just started working, I can not at the moment
But I will definitely do this as soon as I progress in react.

In fact, I needed 3 practical possibilities
1- I can perform crud operations on items
Fortunately, with your help, this was done in code (#4126)

2- I can add an icon to open the modal and perform insert operations
This icon can be a clearable icon instead
I mentioned this in the post (#4169) that I have not succeeded yet, I will open the problem so that this case can be solved there.
![90798698-84d4f500-e327-11ea-97db-178e103b627c](https://user-images.githubusercontent.com/46873097/98764525-3ba9b400-23f1-11eb-97d1-57a4bf9858d2.jpg)

3- But in relation to the tree selection structure
My expectation from this structure is that
1- According to the structure of the example, I sent it to you, if its selectable is active, it can be selected
2 - To select each node has 2 modes, either by selecting the node only the name of that node is displayed or closed together, for example: Authors => tittle1 => title2
Finally we use the selected node id


3- Ability to select multiple isMulti = {true}

(Your transformation of it as a flat array of options to be passed into the options prop of the select)
I do not understand this
Please explain more if needed

[jsonExample.txt](https://github.com/JedWatson/react-select/files/5521691/jsonExample.txt)

**Comment by quocdai92** [comment]
I have a sample [here](https://410r7.csb.app/). Hope this help

**Comment by MohsenEs** [comment]
Thankful
But if there is an arrow next to it that can be seen only the main root of the tree and only with that button we can reach the items below it.
It will be very good

**Comment by ebonow** [comment]
How to create tree?
**Create custom options**

How to create custom options? 
- convert json to a flat array (no nested subMenuList) so it is recognized as valid set of Options
- when creating this list of options, consider adding...
  - descendants
    - This would be the values of every recursive option nested below it
  - ancestors
    - This would be the recursive value of every parent leading back to root

So for example...
    - ie: 
```js 
     tree: { 
       a: {
         id: 1, 
         subMenuList: { 
           b: {
             id: 2 
             subMenuList: {
                c: { 
                  id: 3
                }
             }
           }
         }
      }
    }
```
This could be converted to
``` js
const options = [
  { label: 'a', value: 1, ancestors: [], descendants: [2,3] },
  { label: 'b', value: 2, ancestors: [1], descendants: [3] },
  { label: 'c', value: 3, ancestors: [1,2], descendants: [] },
];
```
As this would likely be good enough to determine the nesting and ordering based on the `ancestors` and `descendants` arrays

**Render custom option**
Override innerProps of the option onMouseDown/onTouchStart so the entire option does not select the option as you want to include special actions inside (like collapse)

**Style**
You can apply paddingLeft based on the number of ancestors to nest it
```jsx
const styles = (css, state) => ({ ...css, paddingLeft: `${(state.data.ancestors.length + 1) * 10}px` }) 
```

You could also likely add some pseudo element to show an arrow in front of it or simply add it to the custom option render method.

**Other**
Toggling options might be beneficial so you'd want to add a button and onTouch, add the descendants to an array. This could be done adding a state variable and expose the ability to toggle it via a prop in the Select

For example...
```jsx
const [ collapsedBranches, setCollapsedBranches ] = useState([]);

const toggleBranches = (branchValues) => { 
 // write custom function to determine to show or hide and set State 
}

const Option = props => {
  const { collapsedBranches, toggleCollapsedBranches } = props.selectProps;
  const ToggleButton = <button onMouseDown={() => toggleCollapsedBranches(props.data)}>+/-</button>
  return <components.Option {...props}><ToggleButton>{props.children}</components.Option>
}

const styles = (css, state) => ({ 
  ...css, 
  paddingLeft: `${(state.data.ancestors.length + 1) * 10}px` }),
  display: state.selectProps.collapsedBranches.includes(state.data.value) ? 'none' : 'block',
});

const TreeSelect = props => (
  <Select 
    styles={styles}
    collapsedBranched={collapsedBranches} 
    toggleBranches={toggleBranches} 
    {...otherProps} 
  />
)
```

I think there is plenty to go on from here, but again @MohsenEs, someone already created a codesandbox example for you and instead of adding the changes yourself and providing an example to share, you leave another request for someone else to pick up.

I don't know that this will be any different, but I will leave this answer here for anyone who is curious to do such a thing to give them some direction.

**Comment by Darkholme1** [comment]
I have an [async tree demo](https://codesandbox.io/s/great-nobel-ku4mx?file=/src/App.js), hope it helps

**Comment by ebonow** [comment]
@Darkholme1 That is awesome! Thank you for sharing!

**Comment by Lonli-Lokli** [comment]
@ebonow 
Is there any sample on how to move further with tree? And have also
1) multi selection via checkbox per tree item
2) ability to filter those values
3) virtualized drop-down for heavy list of options?

Or maybe some guidance
