### ISSUE TITLE
Add an examples folder/section to the repository/website

### ISSUE THREAD

**Issue by cseas** [JedWatson/react-select#4234]
It would be nice to have an examples section or folder somewhere that covers examples for common use cases. People often look for an "examples" folder in the repository when the documentation doesn't suffice for what they want to do.

A good example of this is adding a floating label to react-select for which multiple issues and StackOverflow questions have been raised with lots of different answers.

These unnecessary Issues and questions could be avoided with an examples section that covers the most common use cases. I'd be happy to add a floating label use case as the first example based on the discussion in #4221 

Good references:
- https://github.com/tannerlinsley/react-query/tree/master/examples
- https://github.com/vercel/next.js/tree/canary/examples

**Comment by ebonow** [comment]
Greetings @cseas ,

Part of the initiative for us to get Discussions up and running was to create an area for "Show and Tell" so we can provide examples. I agree there are a lot of deeply hidden features and tricks to building awesome stuff and have been compiling a list of the CodeSandboxes I've built over the past few months.

I think Floating Label is an excellent first example if you would like to share there. I think once we revisit the documentation (likely impending as we work towards version 4) it will be one of the areas that we could pull from.

What are your thoughts?

**Comment by ebonow** [comment]
Greetings, I have started a discussion [here](https://github.com/JedWatson/react-select/discussions/4341) to showcase examples. 

I have more examples to share, but I need to pull them together and put them in codesandboxes.

In any case, I believe this is a good start, and once we have a running list, I think we can begin to identify how this fits with the website. I'll mark this as closed so that we can continue to work through this "backlog" but feel free to contribute there in discussions.
