### ISSUE TITLE
Jump/Scroll to item when typing letters like in a default html select element.

### ISSUE THREAD

**Issue by receter** [JedWatson/react-select#4241]
When isSearchable=false react-select does nothing when I hit a letter key on the keyboard while the select is opened. A standard html select element does this.

**Comment by ebonow** [comment]
Greetings @receter 

I would argue this is likely because a standard HTML select element always "is searchable" whereas react-select intentionally gives the developer the option to toggle this behavior. 

Sounds like you would likely want to keep the isSearchable functionality, but hide the HTML input element. Is that accurate?

**Comment by receter** [comment]
> Sounds like you would likely want to keep the isSearchable functionality, but hide the HTML input element. Also Instead of filtering, you would rather scroll to the first matching word. Is that accurate?

Yes.

I use react-select as a replacement for all html selects in our interface. Initially I did search for a styleable select element and react-select seems like a solid choice. Recently someone pointed out that the cursor in the select does not always feel right. Eg. when tabing to the select it may seem like a text input. This is not a big issue but a little detail that may impact ux.

What I did is to disable the isSearchable attribute, which at first glance solved the problem. But then the checkout suddenly got a country select where people have to scroll to find their country and power users have no way to quickly select their country. Of course this was quickly fixed by enabling isSearchable again for this select.

I see two main points:

1. People disabling isSearchable unintentionally impair ux and accessibility
2. The name react-select cannot be used as a solid replacement for selects if you don't want the cursor

And another thing that just came to my mind: Even if the keyboard shortcut is working, big lists without isSearchable are still worse to use compared to default selects on phones. So if 2. is intended this should be addressed as well.

If 2. is not in the scope of react-select I think it's a good idea to highlight the drawbacks of disabling isSearchable in the docs.

What do you think?

**Comment by ebonow** [comment]
I agree with your assessment of the cursor. It is misleading and I can understand the root cause is likely because it tries to replicate a happy medium of Select and Autocomplete behavior. It is especially frustrating for users who want to edit the existing text.

For that purpose, I have an editable react-select that essentially removes the "Value" label in lieu of keeping the Input visible. Here is a [demo](https://codesandbox.io/s/react-select-editable-and-selectable-6nfdv)

Another approach you may want to consider is removing the "Value" label when the react-select has focus so there is no confusion. 

If you decided to go the route of recreating this as a Select which "searches" without filtering like a html select, it should certainly be possible. The premise would be probably along the lines of...
1. Create a state variable to save user input
```
const [ inputVal, setInputVal ] = useState('');
```
2. Use `filterOption` to essentially always return true so that none of the options are filtered out.
3. Add `onInputChange` to call `setInputVal` when action === 'input-change' || action === 'set-value'
4. Use 'isOptionSelected` to select the first option that begins with the input string.
```
const [options, setOptions] = useState([]);

const isOptionSelected = opt => 
  opt.value === (options.find(x => (x.label.toLowercase()).startsWith(inputVal.toLowercase()))?.value)
```
5. The most difficult part is scrolling the window. There is access to the menuRef from the StateManager but I find it unreliable as the StateManager wrappers for Createable and Async make the Select object inside it inconsistent. 

In one instance I found myself needing a bit more control over the scroll so I used a bit of dirty DOM querying to scroll to the top. This requires use of the classNamePrefix and there certainly are better ways to do this the "React way"...
```
const scrollSelectMenuToTop = (className) => {
    const selector = `${className} .react-select__menu-list`;
    const dropdown = document.querySelector(selector);
    dropdown && dropdown.scrollTo(0, 0);
}
```
6. Last and easiest, hide the Input with the styles prop so you always display the last selected value or the placeholder.


If you decide to try your hand at implementing this, I would be very interested in seeing a codesandbox to see how it turns out. If you decide to create one and hit some snags along the way, I would be happy to help as well.

Hope this is helpful and if there is any way I can further help, let me know.

**Comment by bladey** [comment]
Hi @receter, could you please let us know if @ebonow's reply has assisted you so we can close out this issue.

**Comment by ebonow** [comment]
@receter In an effort to sustain the react-select project going forward, we're closing old issues.

However, if you feel this issue is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!

**Comment by SamTreeline** [comment]
Can anyone help with getting this native html select functionality / behavior from react select ? @ebonow gave some small example on how to do this but I am not able to make this work. Would you be able to give a bit more info / elaborate on your example ?
