### ISSUE TITLE
Can I change the field value?

### ISSUE THREAD

**Issue by Dvakseno** [JedWatson/react-select#4242]
How to change value of native input? Select works well.
version: 3.0.8
![Screenshot_1](https://user-images.githubusercontent.com/16020717/95474305-a2205a00-098d-11eb-8c7d-31643f7ceaa5.png)

**Comment by ebonow** [comment]
Greetings @Dvakseno ,

The way react-select works is that the input is used to search for menu options. Once an option is selected, a "SingleValue" is created and positioned absolutely over the input, and the text input is wiped out and hidden.

If you would like to retain the input instead of displaying a SingleValue, [you can look at this example for some methods of doing so](https://codesandbox.io/s/react-select-editable-and-selectable-6nfdv).

If this resolves your issue, please feel free to close this ticket, but if not, let me know and I would be happy to assist further.

**Comment by bladey** [comment]
Thanks for the assistance @ebonow. @Dvakseno please let us know if you require further help.
