### ISSUE TITLE
Selected value doesn't update on options update

### ISSUE THREAD

**Issue by francescoatseedble** [JedWatson/react-select#4248]
If you select a value and then you change the options object, the selected value remains even if it's not available anymore in the options. I'll leave an example below:   
https://codesandbox.io/s/react-select-v3-sandbox-forked-t22y2?file=/example.js

**Comment by Rall3n** [comment]
By design.

Each selected option is its own object / reference to the original object. Changing the available options will never result in the selected value being removed / unavailable.

**Comment by francescoatseedble** [comment]
Thanks for the reply @Rall3n .
Any idea on how could I achieve this?

**Comment by dakur** [comment]
@francescoatseedble You can take control over `value` prop – that's what is selected. Its content is same as `options` prop, but it should pass down to select options which are currently selected. E.g.:

```js
const [options, updateOptions] = useState([]); // or null in case of single value select
render(
	<CreatableSelect
		// other props
		value={options}
		onChange={(newOptions) => {
			// you can manipulate with the options in here
			updateOptions(newOptions);
		}
	/>
);
```

It goes as follows:
- when option is selected, `onChange` prop listener is called and new options are passed as an argument
- now you can manipulate them
- and update your custom state with these new options
- state is updated -> component is rerendered, this options as passed through `value` prop down to select component

**Comment by ebonow** [comment]
> Thanks for the reply @Rall3n .
> Any idea on how could I achieve this?

Greetings,

react-hooks are another great solution for this.

``` JS
const [ value, setValue ] = useState();
const [ options, setOptions ] = useState([]);

useEffect(function verifyValueExistsInNewOptions() {
  if(value && options.length && !options.find(x => x.value === value.value) {
    setValue(null);
  }
}, [value, options]);

const onChange = option => setValue(option);

return <Select options={options} value={value} />
```

Since it appears you are still using class components, you could do the same using options and value in state. @dakur laid out how you could accomplish this and [here is a forked codesandbox](https://codesandbox.io/s/react-select-remove-value-on-updated-options-3ysft?file=/example.js) demonstrating the behavior he described with the code you had prepared. 

I hope this makes helps and please let us know if you have any other questions, and we can reopen this if so.

**Comment by starikcetin** [comment]
> By design.
> 
> Each selected option is its own object / reference to the original object. Changing the available options will never result in the selected value being removed / unavailable.

Then I suggest re-evaluating the design decisions.

**Comment by ebonow** [comment]
@starikcetin,

Always up for discussion if it makes sense which is exactly why we have a discussions section. I would be happy to engage in such a conversation so long as you are willing to:

1) support your suggestion
2) consider use cases and work arounds for those negatively impacted by your suggestion

**Comment by starikcetin** [comment]
> @starikcetin,
> 
> Always up for discussion if it makes sense which is exactly why we have a discussions section. I would be happy to engage in such a conversation so long as you are willing to:
> 
> 1. support your suggestion

The argument is simple: I just wrote 50+ lines of code just to invalidate the selected option when the options array changes. It doesn't look good, and it certainly doesn't feel good. This situation is about the internal state of the component and I should not be handling it from the outside. If the state becomes invalid, the component should respond and correct itself.

> 2. consider use cases and work arounds for those negatively impacted by the proposed alternative design decision

Providing a prop to toggle between the current behaviour and the proposed behaviour is always an option. Default it to current behaviour so it is opt-in and doesn't break for the current users. Noone gets negatively affected and everyone is happy.

**Comment by ebonow** [comment]
@starikcetin 

> The argument is simple: I just wrote 50+ lines of code just to invalidate the selected option when the options array changes. It doesn't look good, and it certainly doesn't feel good. This situation is about the internal state of the component and I should not be handling it from the outside. If the internal state becomes invalid, the component should react and correct itself.

I provided a code example above that manages to invalidate the selected value in 5 lines, so I would have to surmise that you either have extra complexity or are using a class component with a combination of `getDerivedStateFromProps` and `componentDidUpdate` - which is simply the nature of React pre-v16.8.

Regarding the internal state of the Select, both options and value are also props so it is not just a matter of internal state. 

For example, if a value is specified as a prop, then either...
1) Ignore the user specified value breaking the controlled input contract.
2) Skip validation if the value is a user specified prop breaking the validation contract.

Option 2 seems like the better of the two, but again this is extra complexity within the source code and additionally one more "gotcha" nuance.

AsyncSelect would not have a complete list of options and CreateableSelect may not have the option at all as the selected value so there are already two popular variants in which considerations would have to be made and there are likely other times that this would cause conflicts in the expected behavior.

> Providing a prop to toggle between the current behaviour and the proposed behaviour is always an option.

By last count, there are 64 available props (not including props on custom components). That's not to say that there shouldn't be more, but it should be with some thoughtful discussion about the value that adding a new prop which introduces new behavior and new complexities. 

The proposition here is to introduce an opt-in prop to assist some users to avoid having to manage differences in options and selected values on their own.

My counter argument to this suggestion is:
- It is achievable with hooks in 5 lines of code without impacting source code
- It is not a highly requested feature
- Behavior is dependent on controlled/uncontrolled
- Behavior is illogical for Async and Createable when values are not present in provided options
- A select DOM element maintains its selected value even when its options change
- It introduces complexity about source of truth and validation

I have even more questions about the approach in the implement you are discussing as you are likely to have some action which is triggering the new set of options to be passed. What is stopping you from filtering/clearing out the value in state based against the known set of values you are passing so that it can be done in the same render cycle? This would be more performant than having react-select creating an unnecessary prop quality check.

Based  on all the above, I would learn towards this simply not adding much value at best. Happy to look at your implementation to see if it can be simplified and even discuss this further, but the arguments for convenience should be weighed against side effects and expectations.
