### ISSUE TITLE
Issues with RTL i.e icon on left with ltr support

### ISSUE THREAD

**Issue by techlabz** [JedWatson/react-select#4261]
Many modern search bars have the the search bar icon on the left hand side and type from left to right, I don't see this functionality here. In other words how to achieve this as rtl gets the icon on the left but you types RTL

**Comment by ebonow** [comment]
Greetings @techlabz,

One way to achieve this is use a custom Control component to reverse the display order of its children passed so that the IndicatorsContainer precedes the ValueContainer. 

In regards to the styling, only two inline style overrides are necessary (ValueContainer -> flowDirection: 'row-reverse', Option -> textAlign: 'right'). 

Here is a codesandbox I put together. I hope it is helpful and please let me know if anything is out of place or incorrect as I do not have a lot of experience working with RTL language support.

https://codesandbox.io/s/react-select-indicator-container-rtl-piehk?file=/example.js

**Comment by ebonow** [comment]
@techlabz I hope this answered your inquiry. If not, please reply so we can provide further assistance.
