### ISSUE TITLE
react-select capture click outside event on mobile devices

### ISSUE THREAD

**Issue by OlegKozlovskui** [JedWatson/react-select#4270]
In my app I am using click outside functionality, I have some component and when I click outside this component should be closed. On the desktop version, everything works fine but on the mobile, this component does not hide only in case when click outside is being happened and the target is Select component. From what I see the react-select library has some specific behavior with touch events and this is a reason for the current issue. 

**Product version**
v3.1.0(react-select)

**Comment by ebonow** [comment]
Greetings @OlegKozlovskui ,

I am not able to reproduce the error you are describing. 
Can you please create a sample codesandbox with your code? [You can fork on this one to get started.](https://codesandbox.io/s/epic-einstein-bdqby?file=/src/App.js)

**Comment by ebonow** [comment]
Greetings, I will be closing this ticket due to inactivity. You may want to include a touchEnd event handler around the select to ensure any touchdown events don't leak outside. You can also consider using event.composedPath to properly evaluate the DOM hierarchy to see if it was a click outside.

Please feel free to follow up if there are any further concerns or issues and we can reopen if necessary.
