### ISSUE TITLE
How to use react-select v3 in browser (Will v3 support standalone)?

### ISSUE THREAD

**Issue by hi-hai** [JedWatson/react-select#4286]
I am a bit confused on how to use react-select in browswer. The library list from https://cdnjs.com/libraries/react-select has the 1st one https://cdnjs.cloudflare.com/ajax/libs/react-select/3.1.0/react-select.cjs.js, but when I use 
```
<script src="https://cdnjs.cloudflare.com/ajax/libs/react-select/3.1.0/react-select.cjs.js" integrity="sha512-tXjEPfcs3+8ODA7pVDfd6mZCGXybtuecI8CQkIJOYid0GGEyW8MbK0o8UclNbNLTowh78PRCMh1kPw+7bKXQUQ==" crossorigin="anonymous"></script>
<script type="text/babel">
	ReactDOM.render(
		<Select ***** />,
		document.getElementById( 'root' )
	);
</script>
```
in a HTML, it gave error 
```
react-select.cjs.js:3 Uncaught ReferenceError: process is not defined
    at react-select.cjs.js:3
```

To write an individual app, can use `import Select from 'react-select'`, but in my case, it is just partial of one HTML page. In other words, I want to use react as a part of my HTML page.

Tried google but no luck. Didn't see any example either. Only clue is I may need to load the dependences in v2 https://stackoverflow.com/questions/53927307/how-to-import-from-react-select-cdn-with-react-and-babel . For the v3 question, https://stackoverflow.com/questions/62842565/is-it-possible-to-use-react-select-in-the-browser-from-the-cdn no answer yet. My question is similar to that v3 one.

TIA.

**Comment by marko-hologram** [comment]
@hi-hai Did you try any of the other available scripts in that cdnjs url? I see few of them with "browser" in their name, maybe those could work?

The one you are trying to use is just referencing prod/dev scripts depending on the Node environment so it cannot work in browser.
___

If that doesn't work, I still have something to say, but you can ignore this part since it's not really related to react-select not working in browsers.

Even if you are going to use this in a single page (together with React), it's probably better to still bundle that JS using Webpack/Parcel/Rollup. Parcel can probably get you going super fast with React, but if you are more comfortable with Webpack then go for that.

I know that's not ideal, but neither is loading these libraries directly with `<script>` tags. If this is something you only wanted to test for fun then fine, but using it all like this in production should be avoided in general.

**Comment by ebonow** [comment]
Greetings and thanks for your question.

V3 dropped UMD support so it will be challenging for you use this library outside of the build process. There are people that have varying levels of success and I believe standalone support is a valid feature request which we will be tracking here: https://github.com/JedWatson/react-select/issues/4120

I will close this issue to ensure we are tracking it in one place but feel free to work through any support as it will likely help others trying to do the same and there may be other closed issues that could offer guidance as well.
