### ISSUE TITLE
A component is changing a controlled input to be uncontrolled

### ISSUE THREAD

**Issue by ochov1** [JedWatson/react-select#4304]
Hi 
I have this component. 

<AsyncSelect

                    isSearchable="true"
                    isClearable = "true"
                    classNamePrefix="select"
                    placeholder = "start typing to search your direction"
                    debounceInterval={500}
                    loadOptions={this.handleInputChange}
                    autoFocus
                    name="address"
/>

is working correctly until I select something, when is throwing an error. 

**react_devtools_backend.js:2430 Warning: A component is changing a controlled input to be uncontrolled. This is likely caused by the value changing from a defined to undefined, which should not happen. Decide between using a controlled or uncontrolled input element for the lifetime of the component**

The hidden field will be empty so when I submit the form, I receive empty.

thank you.

**Comment by marianayap** [comment]
@ochov1 hey! is there a chance I can work on the issue?

**Comment by ebonow** [comment]
Greetings @ochov1 

This does not occur during any of the existing async select examples. I have even created a [codesandbox based on the basic async select using your props](https://codesandbox.io/s/react-select-async-uncontrolled-2nzq0?file=/example.js), and am not seeing the console warning, though this example has both `loadOptions` and `onInputChange` whereas yours only has loadOptions but uses a function called handleInputChange.

Some questions to look at:
- What does handleInputChange do?
- Do you have any other forms with the name "address"?
- What other props are you passing into the component? Is `value` one of them?

**Comment by ochov1** [comment]
Hi @ebonow.

Thank you for your answer.

I paste here my code
  
```
  handleInputChange  (inputValue) {
                    return  axios.get("/api/maps?page=1&search="+inputValue,{
                        headers:{
                            "Content-Type": "application/json",
                            accept: "application/json"

                        }
                    }).then(response => response.data)


            }

```

**Comment by ebonow** [comment]
@marianayap Happy to have you assist. It's likely this is not a library issue, but still glad to have our community helping each other work through similar issues.

@ochov1 
You could pass in the value as a prop and treat the Select as a controlled component, though it may not be necessary for your use-case.

ie: 
```
const [ value, setValue ] = useState({});
const onChange = option => setValue(option);

<AsyncSelect value={value} onChange={onChange} ... />
```

It might be helpful to try to reduce the complexity by using some hard coded data for the options and use a Select instead.
```
options = [
  { label: '123 Sesame St, Rogers, WA', value: 123 },
];

<Select 
  isSearchable={true}
  isClearable = {true}
  classNamePrefix="select"
  placeholder = "start typing to search your direction"
  autoFocus
  name="address"
  options={options}
/>
```

If you select the option and you are still receiving that console warning, then you can begin to dig a bit deeper into your form and inputs.

I do recall getting similar warnings when I was using a controlled Checkbox component and the state was initially set as null or undefined instead of false. I would suspect something similar is going on somewhere in your app.

**Comment by ebonow** [comment]
We will be closing this to focus on remaining react-select issues as this does not appear to be an issue with the library itself. If you wish to provide a codesandbox demonstrating the behavior, someone we may able to provide more direction on next steps and we can re-open this issue if necessary.
