### ISSUE TITLE
Showing selected option on top view

### ISSUE THREAD

**Issue by hyphen1370** [JedWatson/react-select#4305]
Hello, 

I am using the latest version of react-select. I am seeing default behavior to show the selected option at the buttom  of the menu view like this
![image](https://user-images.githubusercontent.com/3792453/100820460-1cf07900-3403-11eb-9919-33cf8697e4b1.png)

Is there any way to change so that when the menu is open, "Cape Verde" shows where the "Brunei Darussalam" shows in the picture? 

Thanks

**Comment by ebonow** [comment]
You can add an `onMenuOpen` prop and automatically scroll the focused option to the top. 

``` JS
  const selectRef = useRef();

  const onMenuOpen = () => {
    setTimeout(() => {
      const { focusedOptionRef } = selectRef.current.select;
      focusedOptionRef && focusedOptionRef.scrollIntoView();
     }, 1);
  };

  return <Select ref={selectRef} onMenuOption={onMenuOption} />
```

Demo: [codesandbox](https://codesandbox.io/s/react-select-option-generator-uqfqj?file=/src/App.js)

A couple notes about this...
- It's a known issue that the focusMenuRef and menuListRef are not immediately available at the time of onMenuOpen, so you will need a brief setTimeout to add it to the event queue to be called after render. https://github.com/JedWatson/react-select/issues/4243

- There can be a sudden jump in the changing of it being moved to the top, so there maybe a possibility of adjusting the opacity/visibility before and after it happens if you want by accessing the `selectRef.current.select.menuListRef`.

In any case, this should resolve your use case. If you have any further questions, happy to discuss.

**Comment by gino** [comment]
Is there already better recommended way to achieve this? I would also like to display the selected item as the first option, isn't there a way to invoke the `scrollIntoView` function that is being used under the hood?

```ts
scrollIntoView({ block: "start", inline: "start" })
```

**Comment by Devalekarthik** [comment]
Is there any way to stop sudden jump in the changing of it being moved to the top..?
