### ISSUE TITLE
Remember scrollbar position after view rendered

### ISSUE THREAD

**Issue by lengockyquang** [JedWatson/react-select#4318]
Hi, I am using react-select version 2.4.4.
Here's the position of scrollbar when select value "2005"
![screenshot_1607331474](https://user-images.githubusercontent.com/45225905/101330878-bc9b8480-38a5-11eb-902b-f450a8f3d747.png)

But after reselect the input, position of scrollbar had changed
![screenshot_1607331513](https://user-images.githubusercontent.com/45225905/101330891-c1f8cf00-38a5-11eb-9e1d-1190947c3740.png)

Are there any option to remember position of scrollbar? Thanks

**Comment by ebonow** [comment]
Greetings @lengockyquang ,

The default support is to automatically focus the selected option in the Menu as the bottom most option in the menu. There are other issues related to this asking for more support about where the selected option displays in the menu... 
https://github.com/JedWatson/react-select/issues/3822
https://github.com/JedWatson/react-select/issues/4305

In regards to why it simply doesn't remember scroll position, I can hypothesize that one reason is likely because the options list can change making the scroll position irrelevant to the selected option.

If you wanted to remember the scroll position, you could add a scroll listener to the MenuList and onMenuOpen, scroll to that position.

``` JS 
const MenuList = (props) => {
  const { children, className, cx, getStyles, isMulti, innerRef, selectProps } = props;
  return (
    <div
      css={getStyles('menuList', props)}
      className={cx(
        {
          'menu-list': true,
          'menu-list--is-multi': isMulti,
        },
        className
      )}
      ref={innerRef}
      onScroll={selectProps.onMenuScroll}
    >
      {children}
    </div>
  );
};

const MySelect = props => {
  const selectRef = useRef();
  const [scrollPosition, setScrollPosition ] = useState();
  const onMenuScroll = e => // setScrollPosition here. Probably want to use debounce...

  onMenuOpen = () => {
    // scroll `selectRef.current.select.menuListRef` to scrollPosition
    // this will need to happen on setTimeout as its a known issues as of now 
    // that menuListRef is null at time of this evocation 
    // https://github.com/JedWatson/react-select/issues/4243
  }

  return <Select ref={selectRef} components={{MenuList}} onMenuOpen={onMenuOpen} onMenuScroll={onMenuScroll} />
``` 

This should be enough to get you started. I can reopen this if necessary, and feel free to reply if you have any questions.
