### ISSUE TITLE
AsyncCreatableSelect does not show values with Formik

### ISSUE THREAD

**Issue by flora8984461** [JedWatson/react-select#4321]
I am using Formik, and I have checked with <Select>, it works fine. But here when using AsyncCreatableSelect, when I make a selection, my Formik shows form value, but react-select does not. It seems to be the different behaviour in AsyncCreatableSelect and Select. If I change "opt.value" to "opt", it shows the name in the selection, but that's not working with "clear" action and it not what I want to show in the form field. 

Here is a Demo:
https://codesandbox.io/s/formik-codesandbox-template-forked-cte9o?file=/TestComponent.js

Any help is appreciated. Thanks!

**Comment by flora8984461** [comment]
I have no idea why my markdown format are missing... Sorry for the mess

**Comment by Rall3n** [comment]
@flora8984461 Every `Select` component (be it normal, `Creatable`, `Async` or the combination) expects the `value` prop to be of same shape as the options, meaning an object in the shape of `{ value, label }` (by default).

The label is used for displaying the selected value in the `Select` component.
The value is used to highlight the selected option in the available options list.

-----

You could turn your value into an object:
```jsx
const { value } = props.field;

<Select value={value ? { label: value, value } : null} />
```
This would both show the option in the component and highlight it in the list, but this would require the label and the value to be the same, which in most cases it is not.

**Comment by ebonow** [comment]
> I have no idea why my markdown format are missing... Sorry for the mess

Sorry, I tried to fix it, but yeah, I see what you mean. The markup is completely borked for your comment for some reason. 

But +1 to everything @Rall3n said. I hope this answers your question.

**Comment by flora8984461** [comment]
> @flora8984461 Every `Select` component (be it normal, `Creatable`, `Async` or the combination) expects the `value` prop to be of same shape as the options, meaning an object in the shape of `{ value, label }` (by default).
> 
> The label is used for displaying the selected value in the `Select` component.
> The value is used to highlight the selected option in the available options list.
> 
> You could turn your value into an object:
> 
> ```js-jsx
> const { value } = props.field;
> 
> <Select value={value ? { label: value, value } : null} />
> ```
> 
> This would both show the option in the component and highlight it in the list, but this would require the label and the value to be the same, which in most cases it is not.

@ebonow @Rall3n 

Thank you so much for your help. I had another deep look into this, and I found: 

I thought <Select /> behaves differently is because I have checked this [issue](https://stackoverflow.com/questions/58502707/react-select-with-formik-not-updating-select-field-but-does-everything-else) and the sandbox for it is https://codesandbox.io/s/react-select-formik-jet92?file=/src/Form.jsx. 

In this example, they are not using <Field /> from Formik which makes it behaves differently and can use   `setFieldValue("fieldname", opt.value)` and the clear works fine.


## Then I made an updated sandbox of mine:
Without Field:  https://codesandbox.io/s/formik-asynccreatableselect-3-h3t1o?file=/TestComponent.js
With Field: https://codesandbox.io/s/formik-asynccreatableselect-1-cte9o?file=/TestComponent.js


...................

Though I have no idea why using a Field or not makes this difference... 🤔 But it's a kinda ugly workaround for myself.

Thanks! 

Sorry again my markdown is still not working... 😥

I'm trying to use a screenshot so that you can see it better.

![Capture](https://user-images.githubusercontent.com/39588094/101562788-14b1b400-3996-11eb-805c-cd3c50dfa42d.PNG)

**Comment by ebonow** [comment]
Recopying @flora8984461 's reply to get better Markup support:

Thank you so much for your help. I had another deep look into this, and I found:

I thought behaves differently is because I have checked this [issue](https://stackoverflow.com/questions/58502707/react-select-with-formik-not-updating-select-field-but-does-everything-else) and [the sandbox for it](https://codesandbox.io/s/react-select-formik-jet92?file=/src/Form.jsx). 

In this example, they are not using from Formik which makes it behaves differently and can use 
`setFieldValue("fieldname", opt.value)` and the clear works fine. I did not notice they are not using . 

Then I made an updated sandbox of mine: 
111. Without Field: https://codesandbox.io/s/formik-asynccreatableselect-3-h3t1o?file=/TestComponent.js 
222. With Field: https://codesandbox.io/s/formik-asynccreatableselect-1-cte9o?file=/TestComponent.js 

Though I have no idea why using a Field or not makes this difference... 🤔 But it's a kinda ugly workaround for myself. Thanks! Sorry again my markdown is still not working... 😥 I'm trying to use a screenshot so that you can see it better. Seems my image cannot be updated as well....

**Comment by ebonow** [comment]
@flora8984461 Your examples seem fine from what I can tell.I do not have a lot of experience with Formik so not sure if I am missing something. 

Is there something missing or wrong with either implementation that you are asking for help with?

**Comment by flora8984461** [comment]
> @flora8984461 Your examples seem fine from what I can tell.I do not have a lot of experience with Formik so not sure if I am missing something.
> 
> Is there something missing or wrong with either implementation that you are asking for help with?

Thank you so much. 

Yeah I think I kinda fixed it. Just put my code sandbox here in case someone else comes into the similar issue.

**Comment by ebonow** [comment]
Awesome! Glad you got everything working!
