### ISSUE TITLE
Select doesn't play well with MUI FormControl/InputLabel

### ISSUE THREAD

**Issue by Ploppz** [JedWatson/react-select#4323]
https://codesandbox.io/s/codesandboxer-example-forked-4owo3?file=/example.js

Without marginTop: 50 in `styles.container`, the InputLabel is not shown.

**Comment by Rall3n** [comment]
@Ploppz That is how the Material-UI `InputLabel` component works. 

It is designed to be used as a floating label, so it has to be positioned relatively to the container of the input element to support this.

-----

If you don´t need to use the floating label feature, you could change the style of the component as follows:
```jsx
<InputLabel style={{ position: 'static', transform: 'none' }}>Label</InputLabel>
```

**Comment by ebonow** [comment]
As @Rall3n said, `InputLabel` is positioned 'absolute' to the top let, so this should be expected behavior. 

<img width="917" alt="Screen Shot 2020-12-10 at 9 16 16 AM" src="https://user-images.githubusercontent.com/1007579/101805789-c953ee80-3ad8-11eb-9f4c-bc669cf6fea4.png">

I'll close this issue now as it does not pertain to any defective aspect about react-select, but as a side note, getting MUI TextInput to play nice with react-select is on my long running to-do list.

**Comment by Ploppz** [comment]
Thanks!
