### ISSUE TITLE
Custom Component Props

### ISSUE THREAD

**Issue by DarkPurple141** [JedWatson/react-select#4337]
# Feature Request

Hi there, as part of an internal bug triage related to this behaviour:

https://www.loom.com/share/8ea0b2115af1478b9bea8f8c5f2ba2e7

^ Focus being retained incorrectly if a user provides a custom component which is declared inline.

The workaround for this is to not inline the component and declare it outside the `Select`'s JSX. However, this also prevents the user from accessing props that may be needed by the custom component.

For example:

```
const SpecialOption = ({ ...supportedProps, mySpecialAnalyticsHandler }) => {
  // how to access mySpecialAnalyticsHandler?
  return <div {....supportedProps} />
}

<Select
  component= {{  Option: SpecialOption }}
/>
```

## What do I suggest?

Some way to inject additional props to Select children.

**Comment by ebonow** [comment]
Greetings @DarkPurple141 ,

The source of this unexpected behavior you are referencing inside of the video is due to the way these components are being created. 

As you have identified above declarations inline with the Select, causes the components to mount and remount with every render of the select. A better practice would be to declare the components outside of the same render method of the Select component.
```js
const Option = ({ children, ...props }) => (
  <components.Option {...props}>
    <Colorbox color={children}>{children}
  </components.Option>
);

return <Select component={{ Option }} {...otherProps} />
```

Also before I get to your question, in regards to the video and your specific use-case, there is a prop called `formatOptionLabel` which renders the children prop of the Option and SingleValue/MultiValue. There is an additional context prop passed in that can be used to disseminate between the two (menu or value), but since you are rendering them the same, it wouldn't be needed here.
```js
const formatOptionLabel = ({ label }) => <><Colorbox color={label}>{label}</>;

return <Select formatOptionLabel={formatOptionLabel} {...otherProps} />
```

Finally, there is already a mechanism built in to inject additional props to Select children components.
`selectProps` exists in the props for every component. In regards to your example above...

```js
const mySpecialAnalyticsHandler = (msg) => console.log(`tell me everything you are doing: ${msg}`);

const Option = ({ children, ...props }) => {
  const onMouseDown = e => props.selectProps.mySpecialAnalyticsHandler(`user clicked a ${children} colorbox`);

  return (
    <components.Option {...props}>
      <Colorbox color={children} onMouseDown={onMouseDown}>{children}
    </components.Option>
  );
}

return <Select 
  component={{ Option }} 
  mySpecialAnalyticsHandler={mySpecialAnalyticsHandler} 
  {...otherProps} 
/>
```

Please let me know if this answers your question, as it seems this functionality is already present, or if there is a request or use-case I am not uncertain of.

**Comment by DarkPurple141** [comment]
Let me just verify this. That could be what I'm after.

**Comment by ebonow** [comment]
Just a side note that if you do intend to attach click handlers...

The `onMouseDown` event inside the MenuList gets swallowed (event.stopPropogation, event.stopDefault) so click handlers are usually swallowed up before then since `onClick` comes later in the event loop.

If you want to attach directly to the Option, there is an innerProps prop which applied directly to the component. Since there is already a mouseDown event on the innerProps for Options, you'd likely want to curry it. 
```js
const Option = props => {
  const innerProps = {
    ...props.innerProps, 
    onMouseDown: e => {
      props.selectProps.mySpecialAnalyticsHandler();
      props.innerProps.onMouseDown(e);
    }
  }
  
  return <component.Option {...props} innerProps={innerProps} />
}
```
 
Of course if you are tracking a selected option, the `onChange` select prop might be a bit more straight forward and capable of capturing keyboard events, but every use-case is different. Just wanted to give you some options knowing how granular and complex analytics can get.

**Comment by DarkPurple141** [comment]
Thanks @ebonow yeah tbh the `selectProps` should be the escape hatch required. This wasn't so much strictly about handlers but yeah injecting additional props from a parent dynamically. Both are helpful though. Thanks for your replies!
