### ISSUE TITLE
place for style plugin 

### ISSUE THREAD

**Issue by SergeyMelnyk** [JedWatson/react-select#4353]
hi, can any body help me with style, plugin insert own style like this: 

`<style data-emotion="css">.css-1wa3eu0-placeholder{color:hsl(0,0%,50%);margin-left:2px;margin-right:2px;position:absolute;top:50%;-webkit-transform:translateY(-50%);-ms-transform:translateY(-50%);transform:translateY(-50%);box-sizing:border-box;}</style>`

to head tag in my DOM, i want change destination for this style, how it make

**Comment by manvydasu** [comment]
If you want to style Select component, some examples are here
https://react-select.com/styles

**Comment by SergeyMelnyk** [comment]
i know how to style component, but i want use react-select component in shadow root, where all styles is isolate, and style which plugin included , inserted to head in main dom, i want replace they to my shadow root

**Comment by ebonow** [comment]
@SergeyMelnyk you would likely need to create your own custom components to do this as most of the components provide an `innerProps` which is applied directly to the component.

Here is a working example based on my understanding of your ask: [codesandbox](https://codesandbox.io/s/react-select-style-inner-prop-291t2?file=/src/App.js)

Please let me know if this solves what you are trying to accomplish.

**Comment by ebonow** [comment]
In an effort to clean up stale issues, I will be closing this. If the proposed solution does not work please feel free to reply and we can reopen this if necessary.

**Comment by peterszerzo** [comment]
@ebonow the posted solution doesn't answer the problem. The issue here is that `emotion` adds documents in the global document whereas custom elements using the shadow DOM will not apply these styles to the contents of the custom element. This leads to an otherwise good-looking custom element looking like this inside a custom element:

<img width="1357" alt="Screenshot 2021-03-28 at 12 15 36" src="https://user-images.githubusercontent.com/6738398/112748930-66bb2b80-8fbf-11eb-8b88-44292f1cbdc0.png">

What might solve the issue is an option to have `react-select` expose the container into which `emotion` should be adding styles. This link might be helpful: https://emotion.sh/docs/@emotion/cache#container.
