### ISSUE TITLE
Inline style

### ISSUE THREAD

**Issue by edgesoft** [JedWatson/react-select#436]
Any plans on removing css and use inline styles instead?

**Comment by mull** [comment]
:-1:

**Comment by dminkovsky** [comment]
no need to remove anything; would be really easy to support both

**Comment by brianreavis** [comment]
I don't think CSS is dead yet.

> "really easy to support both"

This is a very slippery slope for maintainers. The final call is on @JedWatson, but this sort of feature is useful to few, following a bandwagon, and one more distraction / thing to maintain. Couldn't inline styles be accomplished in a fork?

**Comment by dminkovsky** [comment]
I was thinking anywhere there is a `className` that takes a `prop`, you have a `style` that takes a `prop`... is that not really easy?

**Comment by brianreavis** [comment]
@dminkovsky For supplementing the styles? Yeah, that's not bad. I think that's a little different than what @edgesoft is pushing for... which is moving all of [this](https://github.com/JedWatson/react-select/blob/master/dist/default.css) into javascript ala [radium](http://projects.formidablelabs.com/radium/) (unless I'm mixed up)

**Comment by dminkovsky** [comment]
@brianreavis yeah that's all I was thinking. But correct me if I'm wrong—if done the way I describe above, I think you could use `className`s or `style`s equivalently.

I'm using the inline styles+Radium approach when possible on my current project and landed on this issue because neither [react-typeahead](https://github.com/fmoo/react-typeahead) nor this project supports inline styles. Radium lets you work around this with its [Style component](https://github.com/FormidableLabs/radium/tree/master/docs/api#style-component) ("work around" because I'm preferring to keep component-specific CSS coupled to the component it styles). So it's not _really_ an issue, but it would be nice to have inline styles where `className` is possible to set with a `prop`.

**Comment by edgesoft** [comment]
@dminkovsky Geat, that would make most people happy.

**Comment by edgesoft** [comment]
This repo has ported to inline styles but also support css. [https://github.com/igorprado/react-notification-system](https://github.com/igorprado/react-notification-system)

**Comment by xomyaq** [comment]
I think that [react-themeable](https://github.com/markdalgleish/react-themeable) is the best solution.

**Comment by holmesal** [comment]
+1 for adding a `style` prop to support inline styles (I also use Radium on react-web, StyleSheet on react-native). I also don't think that this approach is super-rare these days (in the react community).

As far as implementation, it should be as easy as adding a `style` or `containerStyle` prop to the outer element - no need to port any of your existing styles out of css or anything like that. Inline styling of the options can already be achieved by providing a `optionRenderer`, so although an `optionStyle` prop would be awesome for building on the default styles it's not strictly necessary if you feel it's too much to maintain.

I get that some people don't like inline styles on a philosophical level, but IMO developers should be able to go that route and still be able to use react-select in a nice way.

@dminkovsky thanks for the tip about Radium's Style component! 👌

**Comment by dminkovsky** [comment]
@holmesal maybe this will help too https://github.com/dminkovsky/radium-loader?

**Comment by iDVB** [comment]
+1 for inline support

**Comment by dminkovsky** [comment]
You may find https://github.com/dminkovsky/radium-loader helpful. I made it
to help solve issues like this.

(Disclaimer: I am the author)

понедельник, 12 сентября 2016 г. пользователь iDVB написал:

**Comment by iDVB** [comment]
Thanks @dminkovsky !
