### ISSUE TITLE
`useState` does not update inmediately with select

### ISSUE THREAD

**Issue by gino** [JedWatson/react-select#4383]
Hi there.

I am trying to save the selected value of the menu to a state using the `useState` hook, but unfortunately, the state does not immediately update and I have no clue if this is an issue on the react-select side. I also tried this same thing multiple times but it does not seem to update:

Using a normal `useState` hook like here:
```js
const [selected, setSelected] = useState(null);
```

Then I try to actually call the function in the onChange event like here:
```js
onChange={(a, b) => {
  setSelected(a.value);
  console.log(selected);
  // I expect 'selected' to be my value of the selected option (but this one still outputs "null", like the initial state).
  // After changing the selected option for the 2nd time, the first option (that was before selected) gets logged.. 
}}
```

It looks like my state is not immediately being updated, but I am not sure.
Could this be because I am using Next.js and importing the library through this way:
```js
const SelectMenu = dynamic(() => import("react-select"), {
  ssr: false,
}) as Select;
```

I don't think this should make a difference, without using that, I get a bunch of SSR errors.. but really strange issue and I can't get the correct selected value because of this.

I hope someone is able to help me out, thank you!

**Comment by Rall3n** [comment]
@gino This has nothing to do with this library. This is a common mistake which happens when you are using the React hooks.

The state is being updated, no question. But the value of the `selected` variable inside your `onChange` handler will always be `null`. That is because the function itself is never changing. It is being declared once and never updated.

For that you have to use the [`useCallback`](https://reactjs.org/docs/hooks-reference.html#usecallback) hook.

**Comment by manvydasu** [comment]
Hello @gino 
I believe it would be good for your to go through react docs again to understand how state works. 

In your case, 'selected' is still pointing to the old state. Componenet has to re-render for it to have new value.
Anyways, in your onChange function, you should use `a.value` instead of `selected` if you want to do something with the new value.

**Comment by ebonow** [comment]
Greetings @gino, 

To piggyback off of @manvydasu, this is likely the bit of documentation worth looking at that might resolve some confusion.
https://reactjs.org/docs/hooks-faq.html#why-am-i-seeing-stale-props-or-state-inside-my-function

I will be closing this issue now as it does not appear to be an issue with react-select, but is instead the expected behavior when using react hooks. Please feel free to ask any other questions here or in the Discussions area.
