### ISSUE TITLE
Type errors from @types/react-select@3.0.27 and up

### ISSUE THREAD

**Issue by madou** [JedWatson/react-select#4389]
**v3.0.27 +**

```

/Users/mdougall/projects/atlaskit-test/src/App.tsx
TypeScript error in /Users/mdougall/projects/atlaskit-test/src/App.tsx(12,11):
Type 'true' is not assignable to type 'false | undefined'.  TS2322

    10 |         <img src={logo} className="App-logo" alt="logo" />
    11 |         <Select
  > 12 |           isMulti
       |           ^
    13 |           />
    14 |       </header>
    15 |     </div>

```

`isMulti` is `undefined | false`

**v3.0.26**

```
yarn run v1.22.4
$ react-scripts build
Creating an optimized production build...
Compiled successfully.

File sizes after gzip:

  98.66 KB  build/static/js/2.a278f227.chunk.js
  1.4 KB    build/static/js/3.f7df8674.chunk.js
  1.18 KB   build/static/js/runtime-main.638837aa.js
  531 B     build/static/css/main.8c8b27cf.chunk.css
  518 B     build/static/js/main.a3ab659c.chunk.js

The project was built assuming it is hosted at /.
You can control this with the ho
```

`isMulti` is `boolean`

**Comment by Methuselah96** [comment]
See https://github.com/DefinitelyTyped/DefinitelyTyped/pull/49673 and https://github.com/JedWatson/react-select/issues/4308 for more information regarding this change. Feel free to respond in this issue if you have more questions, but I'm going to close this issue since the types are maintained in the DefinitelyTyped repo and not in this repo.

How are you importing `Select`? Is it being imported from `atlaskit` or `react-select`?

**Comment by madou** [comment]
Thanks mate - we're importing via `@atlaskit/select`. I think the reality is we'll need to update type usage in the component and that'll fix things, probably.

Will get the team to look at it 😄
