### ISSUE TITLE
Clarify 'name' prop in docs

### ISSUE THREAD

**Issue by Slapbox** [JedWatson/react-select#4402]
[The docs](https://react-select.com/props) read "Name of the HTML Input (optional - without this, no input will be rendered)"

But looking at the behavior I see in the sandbox provided in the issue template, and in our own project, excluding the `name` prop does not result in "not input will be rendered." I'm not entirely clear on what "input" is being referred to here, but both the `<input />` element and the text the user inputs are rendered. Can this language be clarified?

**Comment by ebonow** [comment]
Greeting @Slapbox ,

The input that is referred to is a hidden input which receives the value of the selected option.

The primary use of this is when used with forms as a means to submit data. This is especially useful since:
- input value is cleared on blur
- When isSearchable is false, there is no editable input rendered
- When isMulti, the input is used for the addition of new entries

I agree this is not well communicated and perhaps a section specific to using with forms or form managers (react-hook-forms, formik, react-final-form, etc...) would be useful. Specifically the related props would be `form`, `name`, and `delimiter` (for isMulti)

**Comment by ebonow** [comment]
I have added this to the general documents improvements thread #3006  to be looked over as the new documentation is being built. I will close this ticket for now to give more transparency to other outstanding issues.
