### ISSUE TITLE
Obtaining focus from the hidden input inside react-select

### ISSUE THREAD

**Issue by tswistak** [JedWatson/react-select#4416]
Hi!
I'm using react-select with React Final Form. For Final Form I'm using a helper library final-form-focus which allows me to focus first input on which there's an error. Unfortunately, it doesn't work well with react-select.
That library makes focus on input, but react-select doesn't propagate the focus from input to itself.

I'm giving issue here because I don't suppose that other libraries should be aware that the input component can be wrapped by something else, like react-select does.

Reproduction steps:
1. Go to https://sklrz.csb.app/ (source code: https://codesandbox.io/s/react-final-form-react-select-focus-issue-sklrz?file=/src/index.js)
2. Open developer tools and put a breakpoint in file `final-form-focus.es.js` on line 41 (`if (firstInput) {`)
3. In browser: Press Submit without checking any value
4. In debugger: check the value of firstInput variable - it's a reference to the hidden input wrapped by react-select
5. In debugger: resume execution
6. In browser: react-select doesn't have a focus.

Expected:
Select component should obtain focus from the input inside of it.

**Comment by ebonow** [comment]
Greetings @tswistak, 

Unfortunately, react-select does not support validation at this point in time. You can read more about it here: https://github.com/JedWatson/react-select/issues/4327

The behavior of react-select is that it uses a hidden field to store the selected value and creates it with the name supplied to the select as the selected value does not necessarily exist in the input 
- Single select, value is cleared on blur
- When isSearchable is false, there is no editable input rendered
- When isMulti, the input is used for the addition of new entries

By storing the selected value in a hidden field, it allows forms to get and submit the selected values with the expected names.

The behavior you are describing appears to be react-final-form is such that:
- A validity attribute is applied to the form with the provided name
- On submit, final-form-focus then gets all inputs and tests the validity
- The applied validity fails, and attempts to focus on the hidden field

To me, it seems strange that the library would try to focus on a hidden field.

What could potentially be done, is creating a custom Input component and applying a `setCustomValidity` to it onMount which returns the validity of its corresponding matching hidden field. This actually might be a nice solution in general and will likely explore this as solution.

https://developer.mozilla.org/en-US/docs/Web/API/HTMLObjectElement/setCustomValidity

Since it's already been documented that validity is not working on the input, I will close this as a duplicate but also add this issue to the list of known reported cases.

If you would like to discuss further about a work around, we can do so, but the only way to seemingly do this with this library is to share the validity with the hidden inputs as final-form-focus will keep attempting to focus on invalid hidden inputs first. Happy to work through it with you if you are interested.
