### ISSUE TITLE
Search does not work when using elements as labels.

### ISSUE THREAD

**Issue by alimovz** [JedWatson/react-select#4438]
Searching labels works great when the options array looks like this:
```
const options = [
  { value: "2312312", label: "Chocolate" },
  { value: "1231eqs", label: "Strawberry" },
  { value: "sdfsf234", label: "Vanilla" }
];
```
But when it looks like this:
```
const options = [
  { value: "2312312", label:  <span> Chocolate <i>Some stuff here</i></span>},
  ...
];
```
Searching `Cho` or `Van` or `Stra` does not work.

Here is a Sandbox to reproduce the issue: https://codesandbox.io/s/eager-field-rrh83?file=/src/App.js

Can you advise on how to fix that?

**Comment by ebonow** [comment]
Greetings @alimovz,

The reason this does not work is because the select relies on string labels to do filtering. Since you are passing JSX, it is stringifying it into `[Object object]` as you can see by typing that into the text input. Please note that this also affects accessibility as the string label read back from screen readers will also be `[Object object]`.

The recommended way to do something like this is by using the `formatOptionLabel` prop to generate the JSX.


```jsx
cont formatOptionLabel = option => (<span> {option.label} <i>Some stuff here</i></span>);

return <Select formatOptionLabel={formatOptionLabel} {...otherProps} />
```

Does this resolve your use case?

**Comment by alimovz** [comment]
Yessir! Works like a charm. Thank you.
