### ISSUE TITLE
how to set readonly Attribute

### ISSUE THREAD

**Issue by Alichs** [JedWatson/react-select#4464]
![image](https://user-images.githubusercontent.com/73932872/109005336-cda9a400-76e4-11eb-9860-c33a3aa3758d.png)

when select component focused, no keyboard as expected.

i tried, but no work
```javascript
<Select readonly="readonly" onFocus={e => e.preventDefault()}  />
```

**Comment by ebonow** [comment]
Greetings @Alichs ,

readonly is not a supported prop.

Instead you may use:
- `isSearchable` to disable the input so that the keyboard doesn't pop up still show the menu to select an option like a dropdown
- `isDisabled` to completely disable the input so that the value cannot be changed

Let me know if this satisfies what you are looking for and if not, we can continue to discuss further.
