### ISSUE TITLE
Async options without a label or value don't work on a multi-select

### ISSUE THREAD

**Issue by jymbob** [JedWatson/react-select#4488]
We've been using a dataset with react-select that loads each record with an `id` and a `display_value`. As the entire object is passed up from react-select in the onChange event, until now we have just looked for those fields on the way in and out using a custom formatOptionLabel and a custom filter.

Today for the first time I attempted to use this dataset in a `<Select>` with `isMulti` set. After selecting the first option, everything vanished from the dropdown.

Eventually I tracked this down to `buildFocusableOptions` and have now worked around this by mapping the `id` to `value` but it would be helpful to have this requirement documented somewhere!

See example code [here](https://codesandbox.io/s/codesandboxer-broken-async-multi-tqm3y)

**Comment by ebonow** [comment]
Greetings @jymbob , were you looking for `getOptionLabel` and `getOptionValue`?  

The below are pulled from the props documentation
> **getOptionLabel** _typeof getOptionLabelBuiltin = (option) => string_
> Resolves option data to a string to be displayed as the label by components
> Note: Failure to resolve to a string type can interfere with filtering and screen reader support.

> **getOptionValue** _typeof getOptionValueBuiltin = (option) => string_
> Resolves option data to a string to compare options and specify value attributes

There is also an additional section here with an example:
https://react-select.com/advanced#replacing-builtins

**Comment by jymbob** [comment]
Not specifically.

I had the data, I was expecting to use a custom formatter to display it, and it was already in the format I needed for my use case.

So my intention was:
1. filter response to options
2. modify display using `formatOptionLabel`
3. pass the selected response out via `onChange`

I built this as a simple AsyncSelect, and it was fine. So far, so good. No errors, no issues, no warnings that I might conceivably be setting myself up for future problems.

As soon as I added the `isMulti` attribute, my options vanished after the first selection. This is repeatable. I don't know what's different about how they're checked for the initial display vs subsequent ones (I suspect a function is being skipped over because there's no currentValue), but it was disconcerting to have them just vanish on me.

I spent over an hour poring through the docs, and trying to figure out the issue with React dev tools, before I eventually spotted that while `options` was passing through unscathed, `focusableOptions` was empty.

I inferred that there was no requirement for any particular keys to be in the options Array. Apparently there is.

**Comment by ebonow** [comment]
Sorry about that. A new documentation is being worked on now and should be out within the next month or two so hopefully it will be a bit easier to find in the future.

Many people were likely using `formatOptionLabel` and `getOptionLabel` interchangeably but there is a distinct difference that should be noted:

`formatOptionLabel` is exclusively for rendering JSX. It's essentially just a shortcut for writing quick custom `Option` and `{Single|Multi}Value` components.

`getOptionLabel` is used for filtering as well as accessibility.
- filtering is done by stringifying both the label and value and doing a string comparison (this can be customized by createFilter)
- the aria-live accessibility is dependent on this because it needs to read back the selected/focused labels, which aren't apparent if not properly mapped to some string value (JSX gets natively stringified to `[Object object]`)

react-select currently has 65 different props so it's hard to convey everything, but welcome to any feedback in terms of how to make this more clear. 

Can you confirm that adding the accessor props for getOption{Label|Value} resolves your issues?

**Comment by ebonow** [comment]
This doesn't appear to be an issue with the library so I will close this issue, but please feel free to reply if you come across any other issues or have some constructive feedback on where or how to better document what you were looking for.

**Comment by jymbob** [comment]
Just to confirm, adding a getOptionValue does return me to expected
behaviour
