### ISSUE TITLE
Custom option component, keys up/down does not show selected option

### ISSUE THREAD

**Issue by fpetterlate** [JedWatson/react-select#4494]
react-select:4.2.1

`
<AsyncSelect components={{Option: customOption}} isMulti={true} ... />
`

`
function customOption({innerProps, data}) {
    return <div {...innerProps}>{data.label}</div>
}
`

On mouse over the background color change to show the option you will be selecting. But when using keys up/down the background color does not change to show selected option. If i press enter the correct item is selected.

**Comment by ebonow** [comment]
Greetings @fpetterlate , 

This is not an issue with library but rather the implementation.
1. You are not passing the innerRef
https://react-select.com/components#inner-ref
2. You are replacing the <components.Option> with your own div. This is fine, but a majority of the component is used to establish the styling including disabled and focused styling so you would need to account for that in your component by looking at the relevant props or using the styling api.

There are plenty of examples on the site for custom Options but it's also not clear to me why you are overriding the Option component since nothing in your implementation seems to require it. Happy to reply and assist further but this isn't a bug.
