### ISSUE TITLE
Select not closing when using components.ValueContainer

### ISSUE THREAD

**Issue by suyashdeshpande** [JedWatson/react-select#4557]
I am using `components.ValueContainer`. After selecting multiple options, when I click outside somewhere else, dropdown doesn't get closed.

Codesandbox: https://codesandbox.io/s/react-select-custom-valuecontainer-forked-wuusq?file=/src/index.js:306-331

When no options are selected, it works perfectly fine

**Comment by ebonow** [comment]
Greetings @suyashdeshpande ,

The ability for the menu to close on its own on outside clicks is based on the Input calling onBlur and closing the Input. Since the code sandbox example is replacing the children of the Value Container with a string label when there is a value, there is no longer an Input to blur and therefore to close the menu.

Several workarounds for this implementation: 
- You can filter the children of the ValueContainer and always keep the Input
- Not sure if you have a reason for using such an old version of react-select but ever since v3.0.8 was introduced, the prop `index` on the MultiValue so you could instead replace the MultiValue instead of the ValueContainer like so:
```jsx 
// only display a single string for the selected values so only interested in rendering a single multiValue where index is 0
const MultiValue = ({ index, getValue }) =>   return !index && `${getValue().length} items selected`;

const App = () => { 
  const components = { MultiValue };
  return <Select components {...otherProps} />
```

Hope this helps

**Comment by suyashdeshpande** [comment]
Yup, it worked.
Thanks, @ebonow for the quick response.
