### ISSUE TITLE
document.contains(e.target) returns false when option is clicked.

### ISSUE THREAD

**Issue by RustamKarimov3** [JedWatson/react-select#4560]
Good afternoon!

"react-select": "4.1.0",
"react": "16.8.0",
"react-dom": "16.8.0",

Code example.

```jsx
const Component: React.FC = () => {
  const [closed, setClosed] = useState(false);
  const containerRef = useRef(null);

  const handleOutsideClick = (event: React.MouseEvent<HTMLDivElement>) => {
    if(!containerRef.contains(e.target)) {
       setClosed(true);
    };
  }

  return  (
    <div ref={containerRef} style={{ visibility: closed ? 'invisible': 'visible' }}>
       <ReactSelect />
    </div>
  )
};
```

Problem is when I click select option then check "containerRef.contains(e.target)" returns false but it looks like something wrong. Check "document.contains(e.target)" in this case also returns false as if option was outside document.

Thanks in advance!

**Comment by Rall3n** [comment]
Hello @RustamKarimov3,

I hope you don`t mind that I edited your output to make the code sample more readable.

`document.contains(e.target)` returns `false` when an option is clicked because the item is no longer in the document at that time. By default, the `Select` component closes the menu after an option is selected. Due to event bubbling and the asynchronous nature of the component's state, the menu is removed from the document before your handler can execute.

I would suggest that instead of checking the active document, you check the `path` attribute of the event. This should contain a list of elements at the time of the event (from `window` to the triggering element)

```jsx
const handleClickOutside = (event) => {
    let containsElement = event.path.includes(containerRef.current);
    /* ... */
}
```

**Comment by RustamKarimov3** [comment]
@Rall3n That`s amazing, thank you very much!

**Comment by ceremonious** [comment]
Thanks for the solution! FYI for anyone else that finds this, you may need to use `event.composedPath()` instead of `event.path`. https://stackoverflow.com/questions/39245488/event-path-is-undefined-running-in-firefox
