### ISSUE TITLE
Accessibility isssue on AsyncSelect

### ISSUE THREAD

**Issue by sanjaykc** [JedWatson/react-select#4597]
I am using latest version of react select. Getting accessibility issue wile running the code.

**Accessibility issue**:
  "The input element does not have an associated visible label".
   _An input element must have an associated visible label_
Element location:
     `<input value="" style="box-sizing: content-box; width: 2px; background: rgba(0, 0, 0, 0) none repeat scroll 0px center; border: 0px none; font-size: inherit; opacity: 1; outline: currentcolor none 0px; padding: 0px; color: inherit;" aria-label="Business Unit" aria-autocomplete="list" type="text" tabindex="0" spellcheck="false" id="react-select-53-input" autocorrect="off" autocomplete="off" autocapitalize="none">`

Even after adding id to the select, issue persist.
**code sample**:
```
<label
        htmlFor={
          'type-head__' +
          props.label
            .split(' ')
            .filter((s) => s)
            .join('')
        }>
        {props.label}
      </label>
<AsyncSelect
         inputId={
           'type-head__' +
           props.label
             .split(' ')
             .filter((s) => s)
             .join('')
         }
        isMulti={isMulti}
        cacheOptions={true}
        value={props.typeaheadVal || ''}
        aria-label={props.label}
        // defaultOptions
        placeholder={placeholder}
        loadOptions={promiseOptions}
        onInputChange={handleInputChange}
        className="adv-search-multi-select"
        classNamePrefix="select"
        components={animatedComponents}
        name={props.label}
        closeMenuOnSelect={true}
        onChange={handleChange}
        isSearchable={isSearchable}
        isClearable={isClearable}
        styles={style}
        // autoFocus={true}
        noOptionsMessage={() => 'No Match Found'}
      />
```
Even I  tried to run the sample react-select component, found the same accessibility issue.
`https://codesandbox.io/s/react-select-v3-sandbox-forked-k1dz0`

**Comment by ebonow** [comment]
Greetings @sanjaykc ,

There's a few things here.
- Accessibility is addressed via aria-live as opposed to standard and potentially conflicting standard aria-attributes. It's understandable that Lighthouse or other validators may not account for this. react-select still has a ways to go when it comes to a11y, but it's important to distinguish between a11y as being validated as opposed to best UX.

- Based on the link you provided for a codesandbox, its worth noting that the peer dependencies of v3.2 require that you are at minimum using react version 16.8

`value={props.typeaheadVal || ''}`
- A selected value of a select should always be an object with fields representing the label and value.

- I had no issues getting an example of this working.
[codesandbox](https://codesandbox.io/s/react-select-v3-sandbox-forked-0p8y5?file=/example.js)
![Screen Shot 2021-06-23 at 10 24 59 AM](https://user-images.githubusercontent.com/1007579/123143227-30027f00-d40f-11eb-924c-1482f444864d.png)

- `string.replaceAll(' ', '')` might be a cleaner solution for you than the logic you are using. I would also calculate this variable once and pass that value to the fields instead of the copy/paste logic.


I am going to mark this as closed, but happy to answer any other questions you might have regarding the information I provided.
