### ISSUE TITLE
Bug: Dynamic classes take precedence over `classPrefixName` classes - I have to use `!important` to apply CSS

### ISSUE THREAD

**Issue by hb-webdev** [JedWatson/react-select#4622]
The dynamic classes get listed in the HTML _after_ my `classNamePrefix` classes, so take precedence in the CSS. I thus have to use `!important` for my CSS changes, which is not ideal. According examples I've seen in StackOverflow/GitHub Issues, it seems `classNamePrefix` classes should take precedence and you should _not_ need `!important`, yes?

![image](https://user-images.githubusercontent.com/85006632/120723723-870bd880-c48f-11eb-910e-c7e6eaa46528.png)

**Comment by Rall3n** [comment]
Hello @hb-webdev,

this is unfortunately not a bug in the library, but an issue with an implemented dependency, namely [`emotion`](https://github.com/emotion-js/emotion). `emotion` is the CSS-in-JS library used to style the different components of this library. 

You have correctly identified that the styles injected by the component through `emotion` have a higher priority than the styles in your stylesheet. That is because the `emotion` styles appear later in the document than your styles.

**But** there is a way to counter this. You can use `emotion`s `CacheProvider` component in combination with a custom cache to prepend the values to the `<head>` element, giving your styles a higher priority because of them appearing later in the document than the `emotion` styles. The option to set for this is called [`prepend`](https://emotion.sh/docs/@emotion/cache#prepend).

```jsx
import Select from 'react-select';
import { CacheProvider }  from '@emotion/react';
import createCache from '@emotion/cache';

const  myCache = createCache({ key: 'my-select-cache', prepend: true }) // `prepend` is what you need to set

...

<CacheProvider value={myCache}>
    <Select {...} />
</CacheProvider>
```

**Comment by hb-webdev** [comment]
In my particular [probably wrong] implementation, this solution just makes my entire web page hang, to the point where I can't right-click the page to bring up the context menu / Inspect. (But F12 still works but shows absolutely nothing in the Console or any of the Developer Tools tabs so I can't track down any errors causing the hang.)

But I appreciate the quick response and imagine this will work for somebody... :/ I'll stick to my `!important`s for now I think
