### ISSUE TITLE
help me use  defaultValue

### ISSUE THREAD

**Issue by MohsenEs** [JedWatson/react-select#4627]
when use  defaultValue in select error

TypeError: Cannot read property '0' of undefined

` <Select
            onChange={(e) => this.handleChange(e)}
            defaultValue={options[0]}
            styles={styles}
            isLoading={isLoading}
            isDisabled={isDisabled}       
            name="color"
            options={options}
            optionAdd={optionAdd}
            getOptionLabel={({ itemName }) => itemName}
            getOptionValue={({ id }) => id}
            optionEdit={(e) => this.handleCurrentData(e)}
            optionDelete={this.handleDelete}
            id="bankSelect"
            components={{ Option }}    
            value={value}
          />`

**Comment by galabra** [comment]
What's the value of `options`? You'd probably want to set `defaultValue={options[0].value}`

**Comment by galabra** [comment]
What's the value of `options`?

**Comment by MohsenEs** [comment]
`defaultValue={options[0]} `

**Comment by ebonow** [comment]
Greetings,

`TypeError: Cannot read property '0' of undefined`

This indicates an error with your implementation and not the library so I will close the comment but happy to keep conversation open.

Regarding the error, it implies that your `options` is undefined, likely because you are trying to get them from the api. 

If this is the case, then defaultValue will not work for you as the defaultValue is only intended to work at initial render.

What you will likely need to do is pass `value` instead of `defaultValue` and when your api returns with options, set the value to the first option.
