### ISSUE TITLE
Focus selected option if we remove input of the search bar

### ISSUE THREAD

**Issue by theocerutti** [JedWatson/react-select#4639]
Hello, I would like to focus selected option when user remove everything in the search bar.
The current behavior of react-select is to focus the first option even if it's not selected.

How can I make it works ?
Is there a way to programmatically focus options ?

I already tried this (code below) but it keeps closing the menu whenever I want to open it:
I created a Custom Menu component:
```js
const Menu = (props) => {
  console.log(props);
  useEffect(() => {
    if (props.selectProps.menuIsOpen && props.selectProps.inputValue === '') {
      setTimeout(() => {
        const selectedOpt = document.getElementsByClassName(
          'select__option--is-selected',
        )[0];
        if (selectedOpt) {
          selectedOpt.focus()
          selectedOpt.scrollIntoView({
            behavior: 'smooth',
            block: 'nearest',
            inline: 'start',
          });
        }
      }, 15);
    }
  }, [props.selectProps.inputValue, props.selectProps.menuIsOpen]);
};
```

Thanks

**Comment by ebonow** [comment]
Greetings @theocerutti,

Unfortunately there is no exposed method that allows options to be focused, but is likely on the roadmap at some point. 

Regarding the menu closing, it is because the behavior of react-select to automatically close the menu when the input loses focus onBlur. Since you are calling "focus" on the `selectedOpt`, it in turn, closes the menu, so removing that line fixes that behavior.

[Please look at this demo](https://codesandbox.io/s/react-select-focus-option-ietbe) and verify that it is working as you intended.

**Comment by theocerutti** [comment]
Hello!

> Unfortunately there is no exposed method that allows options to be focused, but is likely on the roadmap at some point.
Great!

Thanks for your answer!

**Comment by diavrank** [comment]
Hi,

> Unfortunately there is no exposed method that allows options to be focused, **but is likely on the roadmap at some point.**

I was wondering if there is already a method to control the focus state of the options?
