### ISSUE TITLE
Creatable: 'name' prop isn't passed to input element

### ISSUE THREAD

**Issue by jviall** [JedWatson/react-select#4681]
Reproduced: https://codesandbox.io/s/modest-field-682sj

This may exist on other components as well, but at least with `Creatable` I expect that when I pass a `name` prop like so:
```jsx
   <Creatable
    name="creatable"
   />
```
that it makes it to the inner `input` element. 

```jsx
<input name="creatable" id="react-select-2-input" tabindex="0" type="text" aria-autocomplete="list" value=""/>
```

**Comment by Rall3n** [comment]
Hello @jviall,

this is intentional. The `name` prop is not used for the `<input>` element you reference, because this element is only used for managing focus and searching through our available options. We would not want to have it hold the actual value of the component for form submission.

The `name` prop is instead used for an `<input>` element with `type=hidden`.
