### ISSUE TITLE
Text Cursor color not changing in IE11  and its appearing over to menu list if dropdown over to container

### ISSUE THREAD

**Issue by SharmaPoo** [JedWatson/react-select#4705]
using input: styles => ({ ...styles,   color: "#fff" }) 
text cursor color changed in chrome but not in IE11.

I wanted dropdown to be appeared in center if not enough space in top and bottom. 
but due to cursor appearing over menu looks weared.

Thanks in advance

**Comment by Rall3n** [comment]
Hello @SharmaPoo,

this is not a problem with the library itself, but with how Internet Explorer implements the CSS specifications. As far as I know, there is no way in IE to color the text cursor in `<input>` elements with the `color` property. And since Internet Explorer is reaching its end of support, there will probably be no further changes in this regard from Microsoft.

**Comment by SharmaPoo** [comment]
> Hello @SharmaPoo,
> 
> this is not a problem with the library itself, but with how Internet Explorer implements the CSS specifications. As far as I know, there is no way in IE to color the text cursor in `<input>` elements with the `color` property. And since Internet Explorer is reaching its end of support, there will probably be no further changes in this regard from Microsoft.

Hi @Rall3n 
I found solution for it because it was not working for even Edge.
May be it help someone else.
Instead of styling input -> change style of input inside value container.
valueContainer: styles => ({...styles, input:{color: '#fff' }}),
