### ISSUE TITLE
Long menu options without space or dashes can overflow and cause a horizontal sidebar to appear in the opened dropdown

### ISSUE THREAD

**Issue by olignyf** [JedWatson/react-select#4710]
Using 3.1.0

When the option label is very long and has no dashes or spaces toward the end, it can overflow and cause a horizontal scrollbar. 

<img width="285" alt="react-select-overflow" src="https://user-images.githubusercontent.com/1154566/128389096-0dbb8401-1bd3-4216-9432-f8bdabdbd136.PNG">

<img width="239" alt="react-select-overflow2" src="https://user-images.githubusercontent.com/1154566/128389109-8edfcdb3-61b6-4c45-be69-9b0a2f973e73.PNG">

My solution is to write this extra CSS code :

```
    .react-select__menu > div {
        overflow-x:hidden;
    }
```

Can someone help me make a pull-request?

Thanks!

**Comment by ebonow** [comment]
Greetings @olignyf ,

Thank you for reporting this, but I believe this is more feature than bug, especially when it comes to longer content without spaces. 

The suggested method above would make it impossible for a user to distinguish differences in options if the overflow-x was set to hidden for the extremely long urls shown above above.

Perhaps `white-space: pre-line;` might be a better alternative for you and your users, but the choice here is a matter of preference and not a technical one and would seem better to always default to giving the user access to see the complete option instead of hiding it.

I'm opening to helping with any implementation questions, but as this is expected behavior, I think it best to close this reported issue.
