### ISSUE TITLE
How to improve the functionality of ```isMulti``` or add feature of showing newly typed data on the chained manner after hitting enter key ?????

### ISSUE THREAD

**Issue by ProPhycient5** [JedWatson/react-select#4726]
I want to build select component like this, but I want when the user type something on the input, it will create and show new data on the chained manner while hitting enter key.[enter image description here][1] This is the usual code from react-select. But I want improvised one. @all Please help how to build such component.

Below code is the reference code, I want to build like this, but it will have feature of creating new data as soon as the user type and hit enter key on the input field.

```import Select from 'react-select';
import { colourOptions } from '../data';

export default () => (
  <Select
    defaultValue={[colourOptions[2], colourOptions[3]]}
    isMulti
    name="colors"
    options={colourOptions}
    className="basic-multi-select"
    classNamePrefix="select"
  />
);```

**Comment by Rall3n** [comment]
Hello @ProPhycient5,

Based on your description I would suggest you use the `Creatable` component. This component provides the function to create custom data from user input.

```
import Creatable from 'react-select/';

// ...

<Creatable {...} />
```

Please let me know if this solved your problem.

**Comment by ebonow** [comment]
Greetings @ProPhycient5 ,

In addition to using the `Creatable` Select as mentioned, since the options are passed as props to the control, you would need to add the new option to your existing options. Therefore you also need to pass the newly created options to the Select as well.

```jsx
const [ options, setOptions ] = useState(props.options);

const onCreateOption = enteredText => {
  const newOption = { label: enteredText, value: enteredText };
  setOptions([...options, newOption]);
} 

return <Creatable options={options} onCreateNewOption={onCreateNewOption} {...otherProps} />
```

We will close this out this since this is an implementation question and has been open with no reply for quite some time. Please let us know if you have any further questions though.

**Comment by ProPhycient5** [comment]
Yeah sure, you close this request.
