### ISSUE TITLE
react-select onChange doesn't work with styled-components

### ISSUE THREAD

**Issue by newilu** [JedWatson/react-select#4764]
it's just dont work
at all
no need to provide any code, that just dont working

**Comment by Rall3n** [comment]
Hello @newilu,

could you please provide a minimal reproducible example of how you create your styled components and implement them with `react-select`?

**Comment by newilu** [comment]
> Hello @newilu,
> 
> could you please provide a minimal reproducible example of how you create your styled components and implement them with `react-select`?

Just create component.tsx & styled.ts => create styled(Select) => use StyledSelect with onChange event and it will not work

**Comment by Rall3n** [comment]
I don't think it is an issue with `react-select`.
I created a [CodeSandbox example](https://codesandbox.io/s/react-select-4764-l6hvg) to try to confirm your issue, but everything works as expected. You should see a console output when you select an option in the `StyledSelect` component.

I would like to ask you again to provide a minimal reproducible example of your implementation to find out if the cause of the issue is the component as is, or how you implemented it.

**Comment by ebonow** [comment]
@newilu a volunteer collaborator took time to write the code example that you were unwilling to provide. This will be closed now but can be reopened if you have a reproducible example for us to troubleshoot.
