### ISSUE TITLE
`onChange` handler requires ActionMeta argument [TS]

### ISSUE THREAD

**Issue by ndom91** [JedWatson/react-select#4800]
# Are you reporting a bug or runtime error?

Potential typescript bug, or maybe I'm just using the extend incorrectly.

I have a dumb little timezone select library thats built around `react-select`. Upgrading to v5 has started to throw that `ActionMeta` is required on an onChange handler passed in via props to my component then on to `react-select`, where my component extends the react select props.

- Site of the original error: https://github.com/ndom91/react-timezone-select/pull/39/files#diff-0b5adbfe7b36e4ae2f479291e20152e33e940f7f265162d77f40f6bdb5da7405L179-L181
- I was able to reproduce it in a codesandbox: https://codesandbox.io/s/infallible-morning-jvnc1?file=/src/App.tsx

I saw you mention elsewhere that the `ActionMeta` argument should be optional, shouldn't that mean that:

https://github.com/JedWatson/react-select/blob/a4de91cd73132354afeb86041020caf8200b437a/packages/react-select/src/Select.tsx#L220-L224

Should be something like:

```ts
onChange: ( 
   newValue: OnChangeValue<Option, IsMulti>, 
   actionMeta?: ActionMeta<Option> 
 ) => void; 
```

I'm not super experienced with typescript so sorry if I'm just overlooking something here!

Thanks!

**Comment by Methuselah96** [comment]
The error is actually correct in this case because the props you are exporting to your users says that they can expect there to be a second argument passed to `onChange` when in fact you're only passing one argument to your user.

I have mentioned in the past that the second argument is optional. I should clarify that it's optional in the sense that the `Select` component will gladly accept a function for the `onChange` that only has one parameter. However the current types make the guarantee that if a function is passed to `onChange` that includes a second parameter, that parameter will never be `undefined`. Since you are re-exporting those same props, the same guarantee is in place, when in fact you're only passing in one argument to `onChange` for your users.

I hope that makes sense. I've opened [a PR](https://github.com/ndom91/react-timezone-select/pull/40) on your repo against that branch that should fix the types.

**Comment by ndom91** [comment]
Okay yeah that makes sense. Thanks a ton for the PR!!
