### ISSUE TITLE
Is `closeMenuOnSelect` officialy documented?

### ISSUE THREAD

**Issue by OfirD1** [JedWatson/react-select#4809]
I can see multiple issues here regarding `closeMenuOnSelect`, and I can see it only mentioned once [here](https://react-select.com/advanced) (in quite an obscure way), but I don't see it officially documented.

Should it be?

**Comment by ebonow** [comment]
Greetings @OfirD1 ,

Yes, it is normally documented within the props documentation, but there is an issue currently with the prop types and definitions being generated and loaded properly for the documentation page.  You can track this issue here: https://github.com/JedWatson/react-select/issues/4796
