### ISSUE TITLE
Configuring react-select to keep the input's value but resetting the search filter

### ISSUE THREAD

**Issue by ArnaudWeyts** [JedWatson/react-select#4836]
# Feature request

## Use case

Our main use case is allowing users to copy the input of react-select after an option has been selected.

I've stumbled upon https://github.com/JedWatson/react-select/issues/3938#issuecomment-686209693, which demonstrates how to achieve this, but this example also makes it so the search results are now filtered by that value. (Which makes sense from a technical point of view, but not from a UX point of view).

In an ideal situation we would want the list filter to be reset again and show all of the options (even though the input is filled in). @adobe/react-spectrum has a ComboBox component that does exactly this. The main input still acts as a regular input, but the list is not filtered by it after selecting an option. I've demonstrated this here:

https://codesandbox.io/s/restless-mountain-wbqbo?file=/src/App.js

## Solution

I would propose to revamp the input handling and implement similar behaviour to react-spectrum's ComboBox should be implemented, and the input should act as much as a regular input as possible (when the select is searchable).

Thanks so much for your work on this library 🙏🏻

**Comment by ebonow** [comment]
Greetings @ArnaudWeyts ,

Looking at the react-spectrum example, I was curious how it would differentiate between user-input and a selected value. It doesn't appear that example does filtering, but what I imagine you are looking for is a custom filter which would recognize if the input matches the selected value. If it matches, then show all options, otherwise filter on the input.

```jsx
  const filterOption = useCallback(
    (candidate, input) => {
      if (input === value?.label) return true;

      return createFilter()(candidate, input);
    },
    [value]
  );

  return <Select filterOption={filterOption} {...otherProps} />
``` 

Here is a [codesandbox](https://codesandbox.io/s/react-select-show-all-options-when-input-matches-value-label-6l0g6?file=/src/App.js) example. Please let me know if this is what you were looking for.

**Comment by ArnaudWeyts** [comment]
Hey @ebonow, thanks for the quick reply!

Not sure I'm following, the example does do filtering, but it crashed due to react strict mode. I've updated it here: https://codesandbox.io/s/react-select-show-all-options-when-input-matches-value-label-forked-cgzz3?file=/src/App.js

Your workaround gets very close to what we're trying to achieve, but there's just one use case that isn't covered with this:
When you have 2 almost identical options, all options will be displayed as soon as the selected option is inputted, this doesn't happen with the react-spectrum example

<img width="218" alt="Screenshot 2021-10-04 at 20 34 17" src="https://user-images.githubusercontent.com/10011712/135905784-86a8a921-ea3c-4c91-928f-20b8c4330040.png">
<img width="775" alt="Screenshot 2021-10-04 at 20 34 23" src="https://user-images.githubusercontent.com/10011712/135905789-e7a1cb45-9ab9-417b-8e6b-9d7df5755e24.png">

**Comment by ebonow** [comment]
@ArnaudWeyts 

react-spectrum seemingly behaves in a different way in that the menu doesn't display by default when the input field is focused or the user clicks on the control. Here is what I observed:

**Behavior 1** ✅
1. Select `Kanagaroo`
2. Press :arrow_down:
react-spectrum Result: Full menu shown with Kangaroo option checked
react-select Result: Full menu shown with Kangaroo option checked

**Behavior 2** ✅
1. Select `Kanagaroo`
2. Click down indicator button on right side of the control
react-spectrum Result: Full menu shown with Kangaroo option checked
react-select Result: Full menu shown with Kangaroo option checked

**Behavior 3** ❌
1. Select `Kanagaroo`
2. Click on the input area of the control
react-spectrum Result: Input is focused but no menu is shown
react-select Result: Full menu shown with Kangaroo option checked

This isn't to say that react-select doesn't have the same option to do this with the props `openMenuOnFocus` and `openMenuOnClick` , but it seemingly introduces some potentially confusing behavior as to when the menu should be open and when it should display all items, since this is completely optional, I will leave this up to you if you wish to replicate this behavior.


**Behavior 4** ❌
1. Select `Kanagaroo`
2. Click on the input area of the control
3. Hit Backspace once so the input reads "Kangaro"
4. Blur the Input by clicking outside of the control and the menu

react-spectrum Result: The input `Kanagaroo` is shown
react-select Result: The input `Kangaro` is shown 

This is easy enough to do with the code you copied by uncommenting that section in the onInputChange method to clear the inputValue and restore to the label of the previously selected value.


**Behavior 5** ❌
1. Select `Kanagaroo`
2. Click on the input area of the control
3. Hit Backspace once so the input reads "Kangaro"
4. Type the letter "o" so the input reads "Kangaroo"
Menu react-spectrum Result:  Menu is open with two options shown:  `Kanagaroo` (selected) and `Kangaroo2`
react-select Result: Menu is open with all options shown with `Kanagaroo` (selected) 

After at least identifying the inconsistent behavior of # 3 and # 4, then this, which is likely the issue you are referring to, can be addressed. Another state variable will likely need to be introduced so that it can be determined if the user is editing or not.

``` jsx
  const [ isEditing, setIsEditing ] = useState(false);

  const onInputChange = (inputValue, { action }) => {
    // onBlur => setInputValue to last selected value
    if (action === "input-blur") {
      setInputValue(value ? value.label : "");
      setIsEditing(false);
    }

    // onInputChange => update inputValue
    if (action === "input-change") {
      setInputValue(inputValue);
      setIsEditing(true);
    }
  };

  const filterOption = useCallback(
    (candidate, input) => {
      if (!isEditing && input === value?.label) return true;

      return createFilter()(candidate, input);
    },
    [isEditing, value]
  );

  const onChange = (option) => {
    setValue(option);
    setInputValue(option ? option.label : "");
    setIsEditing(false);
  };
```

[Code sandbox demo here](https://codesandbox.io/s/react-select-show-all-options-when-input-matches-value-label-6l0g6?file=/src/App.js)

I updated the example as well to use React v16 and to not use strict more so that the console errors from react-spectrum don't show up in the console.

I hope this is helpful.

**Comment by ArnaudWeyts** [comment]
@ebonow

Your final solution indeed seems to replicate the ideal behavior we would want. Behaviour 5 is the one that matters the most. I'll discuss with my team if we'll implement this in our UI-library by default and get back to you!

**Comment by ebonow** [comment]
Glad this fits your needs. Just wanted to cover all of the contingencies to match up the behaviors. 

I'll close this issue, but feel free to tag me if you have additional questions about whatever implementation questions you might have either here or create a topic for discussion in the Discussions area.
