### ISSUE TITLE
Typescript error: 'jsx' is declared but its value is never read.  TS6133

### ISSUE THREAD

**Issue by NunoCardoso** [JedWatson/react-select#4840]
Hi. 

React-select 5 is triggering this typescript error for me: 

```
TypeScript error in /Users/{...}/node_modules/react-select/src/components/containers.tsx(3,1):
'jsx' is declared but its value is never read.  TS6133

    1 | /** @jsx jsx */
    2 | import { ReactNode } from 'react';
  > 3 | import { jsx } from '@emotion/react';
      | ^
    4 | import {
    5 |   CommonPropsAndClassName,
    6 |   CSSObjectWithLabel,

```

I believe you just have to clean up / lint the code, as it is complaining that there is an unused var.

**Comment by Rall3n** [comment]
Hello @NunoCardoso,

I can assure you that what typescript marks as an error is in fact intended.

The import `jsx` is not unused. We use it as a replacement for the default JSX transformation from React (`React.createElement`) for emotion specific features. The comment at the top of the file is a so called [jsx pragma](https://www.gatsbyjs.com/blog/2019-08-02-what-is-jsx-pragma/) which tells our compiler (Babel) to [use this instead of the default](https://babeljs.io/docs/en/babel-plugin-transform-react-jsx#customizing-the-classic-runtime-import).

**Comment by Methuselah96** [comment]
@NunoCardoso Are you importing anything from the `src` directory?

From the v5 upgrade guide:

> If you were previously importing a type from the `src` directory when using `@types/react-select`:
> 
> ```
> import { ... } from 'react-select/src/...';
> ```
> 
> These should now be imported from the `dist/declarations/src` directory:
> ```
> import { ... } from 'react-select/dist/declarations/src/...';
> ```
> 
> We export any types from the main entry point that we think might be useful to the user. If you are using a type that is not exported from the main entry point please open a PR or issue so that we can add it.

**Comment by ebonow** [comment]
@NunoCardoso deconfirmed as an issue, but please feel free to ask if you have any implementation questions.
