### ISSUE TITLE
Impossible to get value when isDisabled === true

### ISSUE THREAD

**Issue by fredericgrati** [JedWatson/react-select#4852]
Hey !

First, Thanks for this Component. It makes its easy to add complex Select element in every project.

[I was wondering why we don't want to render the value hidden field when isDisabled is enabled ? ](https://github.com/JedWatson/react-select/blob/be452993b4dce0453d456d338d298f0ec3c05db3/packages/react-select/src/Select.tsx#L1956)

In my app, I want to avoid users changing the value of the Select. (with *isDisabled* property) Still, I want the value to be part of the form.

I am currently testing my app with `testing library` and `.toHaveFormValues()` is not able to get the value as the hidden field value is removed.

**Comment by fredericgrati** [comment]
Thanks you for the answer. Make sense. 
Maybe it could be added to the doc (same for the Select without *name* property)

For those who want to "disable" the component from users but keep the value:
```
isClearable={false}
isSearchable={false}
menuIsOpen={false}
```

**Comment by mattrodak** [comment]
Hey @ebonow , I'm having the same problem with react-testing-library.

> Since the hidden input is rendered for a form submit and the form will ignore this value, it seems unnecessary to render the hidden input.

While this is true in native HMTL, I imagine majority of users are using some sort of form library. I'm using react-hook-form and they are working just fine.

Is there a possibility add a prop to control whether we want to show HTML input or not? Otherwise I'd have to come up with some logic to apply disabled styles on select which seems to be counter-intuitive since most of the code is already there 😞

**Comment by curtisburns** [comment]
Please re-open. Have also just encountered this issue. 

Tests are failing to retrieve the input value for a disabled input (where the default value, which is dynamic, still needs to be checked). If all browsers ignore the value for a disabled input in the onSubmit handler, then there should be no issue having it remain rendered. The decision to remove it when disabled instead of simply disabling the input seems counter-intuitive and is likely continue to catch more people out.
