### ISSUE TITLE
Behavior of `ignoreCase` option for filtering is reversed.

### ISSUE THREAD

**Issue by stla** [JedWatson/react-select#4912]
Hello,

 I set `ignoreCase: false` in the `filterOption` prop. However, look below, when I type "pi" it finds "Pizza", but when I type "Pi" it finds nothing:

![reactselectfilter](https://user-images.githubusercontent.com/4466543/141470797-ff2d8428-c8d4-46a7-ab18-28c8fd849499.gif)

**Comment by Rall3n** [comment]
@stla Could you please provide a minimal reproducible example using CodeSandbox?

**Comment by ebonow** [comment]
Using your example options, this does not appear to be an issue.

codesandbox: https://codesandbox.io/s/compassionate-cartwright-rniyf?file=/src/App.js

Likely what you are seeing is that the string matching/filtering is occurring on the label AND the value. You can adjust this with the `stringify` option in your createFilter.

```jsx
  const stringify = ({ label }) => label;
  const caseSensitive = createFilter({ ignoreCase: false, stringify });
  
  return <Select filterOption={caseSensitive} {...otherProps} />
```

I'm marking this as closed, but if you are able to provide a reproducible example showing otherwise, I'd be happy to reopen and investigate.

**Comment by stla** [comment]
Thanks! I didn't understand the `stringify` option. Sorry for not having provided a code sandbox, I don't have an account yet.

**Comment by stla** [comment]
You're right @ebonow In fact my `option.label` is a React element. Now I'm using this function for `stringify`, it works fine:

```js
const getStrings = (option) => {
  const label = option.label;
  if(typeof label === "string"){
    return label;
  }
  if(React.isValidElement(label)){
    const strings = label.props.children.filter(x => typeof x === "string");
    return strings.join(" ");
  }
  return "";
};
```
