### ISSUE TITLE
Provide an easy way to extend react-select to make it work with other data structures

### ISSUE THREAD

**Issue by smashercosmo** [JedWatson/react-select#502]
Immutable data structures become more and more popular in React community. But one of the biggest issues of using them is that there is no straightforward way to integrate them with third-party components like react-select. That's why we end up with converting immutable data to plain js and back.
I suggest to provide several facade-methods for array manipulation, that anyone can easily override to provide support for any data type he wants.
These methods are  _isArray, _getArrayLength, _getArrayItem and so on.

So originally we will have something like this

``` javascript
{
  _isArray(array) {
    return Array.isArray(array)
  },
  _getArrayLength(array) {
    return array.length;
  },
  _getArrayItem(array, index) {
    return array[index]
  }
}
```

but if we need, for example Immutable.js support, then we can extend react-select in the following way

``` javascript
import Select from 'react-select';
import {List} from 'immutable';

class ImmutableReactSelect extend Select {
  _isArray(array) {
    return Immutable.List.isList(array) || Array.isArray(array)
  },
  _getArrayLength(array) {
    return  Immutable.List.isList(array) ? array.size : array.length;
  },
  _getArrayItem(array, index) {
    return Immutable.List.isList(array) ? array.get(index) : array[index];
  }
}
```

and now we can use 

``` javascript
import React from 'react';
import {List, Record} from 'immutable';
import ImmutableReactSelect from './ImmutableReactSelect';

const Option = Record({ value: '', label: '' });
const options = List([
   new Option({ value: 'one', label: 'One' }),
   new Option({ value: 'two', label: 'Two' }),
   new Option({ value: 'three', label: 'Three' })
]);

export default class App extends React.Component {
  render() {
    return (
      <ImmutableReactSelect
        name="form-field-name"
        value='one'
        options={options}
      />
    );
  }
}
```

I have a PR for these changes. If you guys are interested, I can submit it.

**Comment by Webkadabra** [comment]
I would vote for that, immutable is awesome :+1:

**Comment by stipsan** [comment]
I was just about to write a PR for this, but if you got one ready @smashercosmo it would be awesome if you submitted it 😃 I can help out if you're short on free time 👍

**Comment by smashercosmo** [comment]
Well, actually I came up to conclusion, that more convenient way to deal with Immutable data structures is to convert them to normal js structures using selectors. Consider using [reselect](https://github.com/reactjs/reselect).

**Comment by stipsan** [comment]
Thanks for sharing, that's likely a much better solution indeed 👌

**Comment by kevinjhanna** [comment]
Hey @smashercosmo @stipsan, wouldn’t it be better to use the immutablejs ```Iterable```, performance-wise?

Suppose you have a big ```List``` of ```Map```s, and one of those changes, that would discard the memoized array, and convert the whole ```List``` again to js.

I **guess** that using "native" ```Iterable```s you wouldn’t need that transformation, is that right?

**Comment by stipsan** [comment]
@kevinjhanna `Map` extends `Collection.Keyed` which extends [`Iterable`](http://facebook.github.io/immutable-js/docs/#/Iterable).

@leebyron recently pushed out [literall](https://github.com/leebyron/iterall), quoting from its [FAQ](https://github.com/leebyron/iterall#faq) using a `Map` or `List` inside a component render should be supported:

> In [React](https://github.com/facebook/react), render functions are expected to return view trees, where any
node (e.g. a `<ul>`) can have many children (e.g. many `<li>`). While it could
expect those children to always be represented as an Array, that would limit
React's usefulness - other data-structures couldn't be used. Instead, React
expects those children to be represented as an _Iterable_. That allows it to
continue to accept Arrays, but also accept many other data-structures.

> [Immutable.js](https://github.com/facebook/immutable-js/) implements many new kinds of data-structures (including [HAMT](https://en.wikipedia.org/wiki/Hash_array_mapped_trie))
all of which implement _Iterable_, which allows them to be used in many of
JavaScript's built-in functions, but also allows them to be used by many
libraries which accept Iterables, including React. Also, similar to
[`Array.from`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/from), Immutable.js's constructors accept not only Arrays,
but any _Iterable_, allowing you to build any of these new data-structures from
any other data-structure.

It looks like this would be a safe thing to support in react-select. Instead of supporting `Immutable.js` specifically, it could simple use this method from `iterall`, [`isCollection`](https://github.com/leebyron/iterall#iscollection) to verify that the `options` is not an object or a string, but a collection of options.

And yeah, this would avoid transforming data structures and perform a lot better compared to selectors. You're absolutely right.

**Comment by justhineT** [comment]
Was this ever implemented?

**Comment by gilangmugnirespaty** [comment]
UP!

**Comment by seanlindo** [comment]
+1 :)

**Comment by cosmidumi** [comment]
+1!

**Comment by seanlindo** [comment]
@justhineT I don't think so. I ended up using reselect in my containers when mapping state to props and it worked great.

**Comment by kylemh** [comment]
@smashercosmo @stipsan do either of you have a simple example of utilizing `reselect` in conjunction with `react-select`? I, too, have entirely immutable data that I'd like to use `react-select` with, but am having to map with `toJS()` rn
