### ISSUE TITLE
Input loosing focus when menu is Open

### ISSUE THREAD

**Issue by cubecleveland** [JedWatson/react-select#5039]
Hello, im not sure if this is a bug r an expected behaviour and if this can be overcome.

When React select prop for menuIsOpen is True.

The input box does not get back the foucs when clicking in it.

Just apply menu?IsOpen to any simple Select and u ll see that clicking back in the input doesnt show the blinkink cursor...

it only happens when menuIsOpen .

However looking at the experimental example in the docs it seems to not be the case.

Here si a sandbox to reproduce.
https://codesandbox.io/s/react-select-default-value-forked-7e8zp?file=/index.js

Again, just add menuIsOpen to the props and the focus is gone.

**Comment by Rall3n** [comment]
Hello @cubecleveland,

I could not see the component losing focus after any interaction done inside the component.
Yes, the input cursor is hidden, but this is by design after selecting an option (in a non-`isMulti` context).

You can rest assured that as long as the component has a highlighted border around it (by default in the color blue) it has focus.

-----

If you want to keep the input cursor visible, you have to do it through the components style framework:
```jsx
<Select
  styles={{
    input: (provided) => ({
      ...provided,
      input: {
        opacity: '1 !important'
      }
    })
  }}
/>
```

**Comment by cubecleveland** [comment]
As always. Spot on. and thanks so much!!!
This indeed solved it....

Im sure not showing the cursor was tested by you and this is indeed the best behavior, but for us it caused confusion.

Thanks again!
