### ISSUE TITLE
Bug in ellipsis view in RTL mode

### ISSUE THREAD

**Issue by HadarHarush** [JedWatson/react-select#5046]
**The situation**: We are in RTL mode. We have 3 options: the first and the second have a long text in the label, and the third with blank text ("") in the label.

**The problem**: When you click the option with the blank text, and then click the option with a text, the ellipsis snaps.

Sandbox: https://codesandbox.io/s/react-select-bug-h5o9k 

https://user-images.githubusercontent.com/77837737/152691890-f3c42eb5-e9f0-4f3f-bd58-5aed64e2206c.mov

**Comment by Rall3n** [comment]
Hello @HadarHarush,

this is a very strange problem. As far as I could reproduce it from your example, this only occurred in a Chromium browser. In Firefox the result was as it should be expected.
Also, I could observe that when selecting the empty option, the scroll position of the "SingleValue" element is not equal to "0", but somewhere at "-110".
I don't think this is a bug caused by this library or even by React itself, but a bug in RTL calculation in Chromium browsers. Therefore, there is not much we can do about it.

But there are solutions implementable on your end:
You can either replace the empty label with the Unicode representation of `&nbsp;` (`\u00A0`), or not provide an option with an empty label.
If you by chance require the empty label to reset the value of the component, then I would recommend you use the `isClearable` prop instead.

**Comment by HadarHarush** [comment]
Thank you very very much

בתאריך יום ב׳, 7 בפבר׳ 2022 ב-10:08 מאת Rall3n ***@***.***>:
