### ISSUE TITLE
loadOptions not properly typed anymore

### ISSUE THREAD

**Issue by josias-r** [JedWatson/react-select#5055]
- The argument `inputValue` provided to `loadOptions` is inferred with type `any`, instead of `string` (unless the second argument, callback, is also extracted) -> type overload seems to be broken.
- The return value of `loadOptions` can be anything, no type error is ever reported.

See example:
https://codesandbox.io/s/react-select-v5-ts-9sxmq

This worked prior to v5

**Comment by Rall3n** [comment]
It's curios that TypeScript can't coalesce the second variant provided in its current typing. Maybe because the function always gets the callback as its second parameter?

**Comment by josias-r** [comment]
Could the problem be that one of the two types for `loadOptions` is
```
((inputValue: string, callback: (options: OptionsOrGroups<Option, Group>) => void) => void)
```
instead of
```
((inputValue: string, callback: (options: OptionsOrGroups<Option, Group>) => void) => Promise<OptionsOrGroups<Option, Group>>) 
```

I don't know why the return type would be `void`.
Maybe the two different return types + two different argument types cause typescrip to report type `any` because it has no clue which one it is of the two.


Also, wouldn't a single type like this (notice the optional callback argument):
```
((inputValue: string, callback?: (options: OptionsOrGroups<Option, Group>) => void) => Promise<OptionsOrGroups<Option, Group>>) 
```
...be sufficient? Instead of having two types for with and without the callback argument

**Comment by Methuselah96** [comment]
The return type is `void` because you should be able to pass in a function that doesn't return a promise. We have an example of that [in the docs](https://github.com/JedWatson/react-select/blob/master/docs/examples/AsyncCallbacks.tsx#L16-L23). If we updated the `loadOptions` type to have the return type always be a `Promise` that example wouldn't compile.

**Comment by josias-r** [comment]
@Methuselah96 Ah yeah of course. That's the point of having a callback. I have no clue where types breaks here 😕

**Comment by Rall3n** [comment]
> Then I have no clue where the types breaks here

I don't know exactly how TypeScript determines which types are applicable, but I believe it checks the source to see where something would apply.

With that in mind I also believe the issue is that we only call the prop with both arguments (`inputValue`, `callback`), never with only the first argument (see [source](https://github.com/JedWatson/react-select/tree/master/packages/react-select/src/useAsync.ts#L120)).

@Methuselah96 Would a change to the old type `(...) => Promise<...> | void` sufficient and acceptable?

**Comment by Methuselah96** [comment]
The attached PR should fix your first bullet point in the original post. I don't think the second bullet point can be fixed since it's an inherent limitation of TypeScript that you're allowed to return anything even if the return type is void. Unless I'm missing something, that's not a regression from the v4 types.

**Comment by Methuselah96** [comment]
Scratch that, let me rethink the solution.

**Comment by Methuselah96** [comment]
I made a PR to go back to the old type.
