### ISSUE TITLE
Width size is incorrect for first option selected in react-select/animated

### ISSUE THREAD

**Issue by manjushsh** [JedWatson/react-select#5205]
Hello,
There is CSS related issue in react-select/animated on version 5.2.0 and later.
If only one option is selected, width of option is about double.

[Actual discussion by @AlfeeAeman](https://github.com/JedWatson/react-select/discussions/5199)

[Bug Sandbox](https://codesandbox.io/s/react-select-multiple-old-forked-6picqk)

**Comment by jleh** [comment]
This seems to be related to React 18 as with React 17 option width size works as expected.

**Comment by kunjaltandel24** [comment]
I am using React 17 and still got this issue.. checked in rendered DOM.
I am face this issue only when selecting value by pressing enter key.
It is some how calculating first select value width based on initial **display: grid** in valueContainer div.

**Comment by NicolasZim** [comment]
I'm having the same issue here.

Also: why the size of the selected options are calculated? Since the `valueContainer` it's flex, there it's no need to fix the value in pixels, in fact if you inspect the element and remove the width attribute the problem it's fixed and works completely fine. It's a browser compatibility thing?
That being said, a workaround would be add a css setting `width` to `unset` in each label container. However I can't to that here.

**Comment by manjushsh** [comment]
@Rall3n It seems like this issue is resolved in release 5.5.2. [Sandbox](https://codesandbox.io/s/react-select-examples-6picqk)

**Comment by Rall3n** [comment]
@manjushsh Thanks for reminding me of this issue.

I will close this as it has been fixed by #5376.
