### ISSUE TITLE
Creatable getNewOptionData and formatCreateLabel cannot be used together

### ISSUE THREAD

**Issue by geisterfurz007** [JedWatson/react-select#5224]
When using the Creatable component, the result of `getNewOptionData` appears to override `formatCreateLabel`.

## Expected behaviour

`formatCreateLabel` - Takes the current input value, returns a string to be displayed as the create option  
`getNewOptionData` - Takes the current input value (once created), returns an Option value to be used going forwards

## Actual behaviour

`getNewOptionData` is already used to format the create option instead of `formatCreateLabel`, see screenshot below and linked CodeSandbox:

![grafik](https://user-images.githubusercontent.com/26303198/173085772-d350b948-129a-4838-b5c8-2b230c418030.png)

https://codesandbox.io/s/react-select-v5-sandbox-forked-7hq73m

**Comment by efossvold** [comment]
I'm getting same issue (v5.3.2)

**Comment by Rall3n** [comment]
Hello @geisterfurz007,

the result of `formatCreateLabel` is used as the second argument of `getNewOptionData` and can be used as follows:

```jsx
 <Creatable
    getNewOptionData={(input, label) => ({ label, value: input, __isNew__: true })}
    formatCreateLabel={(input) => `Create "${input}" option`}
    {...}
/>
```
`getNewOptionData` is also used to format the structure of the final option, but there is no need to distinguish between the two use cases, because in the second case `formatCreateLabel` is not used for the second argument, but the current input value.

------
I will close this issue as it is not a problem with the component per se, but a problem with understanding the props provided.

**Comment by geisterfurz007** [comment]
I really appreciate the response!

So that means there has to be a dedicated property on the object holding the label to make use of this? In my actual usecase (outside the forked sandbox), I really only handle strings so I wrap them in an object which in turn means I have no label/value combination in my object atm. Is there a way around a second field in the object that has the only purpose of serving the formatted label?

**Comment by Rall3n** [comment]
@geisterfurz007 Not necessarily. The property should just be the same as the one you return through `getOptionLabel`.
