### ISSUE TITLE
Migration to SASS?

### ISSUE THREAD

**Issue by nkabardin** [JedWatson/react-select#541]
Hey guys.
What do you think about migrating styles from less to sass?
Let's do that, and also styles can definitely be covered with CSS tests and refactored a bit.

**Comment by twe4ked** [comment]
:+1:

**Comment by JedWatson** [comment]
@subshad has kindly contributed a SASS conversion of the LESS stylesheets, which I just merged (#544)

I actually think that in the future we'll reimplement the styles in JavaScript (probably with JSS, since that's what we're going to use for [Elemental UI](https://github.com/elementalui/elemental/issues/53), but in the meantime it's great to support both.

If you've got any improvements to suggest (or tests for the CSS) they'd be very welcome!

**Comment by nkabardin** [comment]
@JedWatson what do you think about using [react-style](https://github.com/js-next/react-style)? Yeah, in component that is intended to be used as a separate thing, it can be really great option. If you do not have anything against experimenting with react-style, I can play with it and submit a pull request for your review and we can have a high level discussion of how it can help the project.

**Comment by nkabardin** [comment]
Also, it was converted to `scss` and not exactly `sass`. There are still semicolons and brackets, unfortunately.
