### ISSUE TITLE
Map MultiValue

### ISSUE THREAD

**Issue by illiyyin** [JedWatson/react-select#5568]
I'm new on TS,
 
I have onChange props like this 
`onChange={e => setForm(prev => ({ ...prev, required_fields: e?.map(item => item.value) }) )}`

and interface like this 
`onChange: ((newValue: SingleValue<SelectItem> | MultiValue<SelectItem>, actionMeta?: ActionMeta<SelectItem>) => void) `

the component still works functionally, but I got an error on vs code 
`Property 'map' does not exist on type 'SelectItem | MultiValue<SelectItem>'`

is there anything I can do to get rid of vs code error besides using `any`?

**Comment by Rall3n** [comment]
Hello @illiyyin,

the error in your IDE occurs because the value (or in your case `e`) can be both a single option or an array of options.
As the single option is not an array, it does not have the function `map`.

Normally VSCode / TypeScript should infer the typing for the `onChange` parameters from the prop `isMulti` (if `isMulti == true`, use `MultiValue<T>` [or `Array<T>`], else use `SingleValue<T>`).
Do you use the `Select` component as the output of another component? Do you provide the `Select` prop `isMulti` through the props of this other component?

Regardless, you can enforce the correct typing through two ways:
* Set the `IsMulti` generic type on the `Select` component (<code><Select<YourOptionType | unknown, <b>true</b>> ... /></code>).
* Cast your `onChange` value parameter (`e`) as either `MultiValue<YourOptionType | unknown>` or `Array<YourOptionType | unknown>` (`(e as MultiValue<YourOptionType | unknown>)?.map(...)`)
