### ISSUE TITLE
Select is not changing value

### ISSUE THREAD

**Issue by simkesd** [JedWatson/react-select#592]
Hello, I am using Select.Async but cant seem to make it show selected value, even tough onChange shows correct value.
I have this

```
<Select.Async name="form-field-name" 
onChange={this._clientChange} 
autoload={false}
loadOptions={this.getOptions} />
```

options are successfully loaded (also loading bar is working) but when i click any element from select box  input field remains empty. Any idea what could that be? what additional info can i provide?

Im using `"react": "^0.14.1"` and `"react-select": "^1.0.0-beta5",`

**Comment by azaharakis** [comment]
I'm also seeing this behaviour as well with all Beta versions using ```"react": "^0.14.1"```

**Comment by bkniffler** [comment]
+1

**Comment by JedWatson** [comment]
The component now requires you to handle the `value` independently and pass it as a prop, does this help? It looks like you're not passing that in the code you've provided.

Check the examples to see how that works.

(previously, value would be managed internally, but this was causing a lot of problems so that feature has been removed for 1.0.0)

**Comment by bkniffler** [comment]
Ah, I noticed https://github.com/JedWatson/react-select/issues/586 is the problem for me.

**Comment by jonathanasquier** [comment]
+1

**Comment by santosh-k1** [comment]
i have updated the version of react-select to "react-select": "^2.0.0-beta.7", which is  working fine there is no to call the css 

![image](https://user-images.githubusercontent.com/4470369/43393448-cb4aecf6-9414-11e8-8588-ab177466809b.png)
