### ISSUE TITLE
Allow passing classNames to the input element

### ISSUE THREAD

**Issue by petetnt** [JedWatson/react-select#598]
Correct me if I am wrong, but currently you can set the outer element classes via `className` and use `optionRenderer` to add whatever classes you want for the options, but there's currently no way to directly pass classes for the input element. 

Of course use child selectors and the main `<Select>` classNames, if you absolutely need to, but passing `classNames` to the input element itself would be a nice convenience to have for some situations (such as passing validation classes directly et cetera).

**Comment by amit1911** [comment]
+1

**Comment by Sitch** [comment]
+1

**Comment by jjjjeeffff** [comment]
Somewhat related issue, it looks like if you add `className` to `inputProps` it gets applied twice, once to the wrapper and once to the input element itself. Not great when using a CSS framework like Bulma.

**Comment by teamtechalpha** [comment]
+1

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're cleaning up and closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!

**Comment by POTEAMARDEEP** [comment]
+1
