### ISSUE TITLE
onFocus and onBlur not called

### ISSUE THREAD

**Issue by ooflorent** [JedWatson/react-select#625]
**NOTE:** The issue was encountered in `1.0.0-beta5`

When the `<Select/>` component is not `searchable`, neither `onFocus` nor `onBlur` are called when interacting with the component. I don't think it is the expected behaviour.

**Comment by cedricdelpoux** [comment]
+1

**Comment by IgorKirey** [comment]
Seems it doesn't matter for author. So many questions without any response.

**Comment by choonkending** [comment]
@IgorKirey Sometimes a repo maintainer could be busy with their own work and life. I know there might be a lot of issues that do not have a response (and I understand the frustration), but what we can do as a community is to try our best to provide support + try our best to give a hand in projects we care about. That's the power of Open Source right? :)


----

**Issue related info**
Have been encountering the same issue but only on IE Edge.

Browser: `IE Edge (IE13)`
OS: `Windows 10`
react-select version: `beta-13`

The `onBlur` event is working on Chrome and Safari, but not on Edge.

```javascript
            <Select
                {...this.props}
                multi={true}
                searchable={false}
                clearable={true}
                openAfterFocus={true}/>

```

I'm unsure what the root cause is, whether it is a React 15 problem or whether it's a react-select issue.

**Comment by psimyn** [comment]
@choonkending it seems ok for me

Same versions you mentioned but react 0.14.8

Maybe similar to https://github.com/JedWatson/react-select/pull/661

**Comment by loopmode** [comment]
This works just fine:

```
export default class Select extends Component {
    static propTypes = {
        onFocus: PropTypes.func,
        onBlur: PropTypes.func,
    };
    render() {
        return (
            <div onFocusCapture={this.props.onFocus} onBlurCapture={this.props.onBlur}>
                <ReactSelect {...this.props} />
            </div>
        );
    }
}

```

Simply use the capturing phase on a parent element. You handle the event on its "way down" before it even reaches ReactSelect.

**Comment by j-funk** [comment]
I am having this issue in Chrome on v2
