### ISSUE TITLE
[1.0.0-beta6][Async] passing string as value doesn't work when minimumInput is set

### ISSUE THREAD

**Issue by junhanamaki** [JedWatson/react-select#650]
From the code in /examples/src/components/Constributors.js, if I change the Select component to the following it doesn't work:

``` javascript
<Select.Async
  value={this.state.value.github}
  onChange={this.onChange}
  valueKey="github"
  labelKey="name"
  loadOptions={this.getContributors}
  minimumInput={3}
/>
```

What seems to be happening is that after I select the value, the "loadOptions" passed as "onInputChange" runs, and since input was cleaned it will have a length bellow minimumInput, and it will reset the state, or so I think.

Thanks.

**Comment by littletimo** [comment]
I'm seeing something related, but in another form...

1. Search for something that isn't included in the initial autoloaded options
1. Selecting that item from the dropdown will call selectValue()
2. selectValue() updates state.inputValue to ''
3. componentDidUpdate() gets called and calls props.onInputChange(), which for Async calls loadOptions() and replaces my options with the cached ones for the autoloaded options for the blank string
4. Even with props.value set, it won't select anything because the new options are tossed for the originally loaded ones

**Comment by stevoland** [comment]
I've commented on a workaround here: https://github.com/JedWatson/react-select/issues/672#issuecomment-166286246

**Comment by jossmac** [comment]
Version 1 of react-select is no longer supported.

In the best interest of the community we've decided to spend the time we have available on the latest version.

We apologise for any inconvenience.

Please see:

1. [v1 to v2 upgrade guide](https://react-select.com/upgrade-guide)
1. [v1 documentation and examples](v1.react-select.com)
