### ISSUE TITLE
How to have repeated options?

### ISSUE THREAD

**Issue by gugahoi** [JedWatson/react-select#744]
I need to use options that have the same label/value pair multiple times in one dropdown however I get a key conflict warning and only one of them renders.

```
Warning: flattenChildren(...): Encountered two children with the same key, `.$option-4801`. Child keys must be unique; when two children share a key, only the first child will be used
```

Is there a way around this? Does the user have any control on how these keys are generated?

Just for clarity the use case is the following: the dropdown contains teams and it's members (one can select entire teams which include the users or an individual user) and users can be part of multiple teams.

**Comment by Spurlock** [comment]
+1 

My use case is that I have options that share a value, but have different labels. This is to allow the user to find options by whichever label is more intuitive for them. For example, a dropdown that has options for "USA" and "United States", both of which have the value "USA".

Perhaps there could be an setting to generate keys by the array index of the option, rather than its value?

**Comment by patrickbeeson** [comment]
+1

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
