### ISSUE TITLE
jarring ui behavior of 'multi' select

### ISSUE THREAD

**Issue by pdeva** [JedWatson/react-select#767]
In the react-select library, doing a 'multi' select goes like this:
1. you type a character 
2. the dropdown shows up
3. you select the first item
4. the list remains open 
5. you select items 2...n
6. you click outside the dropdown or press esc when done

However, a typical auto complete usually behaves like this:
1. you type a character 
2. the dropdown shows up
3. you select the first item
4. the list closes
5. Go to 1. to select next item 

In this behavior, the user doesnt have to click outside the dropdown to close it. it closes after each item selection.

This is how pretty much all auto completing UIs behave.

The fact that react-select behaves differently is very jarring to the UX.

**Comment by cognipla** [comment]
Hi,
in my opinion react-select behaves correctly by design.
It is 'select' component by name, not 'autocomplete'.
If you want to select more than one value you typically know at the time of selection what you should select. In that case opening the dropdown everytime would be annoying.

I haven't looked at src too much but your proposition could be added as setting as it probably boils down to setting isOpen flag. But I still think it should not be by design.

**Comment by tamagokun** [comment]
have you tried the `autoBlur` option?

**Comment by FutureKode** [comment]
@tamagokun autoBlur doesn't seem to do anything when react select is in multi mode

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
