### ISSUE TITLE
Clearing Select and then tabbing away seems to trigger selection of first item

### ISSUE THREAD

**Issue by jooj123** [JedWatson/react-select#824]
Not sure if this is standard behaviour or not (otherwise ill throw up a PR to try and fix it)

In the example page: https://jedwatson.github.io/react-select/
If i select "Queensland" and then clear it (via back space key) and then click tab on the keyboard it selects the first item. 
It would make sense for it to stay cleared

The only way to currently clear the Select is to perform a backspace and then mouse click somewhere off the control - not an ideal UX

**Comment by seanadenise** [comment]
It looks like this original issue is fixed in version 1.0.0-rc.  However, if you've selected an option, but are currently hovering over a different option, and hit the tab key, it selects the option you were hovering over instead of leaving the option you'd previously selected.  I don't think the tab key should be changing the selected value at all.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
