### ISSUE TITLE
Documentation contains Select.Async

### ISSUE THREAD

**Issue by burimshala** [JedWatson/react-select#866]
This is causing confusion if you try to implement async loading for the first time as Select.Async is never exported.

**Comment by richard-flosi** [comment]
I ran into this too. Then I browsed the source for version 0.9.1 which takes an `asyncOptions` prop which is getting called when I type into the search field. Providing an `asyncOptions` prop seems more natural than using `Select.Async` I'm not sure why using `Select.Async` would be desired, I'd prefer the `prop` based solution since I'm wrapping this component.

To view the repository and README docs for version 0.9.1 start here:
https://github.com/JedWatson/react-select/tree/d8fe544f32dc28e1f72592671f7c70bddae3258a

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
