### ISSUE TITLE
Duplicate items in multi mode (not delete selected item from list)

### ISSUE THREAD

**Issue by khmelevskii** [JedWatson/react-select#874]

**Comment by dherran** [comment]
Would this be it? #882

**Comment by kav** [comment]
I'm running into a similar issue and no it's not #882. Say for example I'm picking ice cream flavors for a group of people. Two want chocolate. If I use the existing control the second time I select chocolate rather than it appearing a second time the first chocolate selection will disappear. Not ideal.

**Comment by kav** [comment]
Looking at v2 this may be doable via the controlled values. I'll investigate there, be nice if I could just tack a gist on for folks

**Comment by aleccool213** [comment]
@kav have one available?

**Comment by kav** [comment]
Let me poke around. I did get it working in my use case back then. I'll see if I can find the code and toss a gist or patch up

**Comment by kav** [comment]
I forked and made the change here: https://github.com/kav/react-select/commits/1dup That fork is way out of date but if you want to cherry pick those changes for a PR or your own fork by all means go ahead. Let me know if you need a hand with any of it. It's been a while but I could probably get back up to speed fairly quickly

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
