### ISSUE TITLE
Use peerDependencies for react reference

### ISSUE THREAD

**Issue by lukemcgregor** [JedWatson/react-select#88]
This means that it will use the version of react referenced by the application. Using different versions causes explode.

article about this here: http://stackoverflow.com/questions/27153166/typeerror-when-using-react-cannot-read-property-firstchild-of-undefined

**Comment by mattdell** [comment]
Yes please. I've been getting this for the past few hours and just narrowed it down to this.

**Comment by JedWatson** [comment]
Thanks for the link to that SO answer; it explains why everyone's opening "make React a peerDependency" issues in my projects.

As far as I can tell, `peerDependencies` is not a valid solution for this package. React-select requires react to function as a standalone component, for testing, examples and build. Listing it as both a `peerDependency` _and_ `devDependency` may work...

However it's just as valid to specify `"react": ">=0.12.0"` in `dependencies`; either you have a compatible version (in which case everything is fine), or you don't in which case _either_ your two reacts explode, or you outright won't be able to `npm install` because npm will block you based on the invalid peer dependency. Until React figures out a way to detect & warn you in the case where you have two instances loaded, neither of the outcomes are great, but for now (0.12 and 0.13) fixing the dependency version will work just fine.

**Comment by JedWatson** [comment]
Updating the dependency seems to have resolved the issue, let me know if it still causes any troubles.

**Comment by ahutchings** [comment]
I believe this issue should be reopened. Declaring react as a dependency rather than a peerdep causes multiple copies of react to be loaded - I believe this is the cause of issue #112. react-router uses the strategy of declaring react as both a peerDependency and a devDependency for testing (https://github.com/rackt/react-router/issues/98).

**Comment by JedWatson** [comment]
I've still got my reservations but have merged #88 so we'll see how it works out :)
