### ISSUE TITLE
Enhancement: Keyboard Support

### ISSUE THREAD

**Issue by jeff3dx** [JedWatson/react-select#918]
**Missing Keyboard Support**

When using **multi**, can't navigate select values using arrow keys.  There is actually no way to access individual select values (to remove for instance) using the keyboard, and no obvious way to access the "clear all" button by keyboard.  Other controls like this (including Semantic UI and Selectize) support arrow key navigation of select items.

**Comment by echenley** [comment]
I believe this line is the issue: https://github.com/JedWatson/react-select/blob/master/src/Select.js#L1031

It should be:

```js
const valueKey = this.props.valueKey
const isOptionEqual = option[valueKey] === focusedOption[valueKey];
```

**Comment by hakunin** [comment]
Its funny since the [x] button gets highlighted when you hit the left button but then there is no way to hit enter / space to press it.

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!
