### ISSUE TITLE
pass through `id` prop 

### ISSUE THREAD

**Issue by macgyver** [JedWatson/react-select#959]
just as `className` is appended to the class name of the rendered element, the passed in `id` attr should be used as the `id` for the rendered element.

This will allow `<Select>` components to work with the alternative label form, e.g.
```jsx
<label htmlFor='my_input'>my input</label>
<Select id='my_input' {...props} />
```

**Comment by banderson** [comment]
I just noticed there's an `inputProps` prop which allows you to set the `id` on the input itself. Can you try that out?

**Comment by macgyver** [comment]
@banderson ooh that works perfectly for my use case, clicking the `label` now can focus the input.

**Comment by kumarharsh** [comment]
@macgyver apparently passing `inputProps` does nothing if the <Select> is not searchable...  [https://github.com/JedWatson/react-select/blob/28281a2c57d176420f0ac26795e4d8492cf5bd62/src/Select.js#L776](This line) renders a `div` instead of an input if the <Select> is not searchable, which causes a label's `htmlFor` to not trigger a focus on the associated select.

**Comment by macgyver** [comment]
that's a bummer :/

**Comment by Vadorequest** [comment]
Indeed, this bug is still present, providing an `id` props doesn't generate an ID in the HTML markup.

**Comment by ItsTarik** [comment]
in version `>=` 2 to set the **id** on the Select use `<Select inputId="foo" />`.
