### ISSUE TITLE
Critical dependences webpack

### ISSUE THREAD

**Issue by guilherme90** [JedWatson/react-select#97]
![sem titulo](https://cloud.githubusercontent.com/assets/2879939/6737197/e361a4aa-ce48-11e4-8122-126e48788ce7.png)

Hello. Can anyone help me solve this problem? Thanks.

**Comment by JedWatson** [comment]
I haven't seen this before, but haven't used webpack recently either. It may be complaining because the `package.json` file points at `/lib/Select.js` which has already been transpiled by babel.

From previous discussions, this is the best option because otherwise you have to configure babel to parse your js files, which you may not want for other packages or your own code; so this is the least opinionated way I have found of packaging the component.

I'll have a play with webpack and see what I can figure out.

**Comment by sebmck** [comment]
@JedWatson The error is being thrown on `dist/react-select.js` which is the browserify build. Only way this could happen is if @guilherme90 is doing `require("react-select/dist/react-select")`.

**Comment by JedWatson** [comment]
Thanks @sebmck, I totally should have caught that.

@guilherme90 you should be able to simply use `Select = require('react-select')` if you're using webpack; you don't need to `dist` build.
