### ISSUE TITLE
Cacheing is too aggressive

### ISSUE THREAD

**Issue by nemothekid** [JedWatson/react-select#99]
I'm not sure what the intended use case for remote options are, but it seems way too aggressive to be useful. The current code simply caches and returns all results for all queries with the same prefix.

For example:

1.) The user enters 's'
2.) The dictionary server returns the first 100 items beginning with s `safe...sanctuary`
3.) The user enters `se`
4.) The user sees no results, because the first query only returned words beginning with `sa` and the cached values used to `s` are used for `se` (and consequently `seahors`)

Is this intended?

**Comment by JedWatson** [comment]
This doesn't sound correct; `react-select` only considers the cache when searching for more specific searches (i.e. `s` -> `se` when it has been told by the server that no further results for more specific queries via the `complete` flag.

You can see this behaviour in action on the [demo page](http://jedwatson.github.io/react-select/) - in the **remote options** example, type `a` to see some results (the async getter returns 3 at a time) then type `b` to see more. If you then type `c` you'll notice there is no further async request, because the 'server' has returned the `complete` flag indicating there are no more results to be found so the loaded options are just filtered client-side.

**Comment by nemothekid** [comment]
I see, it looks like I misunderstood the `complete` option in the callback.
